### ISSUE TITLE
SectionedViewDataSourceType undeclared with cocoapods

### ISSUE THREAD

**Issue by kArTeL** [RxSwiftCommunity/RxDataSources#10]
Cocoapod build appears to be broken, SectionedViewDataSourceType is undeclared.
![captura de pantalla 2016-02-09 a las 3 44 41 p m](https://cloud.githubusercontent.com/assets/3840467/12931574/1f9e796e-cf44-11e5-8b92-4e7900b7b646.png)

**Comment by esttorhe** [comment]
@kArTeL that seems like #4 which was fixed with #5 

Which version of `RxDataSources` are you using?

**Comment by kArTeL** [comment]
Sorry, i was using the master, I changed it to version 0.4 and it works!

**Comment by esttorhe** [comment]
:tada: Glad its working.

Going to close this; feel free to open another issue if needed :bow:
