### ISSUE TITLE
Modify data model when observing

### ISSUE THREAD

**Issue by moonorblue** [RxSwiftCommunity/RxDataSources#100]
Hi, I am new to RxSwift and RxDataSource
I have a pretty basic question but i can not figure it out, on how to modify the data model when observing,
My code is like 
```swift
//Init with data source
 let dataSource = RxTableViewSectionedReloadDataSource<MySection>()
 dataSource.configureCell = { ds, tv, ip, item in
            let cell = tv.dequeueReusableCell(withIdentifier: "Cell") ?? UITableViewCell(style: .value1, reuseIdentifier: "Cell")
            cell.textLabel?.text = " \(item.id)"
            return cell
        }
//Use a view model to call web API service and bind to table view 
viewModel?.fetchData().bindTo(MyTableView.rx.items(dataSource: dataSource)).addDisposableTo(disposeBag)

//I use the method to observe the selected data model
MyTableView.rx.modelSelected(MyListItem.self).subscribe(onNext: { myListItem in
            print("Select cell id: \(myListItem.id!) ")
            //I want to do something like changing the id of my data model, like myListItem.id =  "new id" when selecting the cell, but the item is a "let" variable 
        }).addDisposableTo(disposeBag)
```
My question is that if i want to modify the data model that I selected, how should i do inside the closure ? I think there should be some more "React" way to do this.
In traditional way, I would get the data model in the the delegate method, tableView:didSelectRowAtIndexPath:, with the indexPath,  and modify it
like 
```swift
var myListItem = myDataArray[indexPath.row]
myListItem.id = "new id"
```
Please forgive me for such  question, Thank you

**Comment by kzaher** [comment]
This is not an issue.
Please find some help inside http://rxswift-slack.herokuapp.com/.

**Comment by pjcau** [comment]
@kzaher Hi, I write the same question on rxswift on slack, but i didn't have nothing answer!!! Can you write me ??

Thank
J

**Comment by MobanMichael** [comment]
@moonorblue Did you know the answer now?
