### ISSUE TITLE
How could I get the switcher and stepper's value in the example 4?

### ISSUE THREAD

**Issue by joeytat** [RxSwiftCommunity/RxDataSources#102]
Hi~

I ask this is because of I got few cells with UITextField in it. The cell's initial value is populated with `RxTableViewSectionedReloadDataSource`. 

I don't know how to get those changed text values except iterate all cells.

Please help. Thanks.

**Comment by denis631** [comment]
Don't you just subscribe to the rx values ? 
For example:
textField.rx.text.skip(1).subscribe(onNext: { **Your magic here** }).addDisposableTo(cell.disposeBag)

**Comment by denis631** [comment]
In order to solve the problem of multiple invocation of the onNext block, look at: https://github.com/ReactiveX/RxSwift/issues/437

**Comment by joeytat** [comment]
@denis631 Wow, This's very helpful. Thank you.
