### ISSUE TITLE
RxTableViewSectionedAnimatedDataSource initial bind not working

### ISSUE THREAD

**Issue by dylanshine** [RxSwiftCommunity/RxDataSources#103]
Hello, I am using RxTableViewSectionedAnimatedDataSource to bind a section of cell models:
`typealias PrivateChatsSection = AnimatableSectionModel<String, PrivateChatCellViewModel>`
to my tableview.'

I am having an issue when trying to load the initial data. 
```
		viewModel.privateChatSection
			.bindTo(tableView.rx.items(dataSource: dataSource))
			.addDisposableTo(disposeBag)
```
When I simply declare the binding in viewDidLoad, the tableView does not populate, even when it's receiving a valid section. The tableview will only populate if I manually trigger my service to recreate the cell models and next them to the privateChatSection observable.
```
DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
			self.viewModel.privateChatSection
				.bindTo(self.tableView.rx.items(dataSource: self.dataSource))
				.addDisposableTo(self.disposeBag)
		}
```
If I delay the binding to set until after the API finishes, and privateChatSection contains a valid section, it will populate. What is the best way to handle asynchronous nature of my data in this case?

**Comment by kzaher** [comment]
Hi @dylanshine ,

there are examples in this repository that demonstrates that binding in viewDidLoad should work, I'm assuming it's something on your end.
