### ISSUE TITLE
Expand collapse functionality on sections

### ISSUE THREAD

**Issue by szantogab** [RxSwiftCommunity/RxDataSources#104]
Hi,

I would like to implement expand / collapse functionality on a UITableView. I tried to create a datasource that would wrap around RxDataSource, but when I set my data source to the UITableView, I get a crash saying that the proxy has changed on the table view.

How can this functionality be achieved?

Thanks,
Gabor

**Comment by kzaher** [comment]
Hi @szantogab ,

you can either inherit from one of the data sources in this project or use composition.

**Comment by kzaher** [comment]
This is not an issue.
Please find some help inside http://rxswift-slack.herokuapp.com/.
