### ISSUE TITLE
Question: why does sectionForSectionIndexTitle return 0 by default?

### ISSUE THREAD

**Issue by igorkulman** [RxSwiftCommunity/RxDataSources#105]
When I was implementing `sectionIndexTitles` in my `UITableView` I noticed the index did not work. Tapping any item in the index always scrolled to the first section.  

I took a look at the source code and discovered you do it by default: https://github.com/RxSwiftCommunity/RxDataSources/blob/2bdaa075eee1475b2e1fa20d32a6221cb4107229/Sources/DataSources/TableViewSectionedDataSource.swift#L86

This leads to code like this

````
dataSource.sectionForSectionIndexTitle = { source, title, index in return index }
````

that needs to be added to every `UITableView` with sections.

I wonder why, why doesn't the method just return `index` ? I think it is a reasonable default for most cases.

**Comment by kzaher** [comment]
Hi @igorkulman ,

PR?
