### ISSUE TITLE
configureHeader & configureFooter

### ISSUE THREAD

**Issue by mbalex99** [RxSwiftCommunity/RxDataSources#11]
Maybe I'm missing it but shouldn't we have these two methods?

**Comment by kzaher** [comment]
@mbalex99, yep, RxDataSources are lazy load project :)
We need to wrap all methods :)

We are open to PRs :)

**Comment by damienrambout** [comment]
A table view **data source** is only in charge of providing the **title** of section headers / footers. For this purpose, you can use `titleForHeaderInSection` and `titleForHeaderInSection`.

Providing **custom views** (and height) for section headers / footers is the table view **delegate**'s responsibility.

**Comment by mbalex99** [comment]
@damienrambout thanks!

**Comment by kzaher** [comment]
I think this is probably also solved :) We can reopen this if needed :)
