### ISSUE TITLE
Set license type for GitHub API

### ISSUE THREAD

**Issue by igorkulman** [RxSwiftCommunity/RxDataSources#112]
Your repo has a MIT License but Github and the Github API shows it as "Other". Other repos like RxSwift show the license as MIT (https://github.com/ReactiveX/RxSwift/blob/master/LICENSE.md vs https://github.com/RxSwiftCommunity/RxDataSources/blob/master/LICENSE.md). I think the way to fix this is to edit the license file, set the template for the license as MIT License and then copy your license text back.

I use a script that gets the licenses names for all the libraries my app uses in the Cartfile (https://github.com/pietbrauer/CarthageLicenseScript) and embeds them in the app for legal reasons and this repos shows the license as "Other" instead of "MIT License".

**Comment by kzaher** [comment]
Hi @igorkulman ,

any idea what went wrong with LICENSE in this repo? It's content is the same as RxSwift one.

**Comment by igorkulman** [comment]
I think it is this combobox when editing the license file here in the Github UI.
![screen shot 2017-03-28 at 09 24 39](https://cloud.githubusercontent.com/assets/4746070/24393449/737c4e1e-1398-11e7-9440-3f4e94cd642c.png)

**Comment by kzaher** [comment]
It should work now.

**Comment by igorkulman** [comment]
Thanks
