### ISSUE TITLE
Are you planning to release RxDataSources.framework.zip?

### ISSUE THREAD

**Issue by shindyu** [RxSwiftCommunity/RxDataSources#113]
Hi.
We are using RxSwift. Thank you very much.

I have one question.
Are you planning to release RxDataSources.framework.zip?
With that, the time for carthage update is shortened, I am very happy.

**Comment by kzaher** [comment]
Hi @shindyu ,

It should build really fast if you only do `--platform ios`. So far we are only planning on attaching RxSwift.framework.zip

**Comment by shindyu** [comment]
@kzaher 
Thank you for the advice! I will try!
