### ISSUE TITLE
Missing viewForHeaderInSection on TableViewSectionedDataSource

### ISSUE THREAD

**Issue by patrickbdev** [RxSwiftCommunity/RxDataSources#114]
I noticed there isn't an Rx version of `tableView(_:viewForHeaderInSection:)`.
Is there a particular reasoning for this?
If not, would you accept pull requests implementing this?

**Comment by kzaher** [comment]
This is a delegate method and not data source method :) sorry.

**Comment by patrickbdev** [comment]
I completely forgot @kzaher, fair point. Thanks for your quick response.
