### ISSUE TITLE
Question about UIBindingObserver

### ISSUE THREAD

**Issue by haritowa** [RxSwiftCommunity/RxDataSources#116]
Hello, I'm curious why are u [use](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/DataSources%2BRx/RxTableViewSectionedAnimatedDataSource.swift#L40-L63) `Dispatch.main` in `UIBindingObserver`? Trying to implement something close to RxDataSources for internal usage, so maybe I should adopt your experience :)

**Comment by kzaher** [comment]
Hi @haritowa ,

we had issues with UITableView animations and their state getting out of sync. I think there were some internal UI{Table, Collection}View issues. Collection view is by far the worst.

It was some time ago :)

**Comment by haritowa** [comment]
Ok, thanks for explanation :)
