### ISSUE TITLE
Inserts and deletes cell instead of reloading it

### ISSUE THREAD

**Issue by rslim087g** [RxSwiftCommunity/RxDataSources#118]
In the dispatchQueue (in viewdidload), when I change the value of the first element in `data`. instead of reloading the first cell in the table, it deletes the cell and inserts a new one. I was wondering what I'm doing wrong and how I can fix that! 

          class ViewController: UIViewController {

    
    let dataSource = RxTableViewSectionedAnimatedDataSource<AnimatedSectionModel>()
    let data = Variable([
        AnimatedSectionModel(data: [1,5,6,3])])

    
    let disposeBag = DisposeBag()
    
    @IBOutlet weak var tableview: UITableView!
    
    override func viewDidLoad() {
     
        dataSource.configureCell = {_, tableview, indexPath, title in
            let cell = tableview.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
            cell.textLabel?.text = "\(title)"
            return cell
        }
        
        
   
        data.asObservable()
            .bind(to: tableview.rx.items(dataSource: dataSource))
            .addDisposableTo(disposeBag)
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 4) { 
            self.data.value[0].data[0] = 2
        }
        
    }
}

    struct AnimatedSectionModel {
        var data: [Int]
      }

      extension AnimatedSectionModel: AnimatableSectionModelType {
        typealias Item = Int
          typealias Identity = String
    
       var identity: Identity { return "" }
         var items: [Item] { return data }
    
    init(original: AnimatedSectionModel, items: [Int]) {
        self = original
        data = items
    }
}

**Comment by demchenkoalex** [comment]
Hi @rslim087g 

If you take a look at `AnimatableSectionModelType` protocol you'll see that `Item` should conform to `IdentifiableType` and `Equatable`. You are using `Int` as your `Item` and because `Identity` for `Int` will just return your integer you are actually changing identity which leads to delete-insert animation. Hope that makes sense.

What you want to achieve is to change value, not identity. Here is an example code:
```
struct SectionItem {
    var id: Int
    var data: Int
}

extension SectionItem: IdentifiableType, Equatable {
    typealias Identity = Int

    var identity: Int {
        return id
    }
}

func == (lhs: SectionItem, rhs: SectionItem) -> Bool {
    // Here you should compare all the values you want to trigger reload of the cell
    // If `id` is changed cell will be removed and inserted (because `id` is our identity)
    // If `data` is changed cell will be reloaded
    return lhs.id == rhs.id && lhs.data == rhs.data
}

struct Section {
    var title: String
    var items: [SectionItem]
}

extension Section: AnimatableSectionModelType {
    typealias Item = SectionItem

    var identity: String {
        return title
    }

    init(original: Section, items: [SectionItem]) {
        self = original
        self.items = items
    }
}

class TestViewController: UIViewController {

    let dataSource = RxTableViewSectionedAnimatedDataSource<Section>()
    let data = Variable([Section(title: "", items: [
        SectionItem(id: 0, data: 1),
        SectionItem(id: 1, data: 5),
        SectionItem(id: 2, data: 6),
        SectionItem(id: 3, data: 3)
    ])])

    let bag = DisposeBag()

    @IBOutlet weak var tableview: UITableView!

    override func viewDidLoad() {
        super.viewDidLoad()

        dataSource.configureCell = {_, tableview, indexPath, title in
            let cell = tableview.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
            cell.textLabel?.text = "\(title.data)"
            return cell
        }

        data.asObservable()
            .bind(to: tableview.rx.items(dataSource: dataSource))
            .disposed(by: bag)

        DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
            self.data.value[0].items[0].data = 2
        }
    }
}
```

**Comment by demchenkoalex** [comment]
Accidentally closed :)

**Comment by rslim087g** [comment]
Thank you for the clear response sir! Appreciate it!
