### ISSUE TITLE
Is there a way to check when a tableview is about to insert a cell, or delete a cell?

### ISSUE THREAD

**Issue by rslim087g** [RxSwiftCommunity/RxDataSources#120]
My tableView's cells are configured with the RxTableViewSectionedAnimatedDataSource. Does that expose a method or something thats triggered whenever a cell is added or removed?

i tried this..
tableView.rx.itemInserted
.subscribe(onNext: { (indexPath) in
print("next")
}, onError: { (error) in
print(error.localizedDescription, "error")
}, onCompleted: {
print("completed")
}) {
print("disposed")
}.addDisposableTo(disposeBag) .

but it doesnt seem to get triggered at all when a cell is inserted

**Comment by rslim087g** [comment]
i tried this..    
        tableView.rx.itemInserted
            .subscribe(onNext: { (indexPath) in
                print("next")
            }, onError: { (error) in
                print(error.localizedDescription, "error")
            }, onCompleted: {
                print("completed")
            }) {
                print("disposed")
            }.addDisposableTo(disposeBag) . 


but it doesnt seem to get triggered at all

**Comment by LarsJK** [comment]
Curious if you found a way to do this?

**Comment by patrickbdev** [comment]
@rslim087g @LarsJK 
Encountered the same issue where `rx.itemInserted` doesn't get called. Were either of you able to figure it out?

**Comment by patrickbdev** [comment]
Looks like `rx.itemInserted` is part of RxCocoa, not RxDataSources, found your other ticket: https://github.com/ReactiveX/RxSwift/issues/1210
