### ISSUE TITLE
Adding item to empty section causes animation bug

### ISSUE THREAD

**Issue by semireg** [RxSwiftCommunity/RxDataSources#121]
When the first item is added to a section the section header doesn't animate properly. 

![rx data sources isue](https://cloud.githubusercontent.com/assets/1819762/25253254/c144a2cc-25e5-11e7-9c1e-2d020c31a1ef.gif)

We are using this logic for title headers:

```
        presenter.dataSource.titleForHeaderInSection = { [weak self] (dataSource, section) -> String? in
            guard let strongSelf = self, strongSelf.showSectionHeaders else { return nil }
            let section = dataSource[section]
            guard !section.items.isEmpty else { return nil }
            return section.header
        }
```

The work-around, which I admit is more proper code, is to make sure that empty sections don't exist.

**Comment by kzaher** [comment]
Hi @semireg ,

We don't do any special magic, just forward calls. Why do you think this is data sources issue?

**Comment by semireg** [comment]
It might not be a data sources issue, per se, but it could be a combination of updating the section's label without it receiving a setNeedsLayout or layoutSubviews call.

It looks like the section view height isn't being updated properly. If you look closer, notice how the section background is still gray. I'm not sure what the work-around would be in RxDataSources... but at least it's documented somewhere as to what was happening.  👍
