### ISSUE TITLE
Row Height ?

### ISSUE THREAD

**Issue by Arnoymous** [RxSwiftCommunity/RxDataSources#124]
How can I update the row height for a kind of model ?
I use a **RxTableViewSectionedAnimatedDataSource** with 1 section and 3 different kind of cell, how can I have access to **tableView:heightForRowAtIndexPath** ?

**Comment by sergdort** [comment]
Hi, @Arnoymous is it `UITableViewDelegate` method?

**Comment by Arnoymous** [comment]
yes ! how can i update this value ? @sergdort

**Comment by sergdort** [comment]
I guess, you emit new data with updated height (or content if you are using autolayout), which should cause reload item at indexPath and change height of the cell

**Comment by Arnoymous** [comment]
ok, my cells have fixed height, actually I use auto layout to update my cells height but i guess access to the tableView:heightForRowAtIndexPath is better for performances.

**Comment by Arnoymous** [comment]
fixed with 

```
self.tableView.rx.setDelegate(self)
            .disposed(by: disposeBag)
```
