### ISSUE TITLE
Preventing first responder to resign on tableview reload

### ISSUE THREAD

**Issue by rbresjer** [RxSwiftCommunity/RxDataSources#126]
Hi all,

I'm working on a screen very similar to an appointment detail screen in a calendar. I have a UITableView with lot of cells, each cell containing an input for a property of the appointment.

Amongst these cells I have a cell for the appointment start time and one for the appointment end time. Both contain a UITextField with a UIDatePicker as inputView. I've used Rx to bind the chosen date in the picker to the value in UITextField, that works fine.

I also have a binding between the start time and end time: e.g. if the user selects a start time past the end time, the end time should shift. I've made a binding between my view model where all the appointment details are stored, and the UIDatePicker values. RxDataSources (with a RxTableViewSectionedAnimatedDataSource) makes sure the cells are automatically updated.

However, this updating makes the UITableView to resign the first responder (the UIDatePicker) when the user picks a new date (because of the default UITableView behaviour on reloadData?). I changed this so the date in the view model is only updated on UIControlEvents.editingDidEnd, but that looks weird (because the dates are not updated instantaneously).

What would be the best way to preserve the first responder but be able to update cell values in realtime?

Thanks,
Rutger

**Comment by avdwerff** [comment]
As far as I know, RxTableViewSectionedAnimatedDataSource should do delta updates.. are you specifically calling reload on your tableview? When binding the datasource on the tableview this should not have to be case.

**Comment by kzaher** [comment]
This is not an issue.
Please find some help inside http://rxswift-slack.herokuapp.com/.
