### ISSUE TITLE
Supplementary View Factory Optional ?

### ISSUE THREAD

**Issue by Arnoymous** [RxSwiftCommunity/RxDataSources#128]
why dataSource.supplementaryViewFactory don't allow optional UICollectionReusableView?
how can i only set footer but no header ?

**Comment by kzaher** [comment]
Hi @Arnoymous ,

I think this doesn't allow returning non optional items.
```
@available(iOS 6.0, *)
    optional public func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView
```
