### ISSUE TITLE
How can I use RxDataSource for collectionviews with custom delete animation?

### ISSUE THREAD

**Issue by bidadh** [RxSwiftCommunity/RxDataSources#130]
Hi,

I'm currently using RxDataSource in a project to bind to a collection view which is great.

I want to add animation to delete an item.
The issue is when I update the model binding will update the items immediately without custom animations and when I try to trigger the deletion + animation app crashes which make sense.
I'm wondering is there a way to add the animation to the DataSource/Binding so that it use the animation?

Thanks

**Comment by sergdort** [comment]
Hi, @bidadh I feel like this functionality is not part of `UICollectionViewDataSource`

**Comment by bidadh** [comment]
@sergdort 
Hi and thanks for your reply.

Yes, basically it's part of the CollectionViewLayout and the way I do this is I override finalLayoutAttributesForDisappearingItem and then when I want to delete an item I'll do the following:

```swift
records.remove(at:index)
UIView.animate(withDuration: 0.65, delay: 0.0, options: UIViewAnimationOptions(), animations: { () -> Void in
    self.collectionView!.deleteItems(at: indexPaths)
}) { (finished: Bool) -> Void in
    cleanup()
}
```

however, using RxDataSource, I bind the model to collectionView items and as soon as I update model, CollectionView gets updated and refreshes the cells. so I cannot animate 


does it make sense?

**Comment by kzaher** [comment]
Hi @bidadh ,

please use AnimatedDataSource for animations.

**Comment by bidadh** [comment]
Thanks @kzaher
