### ISSUE TITLE
Multiple custom cells dynamically sprinkled throughout 3 sections?

### ISSUE THREAD

**Issue by bboy79** [RxSwiftCommunity/RxDataSources#133]
Hi! I'm not sure if I can use RxDataSources for this, but I have 3 different sections and a bunch of data rows that come either from a network call or a push notification. 

Each data row is then represented on a specific custom table view cell, depending on its type. Each section represents one of three cases - "today", "yesterday" and "before" - and the cells must be placed on their respective section, given the time of their creation. 

I've tried following Example 4 but the problem with using enums is that I can't add any new cells that arrive to the already created sections, ending up creating new sections just for these cells. Is it possible to replace enums with protocols or something similar? (using protocols was actually my first approach before trying out the example, but either I did something wrong or it didn't work). 

Not sure if I made myself clear, but I can elaborate and provide examples if needed. Any help at all would be appreciated. Thank you!

**Comment by sergdort** [comment]
Hi, @bboy79 

If you provide example it would be great! :)

**Comment by bboy79** [comment]
Sure!

So, this is what I have right now (mind that it is still in an alpha state, so it's not pretty!): 
[http://i.imgur.com/VWZkQXC.png](url)

And this is what I want to achieve:
[http://i.imgur.com/mTkE5j7.png](url)

The sections are the rows where you can read "Hoje", "Ontem" and "Anteriores" (sorry for not having this in english, but the original design layouts are in my language).

This is what I got for the sections' enum:


```
 enum ActivitiesBySection {
    case Section(title: String, items: [ActivityItemType])
}

enum ActivityItemType {
    case TextOnly(activity: Activity)
    case WithPictures(activity: Activity)
    case WithVideo(activity: Activity)
    case Unimplemented  // For development purposes
}

extension ActivitiesBySection: SectionModelType {
    typealias Item = ActivityItemType
   
    var items: [ActivityItemType] {
        switch self {
        case .Section(_, items: let items):
            return items.map { $0 }
        }
    }
    
    init(original: ActivitiesBySection, items: [Item]) {
        switch original {
        case .Section(title: let title, _):
            self = .Section(title: title, items: items)
        }
    }
}

extension ActivitiesBySection {
    var title: String {
        switch self {
        case .Section(title: let title, _):
            return title
        }
    }
}
```

And the configureTableCells part:

```
func configureTableCells(dataSource: RxTableViewSectionedReloadDataSource<ActivitiesBySection>) {
        dataSource.configureCell = { dataSource, table, indexPath, item in
            
            switch dataSource[indexPath] {
            case .WithPictures(let activity):
                let cell: PictureCell = table.dequeueReusableCell(withIdentifier: PictureCell.identifier, for: indexPath) as! PictureCell
                cell.mViewModel = PicturesViewModel(dataManager: DataManagerImpl.sharedInstance, activity: activity)
                return cell
                
            case .TextOnly(let activity):
                let cell: GeneralTextCell = table.dequeueReusableCell(withIdentifier: GeneralTextCell.identifier, for: indexPath) as! GeneralTextCell
                cell.mViewModel = GeneralTextViewModel(dataManager: DataManagerImpl.sharedInstance, activity: activity)
                return cell
                
            default:
                print("Unimplemented activity")
            }
            
            return UITableViewCell()
        }
        
        dataSource.titleForHeaderInSection = { dataSource, index in
            let section = dataSource[index]
            
            return section.title
        }
    }

```

The data comes from a network request. I'll just paste the subscribe event where I store the data, for completeness sake:

```
<getData>
.subscribe(onNext: { [unowned self] activity in
                switch activity.type! {
                case AppConstants.ACTIVITY_SELFIE_SEND, AppConstants.ACTIVITY_DRAWING_SEND:
                    self.activities.value.append(ActivitiesBySection.Section(title: self.getSectionTitleForDate(date: activity.createdAt!),
                                                                             items: [.WithPictures(activity: activity)])) // self.activities is of type Variable<[ActivitiesBySection]>
                    
                case AppConstants.ACTIVITY_APP_BATTLE,
                     AppConstants.ACTIVITY_APP_STARTED,
                     AppConstants.ACTIVITY_APP_LEVEL_UP,
                     AppConstants.ACTIVITY_LOGIN,
                     AppConstants.ACTIVITY_LOGOUT:
                    self.activities.value.append(ActivitiesBySection.Section(title: self.getSectionTitleForDate(date: activity.createdAt!),
                                                                             items: [.TextOnly(activity: activity)]))
                default:
                    print("Unimplemented")
                }
            })
...
```

When I began the development, I was kinda hoping that the items array inside the enum would let me append new items (I've been working with Swift for a month now), but that obviously isn't the case. As such, with this solution, I end up with the result on the first image above. What I was asking on my previous post was if it is possible to replace the ActivityBySection and ActivityItemType enums with protocols, so that I can implement them and add new elements to the items array, that way being able to have only 3 sections with all data, instead of creating a section for each row. Yes, I could aggregate all data rows by section type before placing them in the actual sections, but the app is supposed to receive push notifications with new data and, in this case, the problem remains. 

Sorry for the wall of text, and hopefully I made myself clear this time. I'm going on vacation for the next few days, so I might take some time to answer possible future posts. Thank you in advance!

**Comment by kzaher** [comment]
This is not an issue.
Please find some help inside http://rxswift-slack.herokuapp.com/.

**Comment by bboy79** [comment]
Since I got asked about this yesterday, I'm just gonna leave it here. I solved this mostly by replacing all enums with structs. Examples 3 and 4 (in the repository) helped me a lot as well.

**Comment by AjayGirolkar** [comment]
Rx is really frustrating.
