### ISSUE TITLE
Observe datasource changes for use with UITableView

### ISSUE THREAD

**Issue by chetem** [RxSwiftCommunity/RxDataSources#134]
Is there a way to observe when items have been added or removed from the data source?

I want observe when items have been added to the data source (and therefore, rows added to the tableview). I see there's a wrapper `itemsInserted`, but this only seems to detect inserts caused by the built-in table view editing (i.e. it's just a wrapper for `tableView:commitEditingStyle:forRowAtIndexPath:`). If I update my datasource by other means, how can I observe when new rows have been added to the tableview?

I'm pretty new to Rx so sorry if it's a dumb question. Thanks for any help!

**Comment by kzaher** [comment]
This is not an issue.
Please find some help inside http://rxswift-slack.herokuapp.com/.
