### ISSUE TITLE
UITableViewCell height?

### ISSUE THREAD

**Issue by mr** [RxSwiftCommunity/RxDataSources#137]
I want to use `heightForRowAtIndexPath`, but I need to have the data in the datasource to know what to return. I feel like there should be another closure I can add like `configureCell` to the datasource that would provide the datasource, tableview, indexpath, and the item, and you'd return the size.

Is there any way I can make something like this?

**Comment by freak4pc** [comment]
`heightForRowAtIndexPath` is a delegate method ant not a datasource one. As such, this library doesn't deal with it. RxDataSources is a mere delegate proxy to the Data Source, all other things should work as usual so I don't see why you would need a special overload to achieve what you want? 

Can't you just access the same model data and calculate whatever height is needed there?

**Comment by mr** [comment]
The problem is that my data is contained entirely in an Observable stream that gets driven into the datasource. If I overload `heightForRowAtIndexPath` I get the index path but not the actual data. I can't look up the data at that index path since I can't poke into the Observable stream from the outside. My model data may change based off conditions of the stream so I can't assume a size for a given index path.

**Comment by freak4pc** [comment]
Uhm that's a good use case. I don't use RxDataSources so I'm not absolutely sure. I'll leave this for someone else to answer.

**Comment by sergdort** [comment]
Hi guys! 
There is there is `subscript` overloads where you can get item for index path from datasource. Example usage [here](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example1_CustomizationUsingTableViewDelegate.swift#L81)

**Comment by mr** [comment]
Thanks! I  also figured out using model(at: IndexPath) which can be used similarly. Is there any major difference between the two?

**Comment by RamwiseMatt** [comment]
With regards to the `subscript` on the datasource: what is the suggested approach for out-of-bounds checking? The method returns a non-optional, though the `IndexPath` that is passed in might not have a matching item in the datasource.
