### ISSUE TITLE
Linker error when integrating via Carthage with --no-build

### ISSUE THREAD

**Issue by lyricsboy** [RxSwiftCommunity/RxDataSources#138]
I'm attempting to use Carthage dependencies with the --no-build option, incorporating their associated projects into my application project's workspace manually.

This works well enough for RxSwift and several others, but something about automatic target dependency resolution is breaking the link step when I try to use RxDataSources.

Specifically, if I add the RxDataSources.framework as an embedded binary in my app target and try to build the app, Xcode will assume it should build the "RxDataSources" target, and the link step fails with:

> Framework not found Pods_RxDataSources

If I delete the RxDataSources target from the RxDataSources project, it will find (correctly?) the "RxDataSources-iOS" target as a dependency, and build that with no linker errors.

I'm not quite sure whether the solution would be a workaround on my side, or a configuration change in this project... any ideas?

**Comment by lyricsboy** [comment]
I notice that RxSwift only has targets ending in `-iOS` (etc) and no plain `RxSwift` target. Is it possible to configure RxDataSources in this same way? Is the RxDataSources target needed?

**Comment by kzaher** [comment]
Hi @lyricsboy ,

hm, can you check out does https://github.com/kzaher/RxFeedback work for you. If it does, maybe we can refactor this project to do the same.

**Comment by lyricsboy** [comment]
@kzaher I tried to incorporate RxFeedback in the same project in the same manner, and with that I encounter a different problem.

Something related to the way RxFeedback incorporates RxSwift as a submodule dependency is causing the RxSwift-iOS framework target to be built independently (a second time, after my target's build phase has already built it). This then fails to code sign the RxSwift.framework:

```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none .../Build/Products/Debug-iphonesimulator/RxSwift.framework

.../Build/Products/Debug-iphonesimulator/RxSwift.framework: No such file or directory
Command /usr/bin/codesign failed with exit code 1
```

If I had to guess I'd say that my own RxSwift submodule build process is attempting to write and manage the same output product as the RxFeedback RxSwift submodule build process, and this is causing the pain.

**Comment by kzaher** [comment]
Hi @lyricsboy ,

I'm sorry to hear that. I'm not sure how to resolve this. It seems to me that child project will always need to contain RxSwift dependency.

**Comment by lyricsboy** [comment]
This repository uses Carthage and/or CocoaPods to incorporate RxSwift as a dependency, which is fine (Carthage will resolve the dependency graph to a single RxSwift submodule checkout).

The problem described in the original issue is the presence of two separate targets for the iOS platform (RxDataSources and RxDataSources-iOS). Is there a reason for the RxDataSources target to exist? It doesn't appear to be referenced by the shared schemes. If that could be removed, as I have done in my fork, I think that would resolve this issue.

**Comment by kzaher** [comment]
I would like to support somehow all package managers and using git submodules.

The other target is for CocoaPods.

**Comment by kzaher** [comment]
We've removed two targets, should be ok now.
