### ISSUE TITLE
disable animations on RxTableViewSectionedAnimatedDataSource

### ISSUE THREAD

**Issue by Arnoymous** [RxSwiftCommunity/RxDataSources#141]
how can i disable animations on RxTableViewSectionedAnimatedDataSource without using RxTableViewSectionedReloadDataSource ?
i have a subclass of my controller with animatedSection and i want to create the same controller to search on my tableView without animations
thx

**Comment by sergdort** [comment]
Hi, @Arnoymous!
There is `animationConfiguration` property

**Comment by Arnoymous** [comment]
yes but settings insertAnimation/reloadAnimation/deleteAnimation to UITableViewRowAnimation.none do nothing, it's animated

**Comment by sergdort** [comment]
Hm..

I would recommend you to do something like

```
class ClassA: UIViewController {
    
    func dataSourceProvider() -> TableViewSectionedDataSource<Section> {
        return RxTableViewSectionedAnimatedDataSource<Section>()
    }
}

class ClassB: ClassA {
    override func dataSourceProvider() -> TableViewSectionedDataSource<Section> {
        return RxTableViewSectionedReloadDataSource<Section>()
    }
}
```

**Comment by Arnoymous** [comment]
nice idea thx !

**Comment by Arnoymous** [comment]
class RxTableViewSectionedDataSource { 
               static func new<S: AnimatableSectionModelType>(animated: Bool) -> TableViewSectionedDataSource<S> {
                       switch animated {
                       case true:
                           return RxTableViewSectionedAnimatedDataSource<S>()
                       case false:
                           return RxTableViewSectionedReloadDataSource<S>()
                       }
               }
       }

**Comment by Arnoymous** [comment]
hmmm, actually we can't, to bind items in dataSource the dataSource need RxTableViewDataSourceType and TableViewSectionedDataSource doesn't have one

**Comment by Arnoymous** [comment]
can you make property "dataSet" of RxTableViewSectionedAnimatedDataSource/RxCollectionViewSectionedAnimatedDataSource open ?

so we can subclass and force dataSet to false to reload and don't animate, like : 



            private var _dataSet = false

            private var dataSet: Bool {
                  get {
                        if isAnimationEnabled {
                              return  _dataSet
                        }
                        return false
                  } set {
                        _dataSet = newValue
                  }
            }
            var isAnimationEnabled = true

**Comment by sergdort** [comment]
I think you can just subclass of `RxTableViewSectionedAnimatedDataSource`

**Comment by Arnoymous** [comment]
no we can't, wee need to have access to the dataSet property :/ @sergdort

**Comment by sergdort** [comment]
This should work, right?

```swift
final class MyRxTableViewSectionedAnimatedDataSource<S: AnimatableSectionModelType>: RxTableViewSectionedAnimatedDataSource<S> {
    var shouldAnimate: Bool = false
    
    override func tableView(_ tableView: UITableView, observedEvent: Event<[S]>) {
        if shouldAnimate {
            super.tableView(tableView, observedEvent: observedEvent)
        } else {
            UIBindingObserver(UIElement: self) { dataSource, element in
                    dataSource.setSections(element)
                    tableView.reloadData()
            }.on(observedEvent)
        }
    }
}
```

**Comment by Arnoymous** [comment]
yea thx it work :) 
maybe you can add this functionality natively ?

**Comment by sergdort** [comment]
I think we did it =) By opening class for subclassing
