### ISSUE TITLE
Disable autoscrolling on datasource change

### ISSUE THREAD

**Issue by jasin755** [RxSwiftCommunity/RxDataSources#142]
How Can I disable autoscrolling to top when datasource changed? More:
https://stackoverflow.com/questions/44928752/how-disable-automatic-scrolling-to-top

**Comment by sergdort** [comment]
May be this issue will help #89

**Comment by jasin755** [comment]
estimatedRowHeight = 1 (lower than smallest cell in table) fixed it.

**Comment by sergdort** [comment]
I think we can close this one
