### ISSUE TITLE
Data change with animations causes DifferentiatorError.invalidInitializerImplementation

### ISSUE THREAD

**Issue by RamwiseMatt** [RxSwiftCommunity/RxDataSources#144]
I'm getting a `DifferentiatorError.invalidInitializerImplementation` when the data bound to the UITableViewCells changes, but only when using `RxTableViewSectionedAnimatedDataSource`. It's fine when using `RxTableViewSectionedReloadDataSource` (though then I don't have animations, obviously). The error is pretty cryptic and I have no idea how to resolve it.

The full error, should you be interested:

	fatal error: 

	Wrong initializer implementation for: ageSection(
	[MyProject.AmountSectionItem.ageSectionItem(age: 44, itemIndex: 0),
	 MyProject.AmountSectionItem.ageSectionItem(age: 5, itemIndex: 1),
	  MyProject.AmountSectionItem.ageSectionItem(age: 88, itemIndex: 2)])

	Expected it should return items: 
	[MyProject.AmountSectionItem.ageSectionItem(age: 44, itemIndex: 0), 
	MyProject.AmountSectionItem.ageSectionItem(age: 5, itemIndex: 1)]

	Expected it should have id: ageSection: file .../Pods/RxDataSources/Sources/DataSources/DataSources.swift, line 31
	(lldb) 

(The convoluted types are due to the suggested approach when dealing with multiple sections)

Since the data flows through the system correctly when turning animations off, I'm not sure what I can do to fix the problem. I have implemented `AnimatableSectionModelType` on my section model, I have implemented `IdentifiableType` and `Equatable` on the relevant type (`AmountSectionItem` in this case). What is happening here?

**Comment by sergdort** [comment]
@RamwiseMatt Are you sure that all items are unique?

**Comment by RamwiseMatt** [comment]
Unique in what way? The `IdentifiableType` compliance returns a different identity for each item.


	extension AmountSectionItem : IdentifiableType, Equatable {
		typealias Identity = String
		
		var identity : Identity {
			switch self {
			case let .ageSectionItem(age, itemIndex):
				return "ageSectionItem_\(age)_\(itemIndex)"
			}
			// Omitted other cases for conciseness, but they are different.
		}
		
		static func ==(lhs: SelectAmountSectionItem, rhs: SelectAmountSectionItem) -> Bool {
			return lhs.identity == rhs.identity
		}
	}

**Comment by igorkulman** [comment]
Having the same problem since upgrading my project to Swift 4. All items are unique.

**Comment by igorkulman** [comment]
The problem is at https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/Differentiator/Diff.swift#L16 where `self.items != safeItems` is evaluated as `true` even when both arrays have the same items. Tried it in debugger, the length was the same and items at each index were equal.

**Comment by igorkulman** [comment]
Ok, I fixed it, changed the ctor of my custom `AnimatableSectionModelType` defined as
````
enum AnimatableLoaderSectionModel {
    typealias Item = AnimatableLoaderSectionModelItem
    case ItemsSection(items: [Item])
    case LoaderSection
}
````
from
````
init(original: AnimatableLoaderSectionModel, items _: [AnimatableLoaderSectionModelItem]) {
        self = original
}
````
and I changed it to
````
init(original: AnimatableLoaderSectionModel, items: [AnimatableLoaderSectionModelItem]) {
        switch original {
        case .ItemsSection(items: _):
            self = .ItemsSection(items: items)
        case .LoaderSection:
            self = .LoaderSection
        }
    }
````
meaning instead of using the section that comes in as a parameter (with its items) I am now creating a new section of the same type but with the items from the second parameter.

So my recommendation @RamwiseMatt is to look at your ctor.
