### ISSUE TITLE
Please create branch so that I can create pull request for Swift 4 support

### ISSUE THREAD

**Issue by svdo** [RxSwiftCommunity/RxDataSources#145]
Hi,

I have created a fork and converted RxDataSources for Swift 4. I want to create a pull request for that work, but the pull request has to be done to a new branch in your repository. I have named the branch 'swift4.0' so that the name is identical to the branch name in RxSwift and RxCocoa.

In other words: please create a new branch 'swift4.0' in your repository, and I'll create a pull request for Swift 4 support!

Thanks!

**Comment by svdo** [comment]
By the way, my fork is here: https://github.com/svdo/RxDataSources/tree/swift4.0.

**Comment by sergdort** [comment]
I thin it was merged 
https://github.com/RxSwiftCommunity/RxDataSources/pull/146
