### ISSUE TITLE
UICollection view with RxCollectionViewSectionedAnimatedDataSource not animating

### ISSUE THREAD

**Issue by loringit** [RxSwiftCommunity/RxDataSources#147]
Hello!

I'm using RxCollectionViewSectionedAnimatedDataSource. Animation isn't set as none, however there is no animation in collection view at all. The animation doesn't work in cells either.

How can it be connected to dataSources or there is no relation between it and my issue?

**Comment by sergdort** [comment]
If there is no animation I believe you've implemented `AnimatableSectionModelType ` as internally `RxCollectionViewSectionedAnimatedDataSource ` fallback to not animated updates in case of ambiguity

**Comment by loringit** [comment]
I solved the problem. The animation didn't work because I made a mistake implementing cells identity. The issues can be closed now.
