### ISSUE TITLE
when I use RxTableViewSectionedAnimatedDataSource, how to disable animate effect

### ISSUE THREAD

**Issue by punan** [RxSwiftCommunity/RxDataSources#148]
I want to know that how to disable RxTableViewSectionedAnimatedDataSource animate effect?
I try to set animationConfiguration property to AnimationConfiguration(insertAnimation: .none, reloadAnimation: .none, deleteAnimation: .none), but it doesn't work.

**Comment by sergdort** [comment]
This is duplication of #141
