### ISSUE TITLE
Detach diff algorithm from main module.

### ISSUE THREAD

**Issue by muukii** [RxSwiftCommunity/RxDataSources#149]
RxDataSources has very excellent diff algorithm API.
I think that it should detach from RxDataSources module.
And then, it will be the more flexible framework.

It's good if it has patch API (just like this https://github.com/wokalski/Diff.swift)

Actually, I use diff algorithm of RxDataSources for ASCollectionNode of AsyncDisplayKit.

What do you think?
Thanks for the awesome library.

**Comment by kzaher** [comment]
Hi @muukii ,

yeah, sure. Can you help to decouple the projects? I've got my hands full with RxSwift repo right now?

**Comment by muukii** [comment]
@kzaher 

Thanks
I'll try to decouple the projects.
