### ISSUE TITLE
Consider using CollectionType instead of Array for SectionModelType

### ISSUE THREAD

**Issue by damienrambout** [RxSwiftCommunity/RxDataSources#15]
Hi,

Have you considered using a more generic `CollectionType` as type of the `items` property of `SectionModelType` (instead of `[Item]`). This might allow the use of lazy collections for table views / collection views with a very large dataset.

Would that be possible, or am I missing something ?
Maybe it would be useless for animated sectioned data sources though, due to their need to compare sections and rows to each others.

Tell me what you think about it.

Btw, thanks for all the wonderful Rx extensions :-)

Cheers,

Damien

**Comment by kzaher** [comment]
Hi @damienrambout ,

yes, I don't think there is anything we would gain because of the diffing algorithm, but thnx for making a suggestion.

**Comment by damienrambout** [comment]
I think diffing is not required for non animated datasources (since it simple performs a `reloadData()`). 
So `CollectionType` might be useful in these cases.

**Comment by kzaher** [comment]
If you are dealing with user interface, you will want O(1) complexity while accessing by index so sooner or later you'll need to fallback to `Array` :)

¯\\\_(ツ)\_/¯

**Comment by damienrambout** [comment]
@kzaher You're have a very good point here :)
Closing the issue.
