### ISSUE TITLE
[Request]Public AnimationConfiguration

### ISSUE THREAD

**Issue by dangthaison91** [RxSwiftCommunity/RxDataSources#152]
Hi @kzaher , you may know that I'm porting RxDataSources to support AsyncDisplayKit [here](https://github.com/dangthaison91/RxTextureDataSources).

And I need your help to make all AnimationConfiguration's properties as public. So I don't need to create another `AnimationConfiguration` in my repo.

- Expected:
```Ruby
public struct AnimationConfiguration {
  public let insertAnimation: UITableViewRowAnimation
  public let reloadAnimation: UITableViewRowAnimation
  public let deleteAnimation: UITableViewRowAnimation
```
Thanks

**Comment by kzaher** [comment]
Hi @dangthaison91 ,

maybe you can synchronize your efforts with @muukii . It looks like he is doing the same thing.
Please take a look at this issue.
https://github.com/RxSwiftCommunity/RxDataSources/issues/149

**Comment by dangthaison91** [comment]
May be @muukii in WIP and not push his code yet. At the moment, I just want to create a simple port of RxDataSources: https://github.com/dangthaison91/RxTextureDataSources

I also interest with IGListKit and tending to create a Rx extension for it. But it is a different story.

**Comment by muukii** [comment]
@dangthaison91 
Sorry! I've pushed my WIP branch. #153 
But, I don't determine the direction about detaching.
I think good that AnimationConfiguration's properties make public ahead.
Then, that changes will be included my PR (#153)
What do you think?

**Comment by dangthaison91** [comment]
@kzaher @muukii I was on vacation last week. Glad to know #154 was merged. Looking to version 2.0.

**Comment by zboralski** [comment]
@dangthaison91 how's the progress on the IGListKit rx extension? Is it really worth using IGListKit's diffable algorithm compared to RxDatasources?

**Comment by dangthaison91** [comment]
@zboralski I never ever trying to use IGListDiff to replace RxDataSource's diff algorithm. I just ported RxDataSource to support AsyncDisplayKit/Texture. You can find it here https://github.com/RxSwiftCommunity/RxASDataSources
