### ISSUE TITLE
No such module "Differentiator"

### ISSUE THREAD

**Issue by 1cookspe** [RxSwiftCommunity/RxDataSources#156]
In "CollectionViewSectionedDataSource.swift", located at "https://github.com/RxSwiftCommunity/RxDataSources/blob/c883beb687d288b55d61c90d75059ed5fcb63c1c/Sources/RxDataSources/CollectionViewSectionedDataSource.swift", I receive a "No such module 'Differentiator'" error on line 14: "import Differentiator".

![screen shot 2017-08-13 at 5 46 38 pm](https://user-images.githubusercontent.com/8737691/29253611-a3263b56-804f-11e7-8bcf-3f4218d6190a.png)

Any ideas on how I can solve this? I have tried update the pod that I used to install RxDataSources. Thanks for any help!

**Comment by kzaher** [comment]
We still haven't published `Differentiator`. I'll do that this week.

**Comment by freak4pc** [comment]
@kzaher Might also be worthwhile for the dependency to Differentiator reference a local path since it's part of the project anyways and not in a different repository ?

**Comment by kzaher** [comment]
I've published the pods today.

**Comment by freak4pc** [comment]
@1cookspe Can you confirm ?

**Comment by robertwijas** [comment]
Same issue with Carthage.

**Comment by freak4pc** [comment]
Uhm not sure how Carthage works. I remember it needs to be an actual "Release" for it to work, but since both of them are in the same repo, not exactly sure how this looks. Ideas? @kzaher

**Comment by 1cookspe** [comment]
I have updated 'RxDataSources' but it still gives me this error. Any help would be much appreciated.

**Comment by kzaher** [comment]
I've pushed new version, 2.0.1.

Differentiator scheme wasn't shared in 2.0.0. I've also published pod but it's a bit harder to tell will it now work since I've also published it two days ago and it worked for me back then.

¯\\\_(ツ)\_/¯

**Comment by kzaher** [comment]
@1cookspe does 2.0.1 work for you now?

**Comment by 1cookspe** [comment]
How do I access version 2.0.1? When I run `pod update` terminal downloads version 1.0.4 of RxDataSources.

**Comment by 1cookspe** [comment]
Updating the pod worked! Thanks so much for your help everyone!
