### ISSUE TITLE
RxPickerViewDataSourceType not declared

### ISSUE THREAD

**Issue by ivanbruel** [RxSwiftCommunity/RxDataSources#157]
Hey there, seems like `RxPickerViewDataSourceType` got lost along the way.

<img width="325" alt="screen shot 2017-08-16 at 12 02 07" src="https://user-images.githubusercontent.com/4968178/29360451-d980f498-827a-11e7-92c5-7186a6c90e34.png">

This issue seems to be happening on version 2.0 and 2.0.1.

**Comment by freak4pc** [comment]
Woah this is weird. How did it even pass CI? 🤔

**Comment by kzaher** [comment]
It looks like dependency isn't set up correctly
2.0.0 requires 3.6.1 :(

**Comment by freak4pc** [comment]
So this probably needs to change to change - https://github.com/RxSwiftCommunity/RxDataSources/blob/master/RxDataSources.podspec#L40

**Comment by kzaher** [comment]
I've made a new release that should solve this issue https://github.com/RxSwiftCommunity/RxDataSources/releases/tag/2.0.2 . Please let me know if it doesn't.
