### ISSUE TITLE
FetchedResultsController and UICollectionView

### ISSUE THREAD

**Issue by sidmani** [RxSwiftCommunity/RxDataSources#158]
Hi, I need a bit of help binding an NSFetchedResultsController to a UICollectionView with Rx. All of the examples have immutable structs as their data models, but the FetchedResultsController returns mutable managed objects. It also does caching/batching so I never have the entire array of objects in memory at one time- is this required by RxSwift? How would I pass the insert/update/delete events from the FetchedResultsController to the UICollectionView? Am I overcomplicating things by trying to use Rx here?  
(Also, is RxDataSources a part of RxSwift or am I asking in the wrong place?)

**Comment by sergdort** [comment]
Hi, @sidmani take a look on [this](https://github.com/RxSwiftCommunity/RxCoreData/blob/master/Sources/FetchedResultsControllerControllerEntityObserver.swift#L14)

If you wanna get partial update I believe it's possible to have something like 

```swift
enum Change<T> {
case insert(IndexPath, T)
case delete(IndexPath, T)
case move(IndexPath, T)
case update(IndexPath, T)
}
```

And Implement your own `RxTableViewDataSourceType` adapter which gonna handle this, or subclass from existing type.

If you need `batching` I don't think Rx would help here as `NSFetchedResultsController `'s prefetch relies on `func object(at: IndexPath)` to make prefetch of the next batch. So you would need to implement your own adapter

**Comment by sergdort** [comment]
If you have any further questions I would recommend you to contact someone here http://rxswift-slack.herokuapp.com

I'm closing this one as it's not an issue with this library
