### ISSUE TITLE
'AnimationConfiguration' cannot be constructed because it has no accessible initializers.

### ISSUE THREAD

**Issue by damienrambout** [RxSwiftCommunity/RxDataSources#16]
I would like to customize insert / delete animations when using a `RxTableViewSectionedAnimatedDataSource`. But it looks like `AnimationConfiguration` properties and initializers are marked `internal`, even though the struct itself is `public`.

Consider marking all fields and initializers `public` in this struct.

Cheers.

**Comment by sergdort** [comment]
Hi, @damienrambout  there is `public var rowAnimation: UITableViewRowAnimation`

**Comment by esttorhe** [comment]
@damienrambout what error are you getting?
I implemented `AnimationConfiguration` and we are currently using it on `Brewbot` without issues.

When you try to call the initializer what error are you getting?

**Comment by garsdle** [comment]
Making the init public fixes it.
`public init(insertAnimation: UITableViewRowAnimation = .Automatic,
    reloadAnimation: UITableViewRowAnimation = .Automatic,
    deleteAnimation: UITableViewRowAnimation = .Automatic) {
      self.insertAnimation = insertAnimation
      self.reloadAnimation = reloadAnimation
      self.deleteAnimation = deleteAnimation
  }
`

**Comment by esttorhe** [comment]
Huh 😕 that's weird. I'll fix it as soon as I'm back on the computer 🙃

**Comment by damienrambout** [comment]
As pointed out by @garsdle, the initializer should be public for the struct to be initialized outside of the `RxDataSources` framework.
I'm using `RxDataSources` through Cocoapods, just so you know.

**Comment by damienrambout** [comment]
It's ok now :)
