### ISSUE TITLE
With UICollectionView 

### ISSUE THREAD

**Issue by anwent** [RxSwiftCommunity/RxDataSources#162]
```
let layout = UICollectionViewFlowLayout()
        layout.minimumLineSpacing = -15
```
set minimumLineSpacing = -15 but no effect, what should be done, i want cell overlap, likes:

![](https://i.stack.imgur.com/MUvad.png)

**Comment by freak4pc** [comment]
I don't see how this is related to RxDataSources. This is UIKit / UICollectionView related...

**Comment by anwent** [comment]
if i'm not uesd RxDataSources, Settings are valid, so i dont know...

**Comment by freak4pc** [comment]
Hey @anwent 
What you mean is that, if you have the exact same Collection View Layout and the data source is a regular delegate, this works?

**Comment by anwent** [comment]
yes, i have another Demo, the same code @freak4pc

**Comment by freak4pc** [comment]
Sounds like a bug :) Any chance you can provide reproducible examples for both ?

**Comment by anwent** [comment]
![47e8bc39-54d3-4169-850b-ed1d51134c56](https://user-images.githubusercontent.com/15354932/30154364-5233cfb8-937f-11e7-8bb8-0c3dd8d8d850.png)
![7682e384-e4fe-4d1e-91bb-e9791eced5b1](https://user-images.githubusercontent.com/15354932/30154378-593ae4fe-937f-11e7-98a8-472cd122c078.png)
Whether I am missing settings @freak4pc

**Comment by freak4pc** [comment]
@anwent If you can attach both projects I'd love to take a look a bit later.
It's a bit hard based to go off based on screenshots unfortunately :)

**Comment by anwent** [comment]
@freak4pc  hey, 
[](https://github.com/anwent/Collection.git )
[](https://github.com/anwent/RxCollection.git)
I'm already pull,  thanks ：）

**Comment by freak4pc** [comment]
Not sure I understand. Did you resolve your issue?

**Comment by anwent** [comment]
https://github.com/anwent/RxCollection
another：
https://github.com/anwent/Collection
@freak4pc

**Comment by Econa77** [comment]
@anwent This code has made four sections, not rows.
https://github.com/anwent/RxCollection/blob/master/RxCollection/ViewController.swift#L35

This is correct
```
let items = Variable<[Travelers]>([
        Travelers(travelers: [Traveler(name: "Bob", avater: UIImage(named: "pic1")),
                              Traveler(name: "Tom", avater: UIImage(named: "pic2")),
                              Traveler(name: "Jim", avater: UIImage(named: "pic3")),
                              Traveler(name: "Sum", avater: UIImage(named: "pic4"))]
        )
])
```

**Comment by anwent** [comment]
@freak4pc @Econa77   thanks 👍  , it's OK
