### ISSUE TITLE
Differentiator compiler error

### ISSUE THREAD

**Issue by dstipko** [RxSwiftCommunity/RxDataSources#163]
I have updated pods to version 2.0.2 and I'm getting compiler error in Diff.swift saying 

> Generic type 'OptimizedIdentity' cannot be nested in type 'Diff'.

**Comment by kzaher** [comment]
Xcode version?

**Comment by jkmckay** [comment]
Same here, I'm using 8.1

**Comment by kzaher** [comment]
Newer versions require Xcode 9, sorry.
