### ISSUE TITLE
I got a lot of deprecated warnings when build with swift4.0

### ISSUE THREAD

**Issue by lieonCX** [RxSwiftCommunity/RxDataSources#165]
The warnings come from following files:
RxCollectionViewSectionedAnimatedDataSource.swift:57:9: warning: 'UIBindingObserver' is deprecated: renamed to 'Binder'
        UIBindingObserver(UIElement: self) { dataSource, newSections in

RxTableViewSectionedAnimatedDataSource.swift:30:9: warning: 'UIBindingObserver' is deprecated: renamed to 'Binder'
        UIBindingObserver(UIElement: self) { dataSource, newSections in

**Comment by kzaher** [comment]
Hi @lieonCX ,

yeah, we need to fix them.

**Comment by kzaher** [comment]
This should be fixed.
