### ISSUE TITLE
Can't launch Simulator from Xcode 9

### ISSUE THREAD

**Issue by Maxismo** [RxSwiftCommunity/RxDataSources#166]
got this error message:
dyld: Library not loaded: @rpath/Differentiator.framework/Differentiator

after i updated Xcode, i do carthage update. and this thing shows up:
*** Building scheme "Differentiator" in RxDataSources.xcworkspace

but i can't find this framework in the build folder for carthage, any suggestions?

**Comment by kzaher** [comment]
Have no idea, it should be there.

**Comment by Maxismo** [comment]
oh, i forgot to mention that i add the --platform ios parameter to carthage update. 
would it be the reason? cause there is one library only provide ios version

**Comment by kzaher** [comment]
Hm ...., have no idea, anybody else experiencing this?

**Comment by GarenChen** [comment]
+1

**Comment by kzaher** [comment]
Hm,

I'm using carthage 0.26.2 and `carthage build --no-skip-current --platform` ios works for me.
What carthage version do you have?
