### ISSUE TITLE
Type 'inout UITableView' does not conform to protocol 'ReactiveCompatible'

### ISSUE THREAD

**Issue by GTMYang** [RxSwiftCommunity/RxDataSources#167]
tableView.rx.items(dataSource: dataSource)

error: Type 'inout UITableView' does not conform to protocol 'ReactiveCompatible'

in XCode 9

**Comment by kdawgwilk** [comment]
Alos hitting this in Xcode 9 using Swift 3.2 compiler version

**Comment by pbartnikSwift** [comment]
I have the same issue

**Comment by sergdort** [comment]
I'm pretty sure you have a type mismatch. Try to annotate types. Swift compiler error descriptions are pretty shitty

**Comment by pbartnikSwift** [comment]
I have changed Observable.just(SectionArray) to SectionArray.asObservable(), where SectionArray is a Variable<[SectionModelType]> and it solve problem for me

**Comment by ntkhoi** [comment]
I have the same issue with tableView.rx.items(cellIdentifier: String, cellType: Cell.Type) 
Xcode9
Swift4

**Comment by lordzsolt** [comment]
Same issue. Would really appreciate a more detailed tutorial than looking at the example app.

I copied the whole NumberSections file over, added the following 2 lines to the code:
```
       let cvAnimatedDataSource = RxCollectionViewSectionedAnimatedDataSource<NumberSection>()
       let whatever = collectionView.rx.items(dataSource: cvAnimatedDataSource)
```

but I still get this error in the whatever line.

**Comment by bidadh** [comment]
I had same issue with the following code:

```swift
        let data = Observable<String>.of("a", "b")
        data.bind(to: self.tableView.rx.items(cellIdentifier: "Cell", cellType: UITableViewCell.self)) {
                    (row: Int, element: String, cell: UITableViewCell) in
                    cell.textLabel?.text = element
                }
                .disposed(by: rx.disposeBag)
```

changing data to be Observable<[String]> fixes the issue.

```swift
        let data = Observable<[String]>.just(["a", "b"])
        data.bind(to: self.tableView.rx.items(cellIdentifier: "Cell", cellType: UITableViewCell.self)) {
                    (row: Int, element: String, cell: UITableViewCell) in
                    cell.textLabel?.text = element
                }
                .disposed(by: rx.disposeBag)

````

**Comment by heisenberg7594** [comment]
Its very hard to find fixes for Rx stuff 😓

**Comment by MikeGlotov** [comment]
It would be easier to help if you could show more code. I had almost the same problem with UICollectionView. I tend to think that the problem usually caused by the fact that something you want to bind to a table or collection view is not initialized in a proper way.

**Comment by heisenberg7594** [comment]
I am having the same problem which @bidadh has

**Comment by lordzsolt** [comment]
After some struggle, I managed to make it work on my end.
I'll make a short tutorial later today.

**Comment by SimonYHB** [comment]
I have the same problem first, and finally I fix it.
You should insure that your dataSource's type has some with your items, for example:

var dataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, MyModel>>()
var items = Observable.just([SectionModel(model: "First section", items: [MyModel(), MyModel(), MyModel(), MyModel()])])
item.bind(to: tableView.rx.items(dataSource: dataSource)).disposed(by: disposeBag)

now, it work.
It's error when I give the wrong type of section to define dataSource, such as 
RxTableViewSectionedReloadDataSource<SectionModel<String, Double>>() 
and then I input  the type of SectionModel<String, MyModel> to items.

**Comment by heisenberg7594** [comment]
![screen shot 2017-11-07 at 11 28 33 am](https://user-images.githubusercontent.com/31646541/32479254-e97b58a0-c3ae-11e7-9038-0d43d4076389.png)
This is my issue. @SimonYHB can you tell me solution for this please.

**Comment by kzaher** [comment]
Basic examples how to use this library are contained inside this repo in example app.

**Comment by numerics** [comment]
Would like to see a lot more Examples... The examples are NOT enough to cover these typical 'ViewModel' situations.

**Comment by Tonku** [comment]
RXSwift is a huge waste of time

**Comment by heisenberg7594** [comment]
Indeed

**Comment by bidadh** [comment]
@heisenberg7594 sorry for late reply.
have you already fixed your issue? the issue you mentioned and added a screenshot is different.

for this one you need to provide your configureCell as constructor argument 

let me know if you need more

**Comment by Tonku** [comment]
@bidadh 
I had this project working fine 6 months back swift 3
https://github.com/Tonku/Airport
A couple of days back I have opened it and is ported to swift 4.
The app stopped working , thats why I said that RXSwift is a fancy stuff for clever guys
and "Cleverness is evil" . Who is going to maintain self decaying frameworks like this

**Comment by bidadh** [comment]
@Tonku 
I had projects running on Swift 3.2 and RxSwift 3.x and I've recently migrated to Swift 4 and RxSwift 4 and they work as they supposed to. it just took a couple of hours to migrate both.

Maintenance is a common thing with all 3rd party libraries not just the Rx stuff.

**Comment by Tonku** [comment]
@bidadh 
Migration is easy, but what is the use if the library is not behaving ? and imagine if you are in a tight schedule , I think this RX fancy stuffs are good for a hobbyist not for serious project.
The project I made simply not working without any reason in swift 4.

**Comment by bidadh** [comment]
@Tonku 
As I said, my projects are working as expected without issues and migration was not that hard. it was just a couple of changes that I made and all good then.

not agree with having Rx for hobbyist projects. I've got serious ones running on Rx and to be honest I love it!

**Comment by Tonku** [comment]
@bidadh 
If you have time just have a look at https://github.com/Tonku/Airport 
and you will realise what I am saying. I could develop same thing in plain swift and will be maintainable even after 10 years

**Comment by sergdort** [comment]
Hi, guys the discussion here escalated pretty quickly... 
I just want to point out that maintainers **do not owe** anything to anybody. They work for free on their spare time on pure enthusiasm. And conversations like this won't bring us anywhere.

**Comment by freak4pc** [comment]
@GTMYang @heisenberg7594 What you're missing is `configureCell` was moved *into the initializer of the datasource* instead of where it used to be. 

So know you would need to do something like 

```swift
RxTableViewSectionedReloadDataSource<SectionModelType>(configureCell: { dataSource, tableView, indexPath, item in 

})
```

Please see the full method signature here: 
https://github.com/RxSwiftCommunity/RxDataSources/blob/ae7d354dc25cc4e517cb72e00a068669aac97cfd/Sources/RxDataSources/TableViewSectionedDataSource.swift#L38

This seems to currently not be correctly reflected in the documentation, I'll see if I can get around fo fit it.

**Comment by sunshinfight** [comment]
The type of 'item' must be observable<[Any]>,so that you can bind it ot tableView.rx.items.

**Comment by andreaferrando** [comment]
I had the same issue, in my case the problem was an error inside the data source.
```
viewModel.myObjects.asObservable().bind(to: self.tableView.rx.items(cellIdentifier: "myCellId", cellType: myCellId.self)) { (row, myObject, cell) in
    cell.setup(....)
}
```
I was making a mistake passing an integer instead of a string in one of the parameters in cell.setup and, instead of getting an error there, xcode error was: Type 'inout UITableView' does not conform to protocol 'ReactiveCompatible'  on this line:
`viewModel.myObjects.asObservable().bind(to: self.tableView.rx.items`

Hope this can be usefull

**Comment by bharath31** [comment]
Adding RxCocoa should solve this issue
