### ISSUE TITLE
AnimatableSectionModel.swift has a warning (0.5.0)

### ISSUE THREAD

**Issue by frogcjn** [RxSwiftCommunity/RxDataSources#17]
is:issue is:open .../Pods/RxDataSources/Sources/DataSources/AnimatableSectionModel.swift:96:61: 'HashableSectionModel' is deprecated: Please use AnimatableSectionModel or your own model implementing `AnimatableSectionModelType`

**Comment by kzaher** [comment]
This should we fixed now. I've released a new version.
