### ISSUE TITLE
Podfile issue

### ISSUE THREAD

**Issue by pluckq** [RxSwiftCommunity/RxDataSources#170]
Hello
I'm using xcode 9, today on pod update got this error:
`[!] Unable to satisfy the following requirements:

- `Differentiator (~> 3.0.0-beta.0)` required by `RxDataSources (3.0.0-beta.0)`

None of your spec sources contain a spec satisfying the dependency: `Differentiator (~> 3.0.0-beta.0)`.
`

**Comment by kzaher** [comment]
I've just published 3.0.0-beta.0, how about now?

**Comment by pluckq** [comment]
Thank you, now it's working
