### ISSUE TITLE
I want to stop insert animation  Example3_TableViewEditing

### ISSUE THREAD

**Issue by shingo-nakanishi** [RxSwiftCommunity/RxDataSources#173]
https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example3_TableViewEditing.swift#L64

I change `AnimationConfiguration` to

```
dataSource.animationConfiguration = AnimationConfiguration(insertAnimation: .none,
                                                           reloadAnimation: .none,
                                                           deleteAnimation: .none)
```

but, still animation like `.top`. **How to stop animation?**

![example3_rec_trim](https://user-images.githubusercontent.com/2630601/30840555-f0d9f86c-a2b2-11e7-9631-571a023e9425.gif)

**Comment by shingo-nakanishi** [comment]
https://developer.apple.com/documentation/uikit/uitableviewrowanimation

> case none
The inserted or deleted rows use the default animations.

**Comment by shingo-nakanishi** [comment]
I need stop animation like this

https://stackoverflow.com/a/9310886/1979953

> [UIView setAnimationsEnabled:NO];
[tableView beginUpdates];
[tableView endUpdates];
[UIView setAnimationsEnabled:YES];

**Comment by kzaher** [comment]
Hi,

We are passing the correct parameters to Apple API as far as I can tell. Apple's API has a bug as far as I can tell.

**Comment by kzaher** [comment]
You can always use reload data source instead of animated data source. Examples are inside example app inside this repo.
