### ISSUE TITLE
Missing initializer of RxTableViewSectionedReloadDataSource in Swift 4 branch

### ISSUE THREAD

**Issue by ludvigeriksson** [RxSwiftCommunity/RxDataSources#175]
When using the initializer of `RxTableViewSectionedReloadDataSource` I get an error saying `Missing argument for parameter 'configureCell' in call`. It seems that the initializer seen [here](https://github.com/RxSwiftCommunity/RxDataSources/blob/05c3757c77cff62a09d3aebd745e86ed3483d26e/Sources/RxDataSources/RxTableViewSectionedReloadDataSource.swift#L23) isn't present in the Swift 4 branch.

**Comment by kzaher** [comment]
Hi,

I would argue it is.

https://github.com/RxSwiftCommunity/RxDataSources/blob/swift4.0/Sources/RxDataSources/RxTableViewSectionedReloadDataSource.swift

https://github.com/RxSwiftCommunity/RxDataSources/blob/swift4.0/Sources/RxDataSources/TableViewSectionedDataSource.swift#L37

**Comment by juanuribeo13** [comment]
Hi @kzaher, I have the same problem, I have all my data sources declared like this `let dataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, Int>>()` but that init without arguments is no longer present in the 3.0.0-rc.0 release, it was in the betas though and there was no deprecated warning, is that init being removed in v3 or it was just missing in the latest release? I want to know if I should migrate all my code to use the `init(configureCell:_)`

**Comment by kzaher** [comment]
@juanuribeo13 We will use initializer version in future. It seems more Swifty for me.

**Comment by igorkulman** [comment]
The initializer version has one problem, you cannot use `[weak self]` or `[unowned self]` in it (getting an error when trying). 

So if I need to assign to the cell something from the VC, like making the VC a delegate for the cell or getting something from the VC's view model and assign it to the class I cannot. 

Please make it possible to also use the old way, otherwise, I cannot upgrade without re-architecting all my table views.

**Comment by kzaher** [comment]
Hi,

setters still work. Just initialize it with a dummy lambda that fatal errors and set a valid factory where ever you used to set it. 

If you are using `self` inside that factory, that is a code smell to me, but nothing we've done prevents you from keeping your old way.

**Comment by igorkulman** [comment]
Thanks. Regarding the code smell, my cell has a delegate to initiate actions it cannot perform by itself so I need `self` to assign anything to this delegate.

**Comment by kzaher** [comment]
I don't think you need vc to do that, but you can for sure.

**Comment by rbresjer** [comment]
@kzaher Previously I kept the datasource in my view model, but set up the `configureCell` method in my view controller. That way I kept UI-logic out of my view model. With the `configureCell` being set in the `init` method, what would be the best way to do this? Keep the datasource in the view controller? Of set a dummy lambda in the view model and update it with the real implementation from the view controller?

**Comment by kzaher** [comment]
Data source shouldn't be stored in view model. It's just a transformer of data to UI elements.

I don't use ViewModels, but if you are, I guess it's somewhere between UIViewController and ViewModel.

If you still want to store it in view model, then you can set a dummy lambda, that's how it worked before, but I would say that's a bit of code smell.
