### ISSUE TITLE
Animated data source: Type 'inout UICollectionView' does not conform to protocol 'ReactiveCompatible'

### ISSUE THREAD

**Issue by goa** [RxSwiftCommunity/RxDataSources#176]
**Swift 4** - **Xcode 9**

Using **RxSwift 3.6.1** 
and **RxDataSources 2.0.2**

Here is my code:

```
let dataSource = RxCollectionViewSectionedAnimatedDataSource<AnimatableSectionModel<String, Int>>()

dataSource.configureCell = { (ds, cv, ip, i) -> UICollectionViewCell in
	let cell = cv.dequeueReusableCell(withReuseIdentifier: "Cell", for: ip)
	// Cell is populated here
	return cell
}

// ****** Below is where I get the error
let test = collectionView.rx.items(dataSource: dataSource)
```

Thanks for the great work :)

**Comment by goa** [comment]
Got the same exact error using **RxSwift 4.0.0-rc.0** 
and RxDataSources **3.0.0-rc.0**

Updated code:

```
let dataSource = RxCollectionViewSectionedAnimatedDataSource<AnimatableSectionModel<String, Int>> 
(configureCell: { (ds, cv, ip, i) -> UICollectionViewCell in
	let cell = cv.dequeueReusableCell(withReuseIdentifier: "Cell", for: ip)
	// Cell is populated here
	return cell
},
configureSupplementaryView: { (_, _, _, _) -> UICollectionReusableView in
        // I do not require reusable views
        return UICollectionReusableView()
})

// ****** Below is where I get the error
let test = collectionView.rx.items(dataSource: dataSource)
```

**Comment by kzaher** [comment]
Hi @goa ,

you are using it wrong, please take a look at example app how to use it.

**Comment by kzaher** [comment]
Examples how to use this API are contained in example app inside this repo and inline docs for `rx.items`.

**Comment by goa** [comment]
Thanks very much for your help. The API is a little confusing but I made it
work finally.

**Comment by sergdort** [comment]
I guess we can close it :)

**Comment by RaduGrama** [comment]
@kzaher, I am getting the same error and the example for UICollectionView is non-trivial. The documentation states:

> Bind the data to the tableView/collectionView using one of:
rx.items(dataSource:protocol<RxTableViewDataSourceType, UITableViewDataSource>)
rx.items(cellIdentifier:String)
rx.items(cellIdentifier:String:Cell.Type:_:)
rx.items(_:_:)

but trying to run the rx.items(cellIdentifier:String) example for UICollectionView fails with the error in the thread title and it is not clear if it is even supposed to work.

I guess slightly clearer examples for both table views and collection views could help a lot.
