### ISSUE TITLE
How to execute a plain reloadData instead of a very large batch update?

### ISSUE THREAD

**Issue by mthole** [RxSwiftCommunity/RxDataSources#180]
I have an animated RxDataSource bound UITableView with many hundreds of rows. Depending on the particulars of a batch update, the default UITableView animations can look kind of janky a feel slow. I'd like to be able to configure some threshold at which the animated data source will do a simple reloadData, rather than try to animate a large batch of updates.

The README file on this project states:

> it is preferred (and possible) to cap the number of changes to some small number, and in case the number of changes grows towards linear, just do normal reload

...which sounds exactly like what I want! :)

Poking around in the code, I couldn't find anything that looks like this. Can you point me in the right direction?

**Comment by devxoul** [comment]
Which data source class are you using?

**Comment by kzaher** [comment]
Hi @mthole ,

Oh, sorry. Forgot to add that feature.

We just need to add additional argument 

`fallbackToReload: ([Changeset<S>]) -> Bool = { _ in false }`
 to `Rx{Table,Collection}ViewAnimatedDataSource` initializer and hook it 
https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/RxDataSources/RxTableViewSectionedAnimatedDataSource.swift#L92

```
self.setSections(newSections)
tableView.reloadData()
```

**Comment by kzaher** [comment]
I've made a new release that should fix this. 37a6413

**Comment by mthole** [comment]
Thanks for the quick update and release. You're awesome! 💯
