### ISSUE TITLE
support custom section headerView

### ISSUE THREAD

**Issue by julesli** [RxSwiftCommunity/RxDataSources#182]
we have to use traditional UITableViewDelegate method  to custom  section headerView, we prefer to use like the way of dataSource.configcell closure

**Comment by mzgnr** [comment]
`class LiveScoreHeader: UITableViewHeaderFooterView {
    ...
}`

and use func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? delegate method.

**Comment by julesli** [comment]
we prefer to use like the way of dataSource.configcell closure
  
self.dataSource.configureSectionHeaderFooter =  { dataSource, tableView, indexPath, item in
            let header =  MyCustomHeader()
            header.title =  item.title
            return header
        }

**Comment by adrianodiasx93** [comment]
+1

**Comment by stebaps** [comment]
+1 😀

**Comment by pixeldock** [comment]
+1

**Comment by qiushuitian** [comment]
+1

**Comment by sergdort** [comment]
Hi guys, I feel like this is duplicate of #203

**Comment by qiushuitian** [comment]
what about UICollectionView?

**Comment by sergdort** [comment]
There is `configureSupplementaryView` closure [here](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/RxDataSources/CollectionViewSectionedDataSource.swift#L138)
