### ISSUE TITLE
Differentiator framework missing with Carthage

### ISSUE THREAD

**Issue by Antoine4011** [RxSwiftCommunity/RxDataSources#184]
I'm using RxDataSources through Carthage but when I try to update RxDataSources (from 1.0.4 to 3.0.1) I have a crash when launching the application with this message: 

```
dyld: Library not loaded: @rpath/Differentiator.framework/Differentiator
  Referenced from: /var/containers/Bundle/Application/[...]
  Reason: image not found
```

**Comment by Antoine4011** [comment]
It turns out Carthage also build the `Differentiator.framework` as well. But I feel like this is something that should be written somewhere since we expect to only use `RxDataSources.framework`, and maybe you should prefix the the framework by `Rx` so we don't forget to link it and see right away for what it's used... :)

**Comment by frederic-adda** [comment]
@Antoine4011 Finally, Antoine, how did you solve that issue? I'm new to Carthage, and I can't find where I should add or remove things to make it work once again ...
Thanks !

**Comment by robcecil** [comment]
Just ran into this.

**Comment by MortyMerr** [comment]
Not very good solution (

**Comment by Vkt0r** [comment]
According to the Carthage library: 

>If the framework you want to add to your project has dependencies explicitly listed in a Cartfile, Carthage will automatically retrieve them for you. You will then have to drag them yourself into your project from the Carthage/Build folder.

>If the embedded framework in your project has dependencies to other frameworks you must link them to application target (even if application target does not have a dependency on that frameworks and never uses them).

So as `RxDataSources.framework` depends on `Differentiator.framework` after you run `carthage` you need to drag them yourself into your project from the **Carthage/Build folder** to be able to run the library correctly. 

I think we can avoid this kind of issue/doubt updating the `README` with a more detailed explanation of how to integrate the library at the beginning 😅.

**Comment by SoyaTakahashi** [comment]
I was saved by this issue : )
