### ISSUE TITLE
How to change datasource and rebind to tableview

### ISSUE THREAD

**Issue by bupojung** [RxSwiftCommunity/RxDataSources#185]
I change the datasource and rebinding to tableview. cause this assert error

> assertion failed: This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working.
If you are ok with this, try to set delegate (data source) to `nil` in front of this operation.
 This is the source object value: <UITableView: 0x7ffed3022e00; frame = (0 64; 414 672); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000000588a0>; layer = <CALayer: 0x6000000252e0>; contentOffset: {0, 0}; contentSize: {414, 695.33335113525391}; adjustedContentInset: {0, 0, 0, 0}>
 This this the original delegate (data source) value: <_TtGC13RxDataSources38RxTableViewSectionedAnimatedDataSourceGV14Differentiator22AnimatableSectionModelSSC5XMail19ServerMailCellModel__: 0x6000001439c0>
Hint: Maybe delegate was already set in xib or storyboard and now it's being overwritten in code.
: file /Users/yizhongzhuang/Desktop/github/xmail/XMail/Pods/RxCocoa/RxCocoa/Common/DelegateProxyType.swift, line 195
2017-10-26 00:29:23.653905+0800 XMail[50561:10655473] assertion failed: This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working.
If you are ok with this, try to set delegate (data source) to `nil` in front of this operation.
 This is the source object value: <UITableView: 0x7ffed3022e00; frame = (0 64; 414 672); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000000588a0>; layer = <CALayer: 0x6000000252e0>; contentOffset: {0, 0}; contentSize: {414, 695.33335113525391}; adjustedContentInset: {0, 0, 0, 0}>
 This this the original delegate (data source) value: <_TtGC13RxDataSources38RxTableViewSectionedAnimatedDataSourceGV14Differentiator22AnimatableSectionModelSSC5XMail19ServerMailCellModel__: 0x6000001439c0>
Hint: Maybe delegate was already set in xib or storyboard and now it's being overwritten in code.
: file /Users/yizhongzhuang/Desktop/github/xmail/XMail/Pods/RxCocoa/RxCocoa/Common/DelegateProxyType.swift, line 195

This is my code, I call the bindings function when user change account and relogin
```swift
  func bindings() {
        dataSource = RxTableViewSectionedAnimatedDataSource<AnimatableSectionModel<String, ServerMailCellModel>>()

        dataSource.configureCell = { (_, tv, indexPath, element) in
            if let cell = tv.dequeueReusableCell(withIdentifier: "ServerMailCell") as? ServerMailCell {
                cell.model = element
                return cell
            }
            
            return UITableViewCell.init()
        }
        
        dataSource.canEditRowAtIndexPath = { (ds, ip) in
            return true
        }
        viewModel
            .mailList
            .asObservable()
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: bag)
        
        tableView.rx.modelSelected(ServerMailCellModel.self)
            .subscribe(onNext: { (mailModel) in
                guard let mail = StoreManager.shared.mail(with: mailModel.mailID) else {
                    return
                }
                let detailController = RCMailDetailController()
                detailController.mailModel = mail
                detailController.folderPath = self.viewModel.mailboxType.path()
                DispatchQueue.main.async {
                    self.navigationController?.pushViewController(detailController, animated: true)
                }
            })
            .disposed(by: bag)
        
        tableView.rx
            .itemSelected
            .subscribe(onNext:  { [weak self] indexPath in
                self?.viewModel.selected(at: indexPath)
                self?.tableView.deselectRow(at: indexPath, animated: true)
            })
            .disposed(by: bag)
        
        viewModel.isBlank
            .drive(blankView!.rx.isHidden)
            .disposed(by: bag)
        
        viewModel.title
            .drive(self.rx.title)
            .disposed(by: bag)
        
        tableView.rx.itemDeleted.subscribe(onNext:{[weak self]
            indexpath in
            self?.viewModel.delete(at: indexpath)
        }).disposed(by: bag)
}
```

**Comment by rbresjer** [comment]
The solution is already in the error message you posted:

> This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working. If you are ok with this, try to set delegate (data source) to nil in front of this operation.

In other words, set the `delegate` and/or `datasource` to `nil` before binding to it again.

**Comment by pamierdt** [comment]
I have re-binding tableViewDataSources  and it working , but when the ViewConroller is dealloced 
crashed
<img width="1781" alt="qq20171110-162551 2x" src="https://user-images.githubusercontent.com/15703954/32649135-e5d23836-c633-11e7-8193-745e3d13e79c.png">

**Comment by dimohamdy** [comment]
@bupojung i face the same problem how you solve it ?

**Comment by dimohamdy** [comment]
i solve it by add this 
```
 self.tableView.delegate = nil
 self.tableView.dataSource = nil
```

**Comment by bupojung** [comment]
solve it by add this as @dimohamdy do

>  
self.tableView.delegate = nil
 self.tableView.dataSource = nil

**Comment by honbolau** [comment]
@pamierdt  i face the same problem how you solve it ?

**Comment by dimohamdy** [comment]
@honbolau  check this comment https://github.com/RxSwiftCommunity/RxDataSources/issues/185#issuecomment-386594517

**Comment by imChay** [comment]
I have this problem too，Is there a good solution？

**Comment by dimohamdy** [comment]
@imChay check this comment https://github.com/RxSwiftCommunity/RxDataSources/issues/185#issuecomment-386594517

**Comment by ngoclk-nexle** [comment]
> I have re-binding tableViewDataSources and it working , but when the ViewConroller is dealloced
> crashed
> <img alt="qq20171110-162551 2x" width="1781" src="https://user-images.githubusercontent.com/15703954/32649135-e5d23836-c633-11e7-8193-745e3d13e79c.png">

I have the same problem after set nil to delegate and dataSource. Can anyone help?

**Comment by knight2010** [comment]
/// Keep this or will crash
            picker.delegate = nil
            picker.dataSource = nil
            
            Observable.just(contentArr)
                        .bind(to: picker.rx.items(adapter: stringPickerAdapter))
                .disposed(by: rx.disposeBag)

**Comment by ifwrite** [comment]
please var disposeBag = DisposeBag(), and before binding  renew disposeBag = DisposeBag()

**Comment by arwenGhafoor** [comment]
I have solved by adding 
    public override func prepareForReuse() {
        super.prepareForReuse()
        disposeBag = DisposeBag()
    }
