### ISSUE TITLE
Add configureSupplementaryView default implementation for CollectionViewSectionedDataSource

### ISSUE THREAD

**Issue by juanuribeo13** [RxSwiftCommunity/RxDataSources#186]
Hello, I have collection views that have no supplementary views but the `configureSupplementaryView` argument is required in the `CollectionViewSectionedDataSource` initializer, I was thinking that there should be a default implementation like there is for `moveItem` and `canMoveItemAtIndexPath`.

**Comment by kzaher** [comment]
We've made it optional for reload data source. Unfortunately we can't for animated data source because it crashes.

**Comment by FouadAstitou** [comment]
Hello, i can't find an example on how to use configureSupplementaryView using RXDatasources.
Is there somewhere i can find an example?

**Comment by mkko** [comment]
There's one defined here:

https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example2_RandomizedSectionsAnimation.swift#L121-L125

**Comment by FouadAstitou** [comment]
Thanks, in the mean time i had found that one and it helped me to make it work in my project. I appreciate the quick response. Have a great day.

Verstuurd vanaf mijn iPhone
