### ISSUE TITLE
is it an error?

### ISSUE THREAD

**Issue by coder-weed-Xu** [RxSwiftCommunity/RxDataSources#191]
![fd5b8ff3-cc87-453f-8c9b-943b0bcb4b89](https://user-images.githubusercontent.com/31840482/33006342-f519873a-ce04-11e7-9694-3073e5daef4e.png)

look at this  error,it is  not the same with your demo

**Comment by mosamer** [comment]
AFAIK, `configureCell` closure is a required parameter for `init` method starting from v3.0
