### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by victoraugustolls** [RxSwiftCommunity/RxDataSources#193]
Is there a "right way" to implement pagination when using RxDataSources? Thanks!!

**Comment by bobgodwinx** [comment]
Take a look into `contentOffset` in [UIScrollView+Rx](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UIScrollView%2BRx.swift) and use it for your pagination. There is also [RxPagination](https://github.com/tryswift/RxPagination)

**Comment by victoraugustolls** [comment]
Thanks @bobgodwinx
