### ISSUE TITLE
Append items to MultipleSectionModel

### ISSUE THREAD

**Issue by alibaqbani** [RxSwiftCommunity/RxDataSources#198]
I follow this [sample](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example4_DifferentSectionAndItemTypes.swift) and successfully created multi-section tableView, but how can I append items to one of this sections when tableView reloaded? I can recreate the section but it's not what I want!

**Comment by freak4pc** [comment]
I'm not entirely sure what you're trying to do but "appending" is an imperative action. What you would usually want to do is make sure your DataSource reflects that latest source of truth, and that way your Table View correctly represents your latest data.

**Comment by zenghaojim33** [comment]
Hi guys I'm also looking for solutions for this problem, is there any workaround besides recreating a new `SectionModelType`?

**Comment by freak4pc** [comment]
@zenghaojim33 Please read the documentation for RxDataSources.

The concept of "adding an item" is wrong and comes from wrongful thinking of reactive concepts. The only thing that's changing would be the array of your sections - when they change, the Table / Collection will automatically reload based on these changes. 

If you're using a `ReloadDataSource,` everything would reload (e.g. `reloadData()` behavior) while using an `AnimatedDataSource` will only batch reload the changed rows, based on the `IdentifiableType` protocol and a diffing algorithm.
