### ISSUE TITLE
Crashes Xcode when using with UITableViewController

### ISSUE THREAD

**Issue by AttilaTheFun** [RxSwiftCommunity/RxDataSources#199]
I tried using your library but was really confused when Xcode (9.2) kept crashing with even the simplest examples. After downloading your example project, I realized all of the examples created and outlet-ed tableviews instead of subclassing UITableViewController. It should at least be documented in the readme that you must not subclass uitableviewcontroller or uicollectionviewcontroller directly.

**Comment by sergdort** [comment]
If you subclass `UITableViewController ` or `UICollectionViewController ` you need to set `dataSource` property to `nil` as it a `UI{Collection/Table}ViewController `

I think there should be an assertion that `dataSource` is already set

**Comment by AttilaTheFun** [comment]
Ah, that worked. Xcode was crashing for me on that assertion though.

**Comment by netspencer** [comment]
There absolutely should be an assertion to make sure you aren't setting dataSource manually.
