### ISSUE TITLE
Any planning on UITableViewDelegates?

### ISSUE THREAD

**Issue by yuriferretti-luizalabs** [RxSwiftCommunity/RxDataSources#2]
I loved this rx datasources implementation. It makes very simple and reusable to implemente uitableview based view controllers. Do you have any plans to implement similar rx abstractions for uitableview/uicollection view delegates ?

**Comment by kzaher** [comment]
Hi @yuriferretti-luizalabs ,

I don't think we need something equivalent for delegates. They are much simpler.

You can just use `rx_setDelegate` to your VC to implement one or two of the needed methods. Usually there isn't anything you need to them for :)

Delegate extensions `RxCocoa` work with these data sources also, so if you use `rx_modelSelected` or `rx_modelDeselected` with these data sources, everything will work as expected.

**Comment by esttorhe** [comment]
I'm doing some cleanup. 
I'm closing this one given kzaher answer. @yuriferretti-luizalabs feel free to open another issue if you feel the need.
