### ISSUE TITLE
A difficult question: how does RxSwift handle the custom Btn click event in cell?

### ISSUE THREAD

**Issue by ETmanwenhan** [RxSwiftCommunity/RxDataSources#200]
A difficult question: how does RxSwift handle the custom Btn click event in cell?

**Comment by freak4pc** [comment]
@ETmanwenhan It's not "Hard" or "Difficult" but there are many solutions. 
One thing you can do is expose an `Observable` or `ControlEvent` from your cell and then bind it to some input on your ViewModel that knows to handle the taps. 

Here is a snippet I'm using in my code base: 

```swift
cell.rx.didTapUpdate
    .bind(to: viewModel.inputs.didTapEditItem)
    .disposed(by: cell.disposeBag)
```

`didTapUpdate` emits either an index, or better yet some identity/model/something that helps your ViewModel (or whatever else handles the tap) understand who's the sender of that event.

**Comment by ETmanwenhan** [comment]
@freak4pc 
So the Cell needs to hold the ViewModel through a weak reference?

**Comment by freak4pc** [comment]
I think you misunderstood. I’m not passing the ViewModel to the cell at all. I’m exposing a tap even FROM the cell externally, and the just binding it TO a ViewModel input

**Comment by freak4pc** [comment]
Anyways since this isn’t a question about the library itself, please join us on our slack channel our ask on StackOverflow.

The issues tab on projects should be solely used for issues with the code itself so we can concentrate on fixing bugs and issues and not support individual use cases :) 

Thanks for understanding.

**Comment by ETmanwenhan** [comment]
Thanks!
