### ISSUE TITLE
Using my own xib or UIView custom class for sections

### ISSUE THREAD

**Issue by serhatsezer** [RxSwiftCommunity/RxDataSources#203]
Hi, 

I know you have built-in support for titleForHeaderInSection but don't have custom sections. Is it on your roadmap list or I can create it and make a PR for it.

Thank you so much.

**Comment by sergdort** [comment]
This is a method of the [`UITableViewDelegate`](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614901-tableview) method :)

Not sure why Apple did this ¯\_(ツ)_/¯

**Comment by serhatsezer** [comment]
@sergdort okay shame on me. 🤭
