### ISSUE TITLE
RxTableViewSectionedAnimatedDataSource exception when Realm items are deleted

### ISSUE THREAD

**Issue by zwolsman** [RxSwiftCommunity/RxDataSources#205]
When an Item is deleted from Realm there will be a reload. The problem occurs in calculating the differences.

`var sectionCommands = try CommandGenerator<S>.generatorForInitialSections(initialSections, finalSections: finalSections)
`

Throws a Realm exception because it's trying to get the `identity` value of a deleted object. Is there a workaround for this or any solution?

**Comment by sergdort** [comment]
Hi, @zwolsman I would suggest you not to use `Realm` entities directly but convert them to let's say swift `struct`.
Or use `Realm` [changes](https://realm.io/docs/swift/latest/#collection-notifications)

**Comment by zwolsman** [comment]
Hi, @sergdort, thanks for your suggestion. The problem there is, the changes are for the realm collection. I'm viewing the collection in sections so the `Realm changes` isn't the solution.

I guess I can map the realm objects to swift structs but it seems a bit of clumsy.

`JSON -> swift struct -> Realm objects -> swift structs -> tableview`
Can't that be more efficient?

**Comment by sergdort** [comment]
Well, you can do this work on different schedules. [Here](https://github.com/sergdort/CleanArchitectureRxSwift/blob/master/RealmPlatform/Repository/Repository.swift#L16) a prototype I came up with when I played with Realm last time

**Comment by natanrolnik** [comment]
A little late to the party, but might be helpful to others.
When implementing your `identity` property, you can check if the Realm object was invalidated. If so, just return a unique value, like this:

```
    var identity: String {
        return isInvalidated ? "deleted-object-\(UUID().uuidString)" : objectId
    }
```
