### ISSUE TITLE
I have some question about the diff algorithm

### ISSUE THREAD

**Issue by Damonvvong** [RxSwiftCommunity/RxDataSources#206]
I found that Paul Hackel's diff algorithm does not find the optimal edit distance between two arrays

So why not use the Wagner Fischer algorithm?

Although in a large number, using Wagner Fischer algorithm is obviously very slow. But usually, a screen can display the number is not much.

So why not use the Wagner Fischer algorithm to find the optimal edit distance, but quickly find the edit distance using Paul Hackel's diff algorithm?

**Comment by Damonvvong** [comment]
https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm

**Comment by kzaher** [comment]
Hi @Damonvvong ,

nobody is using Paul Hackel's diff algorithm as far as I can tell. That algorithm was optimized for text diffs. Libraries are usually using similar algorithms that rely on identity. 

The algorithm which we are using works in linear time which is extremely important for UI algorithms IMHO.

Using any kind of dynamic programing based algorithms, like Wagner–Fischer, which have **worst time quadratic complexity** is simply not feasible in UI layer IMHO.

**Comment by Damonvvong** [comment]
Yeah, I mean is the similar algorithms not the truly  Paul Hackel's diff algorithm.

So,you think **the best edit distance** is not the most important.

Thank you for you answer!

**Comment by kzaher** [comment]
If it can freeze your ui forever or crash your app depending on data, then its simply not an option IMHO.

This isn’t a tradeoff but a requirement.

**Comment by Damonvvong** [comment]
Sorry,what is "crash your app depending on data" ?

if I use DP, is will crash ? 

I am not sure what you meant. 😂
