### ISSUE TITLE
Difference calculate result make some animation strange.

### ISSUE THREAD

**Issue by ufosky** [RxSwiftCommunity/RxDataSources#208]
I found the differences in this code is an array of ChangeSet, when my changes have a inserted item and an updated item, the differences is an array of 2 ChangeSet, one is a ChangeSet for insert an item and the other is for update an item. So the result make 2 `performBatchUpdates` call which lead to strange animation for the changes. For this case in my project when I scroll to the bottom of the tableview, the animation is the last cell disappear then the inserted cell inserting and updated cell updating, finally the last cell appeared.
https://github.com/RxSwiftCommunity/RxDataSources/blob/ddfc9a1fdba650984f3a72b5b318e55fcfeccbae/Sources/RxDataSources/RxTableViewSectionedAnimatedDataSource.swift#L98-L106

**Comment by kzaher** [comment]
@ufosky I think that insert + update item should be inside the same animation, maybe you have some other animations running.

**Comment by ufosky** [comment]
@kzaher The implement code here is make 3 possible `ChangeSet` for different change type:
https://github.com/RxSwiftCommunity/RxDataSources/blob/ddfc9a1fdba650984f3a72b5b318e55fcfeccbae/Sources/Differentiator/Diff.swift#L363-L365

**Comment by ufosky** [comment]
I read `NSFetchedResultsControllerDelegate` documentation from 
https://developer.apple.com/documentation/coredata/nsfetchedresultscontrollerdelegate#overview
>You can use controllerWillChangeContent(_:) and controllerDidChangeContent(_:) to bracket updates to a table view whose content is provided by the fetched results controller as illustrated in the following example:
So I think it should make changes between one `beginUpdates` and `endUpdates` call.

**Comment by kzaher** [comment]
Hi @ufosky ,

unfortunately that doesn't work properly when there are section and cell moves.
