### ISSUE TITLE
Section reloading issue ( RxTableViewSectionedAnimatedDataSource)

### ISSUE THREAD

**Issue by amirpervaiz086** [RxSwiftCommunity/RxDataSources#211]
Hi guys,
  I have implemented sections using RxTableViewSectionedAnimatedDataSource. Inserting and deletion works fine but when I scroll to end of table view, I faced jerk and it seems like all sections are reloaded rather than only changed one. Please have a look at giff file.

 Initially when description cell is pressed, new cell is added in section but when table view scrolls to end its causing issue in animation. 

![Alt Text](https://media3.giphy.com/media/26DNbkCplG6TqDues/giphy.gif)

**Comment by MoreBlood** [comment]
@amirpervaiz086 any news about fixing this issue?

**Comment by amirpervaiz086** [comment]
@MoreBlood I found issue is with the UITableView insertion. Its a known bug filed by people. Temporary fix was to use to set content offset to false                 self.tableView.setContentOffset(self.tableView.contentOffset, animated: false)
I did that in non-RXTableView. hope It helps.

**Comment by cozzin** [comment]
I also have same issue. In my case, it seems that bugs do not occur when fixed estimatedRowHeight and rowHeight. Therefore, it is expected that the content offset will not jump when the cell height is directly calculated.

**Comment by ThomasLeblond** [comment]
Hi @amirpervaiz086, where did you set the content off set ? 

I have the same issue when I try to expand a cell. All is fine when I don't scroll but I have the same issue after scrolling.

**Comment by cozzin** [comment]
@ThomasLeblond  I also had the same issue. I noticed that the height of the tableview is a recalculation problem. The more the estimatedHeight differs from the actual height, the more it scrolls. So I solved it by caching the height value.

```swift
class ViewController: UIViewController {

    private var cellHieghtsDictionary: [String: CGFloat] = [:]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // set table view ...
        tableView.rx.setDelegate(self).disposed(by: disposeBag)
    }

    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        cellHeightsDictionary[indexPath.cacheKey] = cell.frame.size.height
    }

    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return cellHeightsDictionary[indexPath.cacheKey] ?? UITableViewAutomaticDimension
    }
}

private extension IndexPath {
    var cacheKey: String {
        return String(describing: self)
    }
}
```

**Comment by amirpervaiz086** [comment]
@ThomasLeblond in update table closure I did that:
self.viewModel.updateTableView = { [unowned self] (array) in
            DispatchQueue.main.async {
                self.tableView.insertRows(at: array, with: .fade)
                self.tableView.setContentOffset(self.tableView.contentOffset, animated: false)
                self.loaderView.stopAnimating()
            }
        }
Not sure how it can be done in Rx since we bind observable directly to tableView.

**Comment by amirpervaiz086** [comment]
or calculate height rather than using approximate one like above

**Comment by ThomasLeblond** [comment]
@cozzin Thank you a lot ! This trick solved my issue 😍

**Comment by nguyenvanuyn96** [comment]
Thanks, @cozzin a lot. My issue has been solved with your trick. It's great. <3

**Comment by mkkroliks** [comment]
@SungHo-Hong it works! Great!

**Comment by yojkim** [comment]
@cozzin Oh my god..! You save my life.. !!!

Thank you 👍

**Comment by vkcldhkd** [comment]
@cozzin Thank you 👍

If you change the cellHieghtsDictionary to cellHeightsDictionary, it is really perfect.

**Comment by cozzin** [comment]
@vkcldhkd Thank you for your feedback.
