### ISSUE TITLE
"Generic parameter 'Self' could not be inferred"

### ISSUE THREAD

**Issue by zenghailong** [RxSwiftCommunity/RxDataSources#225]
When tableView binding the data source, the error is reported:

    "Generic parameter 'Self' could not be inferred"

 The code is like this:

```swift
Observable.just(models)
   .bind(to: tableView.rx.items(dataSource: dataSource))
   .disposed(by: disposeBag)
```

**Comment by spirit-jsb** [comment]
Yes, I have the same problem, did you found solution?

**Comment by Majkitos** [comment]
I am having the same issues. Did you found any solutions?

**Comment by Vkt0r** [comment]
@zenghailong Can you share your `models` variable please to have more information about the issue?

**Comment by AshleyDeng** [comment]
Found out this problem was because I didn't turn my data into section compatible.

So if you have an array of data you want to display, make sure it has section / header for that array.

Code example:
Change
`Observable.just(viewModel.events).bind(to: self.collectionView.rx.items(dataSource: dataSource)).disposed(by: disposeBag)
`
to

`let section = [
      SectionOfCustomData(header: "", items: viewModel.events)
    ]
    Observable.just(section)
      .bind(to: self.collectionView.rx.items(dataSource: dataSource))
      .disposed(by: disposeBag)`

**Comment by raytso** [comment]
Here is a shortened version of my code:

`protocol FavouritesViewModel {
    var favouritesIndex: Variable<[CustomType]> { get }
}

class FavouritesViewController: UIViewController {
    private let disposeBag = DisposeBag()
    
    // MARK: - IBOutlets

    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Properties
    
    var viewModel: FavouritesViewModel!
    
    private var dataSource: RxTableViewSectionedReloadDataSource<SectionModel<String?, CustomType>>!
    
    // MARK: - View life cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        bindTableView()
    }
    
    // MARK: - UDF
    
    private func bindTableView() {
        self.dataSource = FavouritesViewController.dataSource()
        
        viewModel.favouritesIndex.asObservable()
            .map { SectionModel(model: nil, items: $0) }
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
    }
}

extension FavouritesViewController {
    static func dataSource() -> RxTableViewSectionedReloadDataSource<SectionModel<String?, CustomType>> {
        return RxTableViewSectionedReloadDataSource(
            configureCell: { (dataSource, tableView, indexPath, element) in
                // ...
            },
            titleForHeaderInSection: { dataSource, index in
                let section = dataSource[index]
                return section.model
            }
        )
    }
}`

I'm still getting the error though :(

**Comment by Vkt0r** [comment]
Feel free to open the issue @zenghailong if it wasn't solved

**Comment by dlindenkreuz** [comment]
Unfortunately, the above fix by @AshleyDeng didn't work for me. I had to make sure my `SectionModelType` implemented the `Equatable` protocol correctly. Section headers etc. didn't matter at all.

Tbh, this error is pretty obscure and absurdly hard to trace. 😞

**Comment by lenkaiser** [comment]
@dlindenkreuz Do you have an example for me? The solution of AshleyDeg isn't going to work for me either since I get my data from my ViewModel.
```
public struct NotificationViewSection {
    var header: String
    var notifications: [Domain.Notification]
}

extension NotificationViewSection: AnimatableSectionModelType {
    public typealias Item = Domain.Notification
    public typealias Identity = String

    public var items: [Item] {
        return notifications
    }

    public var identity: String { return header }

    public init(original: NotificationViewSection, items: [Item]) {
        self = original
        notifications = items
    }
}
```
```
reactor.state
    .map { $0.notifications }
    .bind(to: node.tableNode.rx.items(dataSource: dataSource))
    .disposed(by: disposeBag)
```

**Comment by moonvader** [comment]
Same problem! 
What should be done to make it work.
Tried adding Equatable for my struct with no luck
