### ISSUE TITLE
Unique cell content action handler

### ISSUE THREAD

**Issue by disquad** [RxSwiftCommunity/RxDataSources#229]
Hello, can you explain the best way to bind some button action from some cell to tableviewcontroller view model. An example: cell with two buttons "Add friend" and "Send message".

I tried to provide it via delegate pattern, but I hope there is better way.

[My SO question](https://stackoverflow.com/questions/50086199/how-to-handle-unique-cell-action-with-mvvm)

**Comment by freak4pc** [comment]
This is a bit out-of-scope for this library. RxDataSources is only about representing observable data on-screen, in a Table or Collection view. 

One way of doing what you want is exposing an Observable from the button on the cell and binding that to your "master" ViewModel (the View Controller's one), so the ViewModel can decide what to do with it and emit a new cell change when needed.
