### ISSUE TITLE
Remove Swift 2.2 curried functions warnings

### ISSUE THREAD

**Issue by damienrambout** [RxSwiftCommunity/RxDataSources#23]
Since Swift 2.2 (Xcode 7.3+), use of curried functions is deprecated. It will be marked as an error in Swift 3.0. It means only single parameter list functions will be allowed.

**Comment by kzaher** [comment]
I've moved it to lambdas now, didn't see any warning, do you see it again?

**Comment by damienrambout** [comment]
Sounds good now :+1: Thanks!
