### ISSUE TITLE
Autocompletion failure in closure

### ISSUE THREAD

**Issue by AlexanderBollbach** [RxSwiftCommunity/RxDataSources#231]
in this closure auto-complete totally fails.  I filed this as a Swift bug on the Swift bug site.  Apparently some one fixed it for the Swift 4.2 snapshot but trying that snapshot still doesn't fix it for me.  

Is anyone else running Xcode 9.3 / Swift 4.1 experiencing this?

```
configureCell: { (datasource, tableview, indexPath, item) -> UITableViewCell in {

   // autocomplete fails and show <<error type>>
}
```

**Comment by Vkt0r** [comment]
@AlexanderBollbach This is not an issue in the library! I recommend you delete your DerivedData and close and open your project again.
