### ISSUE TITLE
ConfigureCell function will called after data source disposed

### ISSUE THREAD

**Issue by retsohuang** [RxSwiftCommunity/RxDataSources#235]
I changed example project's EditingExampleTableViewController.swift data source like following
```swift
      let dataSource = RxTableViewSectionedAnimatedDataSource<NumberSection>(
        animationConfiguration: AnimationConfiguration(insertAnimation: .top,
                                                       reloadAnimation: .fade,
                                                       deleteAnimation: .left),
        configureCell: { [weak self] (dataSource, table, idxPath, item) in
          guard let strongSelf = self else { fatalError() }
          let cell = table.dequeueReusableCell(withIdentifier: "Cell", for: idxPath)
          cell.textLabel?.text = "\(item)"
          return cell
      },
        titleForHeaderInSection: { (ds, section) -> String? in
          return ds[section].header
      },
        canEditRowAtIndexPath: { _, _ in
          return true
      },
        canMoveRowAtIndexPath: { _, _ in
          return true
      }
      )
```

The problem is configureCell will called after data source disposed due to `layoutIfNeeded` function call so the app will crash after pop view controller (because `self` is nil).
I'm not sure this is expected behavior or not, maybe I should return an empty UITableViewCell when `self` is nil?

In this case, I need call `self` do something other work, what is the best practice?

**Comment by kzaher** [comment]
Hi @retsohuang ,

you should never call `self` in configureCell. That's a design smell.

**Comment by retsohuang** [comment]
Yes I know, but sometimes I don't have a chose, for example:
I need to do some work when user tap on the button on the cell (rather than an entire cell), no matter I use delegation or reactive way, I always need to call `self` to do that work right?

Any ideas are appreciated.

**Comment by kzaher** [comment]
You don't. Instead of using `self.something` declare a local variable `let something = self.something` and then call `something` from closure vs `self.something`.
