### ISSUE TITLE
Segmentation faults when compiling with Xcode 7.3 

### ISSUE THREAD

**Issue by damienrambout** [RxSwiftCommunity/RxDataSources#24]
Since, Xcode 7.3, segmentation faults occur in `TableViewSectionedDataSource.swift` and `CollectionViewSectionedDataSource.swift`.

----------------------------------

Concerning `TableViewSectionedDataSource.swift`, it looks like the faults come from these 4 functions:
- `override func _tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool`
- `override func _tableView(tableView: UITableView, canMoveRowAtIndexPath indexPath: NSIndexPath) -> Bool`
- `override func _sectionIndexTitlesForTableView(tableView: UITableView) -> [String]?`
- `override func _tableView(tableView: UITableView, sectionForSectionIndexTitle title: String, atIndex index: Int) -> Int`

I think the compiler does not like `super._tableView(...)` that much...

----------------------------------

Concerning `CollectionViewSectionedDataSource.swift`, it looks like the faults come from these 2 functions:
- `override func _collectionView(collectionView: UICollectionView, canMoveItemAtIndexPath indexPath: NSIndexPath) -> Bool`
- `override func _collectionView(collectionView: UICollectionView, moveItemAtIndexPath sourceIndexPath: NSIndexPath, toIndexPath destinationIndexPath: NSIndexPath)`

As for table view, the compiler does not seem to like `super._collectionView(...)`.

**Comment by damienrambout** [comment]
I think I know how to fix this. I will PR you ASAP.

**Comment by kzaher** [comment]
... merged
