### ISSUE TITLE
First batch of items not animated in collection views

### ISSUE THREAD

**Issue by vzsg** [RxSwiftCommunity/RxDataSources#246]
When data is bound to a collection view via the animated data source, the items of the very first event appear without any animation – which seems to be [deliberate](https://github.com/RxSwiftCommunity/RxDataSources/blob/3.0.2/Sources/RxDataSources/RxCollectionViewSectionedAnimatedDataSource.swift#L118-L122), but otherwise pretty counterintuitive.

I made a [demo project](https://github.com/RxSwiftCommunity/RxDataSources/files/2195708/RxDSIssue_1.zip) where this issue is apparent, and my current workaround – which can cause inconsistency crashes, but that's a story for another day.

**Comment by freak4pc** [comment]
I think this is the reason: 

https://github.com/RxSwiftCommunity/RxDataSources/blob/ddfc9a1fdba650984f3a72b5b318e55fcfeccbae/Sources/RxDataSources/RxCollectionViewSectionedAnimatedDataSource.swift#L63-L65

**Comment by kzaher** [comment]
Please bear in mind backwards compatibility. UICollectionView is probably one of the worst piece of UIKit when it comes to stability.

**Comment by vzsg** [comment]
The `startWith` workaround has been working for me from iOS 9 (which is the deployment target of the app I had to figure it out on), I never tested it on iOS 8 though. It's just too far into the past.

Maybe the `dataSet` logic could be wrapped with an `#if available` block so it's not applied on current versions?

**Comment by kzaher** [comment]
Hi @vzsg , 

if you want first animated update, you would just bind to an empty result first with `startWith`. It makes sense that first one is non animated since it doesn't have any state to animate from.

**Comment by vzsg** [comment]
Yeah, that's what I figured by myself too (and visible in the demo project above).
A note in the readme would be nice, but I guess we can consider this issue closed.

---

I originally started writing this issue as a precursor for a bigger deal: using `startWith` in a combination of schedulers did lead to a large number of crashes in one of my projects. But I can't reproduce it without making a mistake purposefully, so all's well.
