### ISSUE TITLE
Swift Compiler Segmentation Faults on 32 bit architecture devices

### ISSUE THREAD

**Issue by KingDavid91** [RxSwiftCommunity/RxDataSources#247]
Xcode Ver.: 9.4.1
Devices Tested: iPhone 4s (iOS Ver. 9.3), iPhone 5 (iOS Ver. 10.3.1), iPhone 5s (iOS Ver. 10.3.1)
RxDataSources Ver.: 2.0.2

When attempting to compile and run source code on 32 bit architecture devices (i.e. iPhone 4s, iPhone 5), I'm receiving a segmentation fault within the `TableViewSectionedDataSource` class on`deinit` (isn't explicitly defined... )

The issue is not present on 64 bit architectures (i.e. iPhone 5s and greater) as it was tested on both an iPhone 5 and iPhone 5s running the same iOS version (Ver. 10.3.1)

Searching through the existing issues I discovered there was a fix for segmentation issues with the DataSource classes (TableViewSectionedDataSource.swift and CollectionViewSectionedDataSource.swift) in March of 2016. ([Added Issue for Reference](https://github.com/RxSwiftCommunity/RxDataSources/pull/25))

Unfortunately I don't have the option to update RxDataSources to the latest version as our organization has existing dependencies on RxCocoa 3.x.x (whereas RxDataSources 3.0.2 is using RxCocoa 4.x.x) however it appears that RxDataSources 2.0.2 was tagged in Sept. 2017 so it would ideally contain the fix mentioned above.

Below is the segmentation fault experienced on compilation:
`1.	While emitting IR SIL function "@_T013RxDataSources018TableViewSectionedB6SourceCfE".
 for 'deinit' at /Users/SourceCode/iPhone/project/Pods/RxDataSources/Sources/RxDataSources/TableViewSectionedDataSource.swift:105:12`

**Comment by kzaher** [comment]
Hi @KingDavid91 ,

we can't fix compiler crashes, this is out of scope of this project. Please report this issue to Apple, or make a PR that fixes this issue and we will consider releasing it.

**Comment by KingDavid91** [comment]
Oh thats unfortunate..
I doubt Apple will resolve this issue for a Third Party Framework.

However, I believe I have an implementation that resolves this issue, I will fork the repo and submit a PR for review
