### ISSUE TITLE
Section Header Dissapear when beginUpdates

### ISSUE THREAD

**Issue by alfian0** [RxSwiftCommunity/RxDataSources#249]
Hi, I want implement RxDatasource and cell with textView. And I need to update tableView when textView Change to fit with textView height, but when I update the tableView, section header dissapear. How to solve this ?

**Comment by mkko** [comment]
Can you share a bit more, provide some code or some example how to reproduce this?

**Comment by mkko** [comment]
Okay, thanks. So `tableView(_:viewForHeaderInSection:)` doesn't get called after the update, right?

One thing to note is that you're using `tableView.dequeueReusableCell(withIdentifier:)`. I think reloading table view might give you empty cells. If you use an overload that also takes the index path that will always return a cell.

**Comment by alfian0** [comment]
Ha ha, oke ...this solved,
I changed cell to view, and working properly :)

**Comment by mkko** [comment]
Oh, good catch! Happy to close this then.
