### ISSUE TITLE
How to made RxTableViewSectionedAnimatedDataSource keep the old objects if the new ones are no different from the old ones?

### ISSUE THREAD

**Issue by vldalx** [RxSwiftCommunity/RxDataSources#250]
Firstly, the same RxSwiftCommunity/RxASDataSources#25 issue was created in `RxASDataSources` repo.

Let's say I have two arrays of data. The second array has more element than the first one, but all elements of the first array are equal to the first elements of the second array.

Steps:
- The first array is passed to `RxTableViewSectionedAnimatedDataSource` instance.
- A cell is created for each item from the first array. The cell holds the item.
- The second array is passed to the datasource instance. 
- New cells are created for new items from the second array.
- The datasource contains all items from the second array, but the cells that were created for the items from the first array still hold that items.

**Comment by vldalx** [comment]
The code below helps to reproduce the issue.
``` Swift
typealias Section = AnimatableSectionModel<Int, ViewModel>

final class ViewModel: IdentifiableType, Equatable, CustomDebugStringConvertible {
    private(set) var identity: Int
    private let debugText: String
    
    var debugDescription: String {
        return "\(debugText) - \(identity)"
    }
    
    init(id: Int, debugText text: String) {
        identity = id
        debugText = text
    }
    
    @objc func didButtonTap() {
        print("binded to cell item: \(debugDescription)")
    }
    
    static func == (lhs: ViewModel, rhs: ViewModel) -> Bool {
        return lhs.identity == rhs.identity
    }
}

class ViewController: UIViewController {
    private let disposeBag = DisposeBag()
    
    private let tableView: UITableView = {
        let table = UITableView()
        table.estimatedRowHeight = 0
        table.rowHeight = 44
        table.register(ButtonTableCell.self, forCellReuseIdentifier: "cellId")
        return table
    }()
    
    private lazy var dataSource: RxTableViewSectionedAnimatedDataSource<Section> = { [unowned self] in
        RxTableViewSectionedAnimatedDataSource<Section>(configureCell: { _, table, index, viewModel in
            let cell = table.dequeueReusableCell(withIdentifier: "cellId", for: index) as! ButtonTableCell
            cell.viewModel = viewModel
            cell.button.setTitle(viewModel.debugDescription, for: .normal)
            
            cell.button.addTarget(viewModel, action: #selector(ViewModel.didButtonTap), for: .touchUpInside)
            cell.button.addTarget(self, action: #selector(ViewController.didCellButtonTap(_:)), for: .touchUpInside)
            
            return cell
        })
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        view.addSubview(tableView)
        
        let initialItems = (0...7).map { ViewModel(id: $0, debugText: "initial item") }
        let delayedItems = (0...10).map { ViewModel(id: $0, debugText: "delayed item") }
        
        let initialObservable = Observable.just(initialItems)
        let delayedObservable = Observable.just(delayedItems).delay(5, scheduler: MainScheduler.asyncInstance)
        
        Observable
            .merge([initialObservable, delayedObservable])
            .map { [Section(model: 0, items: $0)] }
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        tableView.frame = view.bounds
    }
    
    @objc func didCellButtonTap(_ button: UIButton) {
        let buttonCell = button.superview!.superview as! ButtonTableCell
        let index = buttonCell.viewModel.identity
        let viewModel = self.dataSource[IndexPath(row: index, section: 0)]
        
        print("item in datasource: \(viewModel.debugDescription)")
    }
}

final class ButtonTableCell: UITableViewCell {
    var viewModel: ViewModel!
    
    let button: UIButton = {
        let button = UIButton()
        button.setTitleColor(.black, for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()
    
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        
        selectionStyle = .none
        
        contentView.addSubview(button)
        
        button.leadingAnchor.constraint(equalTo: contentView.leadingAnchor).isActive = true
        button.topAnchor.constraint(equalTo: contentView.topAnchor).isActive = true
        button.trailingAnchor.constraint(equalTo: contentView.trailingAnchor).isActive = true
        button.bottomAnchor.constraint(equalTo: contentView.bottomAnchor).isActive = true
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func prepareForReuse() {
        super.prepareForReuse()
        
        button.removeTarget(nil, action: nil, for: .allEvents)
    }
}
```

**Comment by sergdort** [comment]
Hi, @vldalx 

`Identity` and `Equatable` are different concepts

This is a wrong implementation of `Equatable` with regard to `Identity ` 👇
```swift
static func == (lhs: ViewModel, rhs: ViewModel) -> Bool {
        return lhs.identity == rhs.identity
    }
```

**Comment by vldalx** [comment]
Hi, @sergdort 
It just an example that shows what happens when two objects has the same `Identity` and `==` operator returns `true`

**Comment by sergdort** [comment]
I'm not sure what do you want to achieve with the example you posted...

I mean if view models `Identity` are the same and view models are `Equal` then cells won't be rebound with new view models as they are the same.

**Comment by vldalx** [comment]
> I mean if view models Identity are the same and view models are Equal then cells won't be rebound with new view models as they are the same.

It is the right behaviour. But the datasource **will replace the old object with the new one in the internal storage**.
The cell hold the object. For example, if a user clicks the button some fields will be changed. But the change won't happen with object in the datasource.

**Comment by mkko** [comment]
I think the example is a really risky. You're using classes and the equality is simply determined by the ID. The current implementation doesn't replace items if they are equal, so you will end up with contents of the first list plus the excess part from the second list. The items won't be replaced just as @sergdort clarified. Also relying on the implementation details is dangerous.

In general I think equality with reference types is a risky concept when doing the comparison to something else than the reference.

I had pretty much the same issue just some time ago. I [asked this on StackOverflow](https://stackoverflow.com/questions/51375543/map-a-list-of-one-type-to-another-in-rxswift-but-keep-existing-ones/51754503#51754503) but didn't really get anywhere. I'm currently using `scan` to loop the previous items back and reusing these while doing the mapping. In your case there'd be no need for conversion though.

**Comment by mkko** [comment]
Just change the code a bit:

```swift
    var debugDescription: String {
        return "\(debugText) - \(identity) - \(Unmanaged.passUnretained(self).toOpaque())"
    }
```

You'll see that the first batch of items don't change. The new view models you create are only added with IDs 8, 9 and 10 and the rest are the initial items.

**Comment by vldalx** [comment]
Did you press, for example, the first button in my example?
The first cell holds the first item from the first array, but the datasource contains the first item from the second array.
Take a look at didButtonTap() and didCellButtonTap(_:) methods. When you press the button the first method prints the description of the item binded to the cell, the second method prints the description of the item from the data source with the same index.

**Comment by mkko** [comment]
Yeah, and you will have the datasource out of sync with the UI. I'm not sure what are you trying to prove here.

**Comment by mkko** [comment]
I think I understand your point of view, it can be unexpected.

However, the issues are because you're misusing the `Equitable`. In your implementation two view models are equal if they have the same ID, but instead you should do a deep comparison and include all fields including bindings and such to determine equality.

It is still not quite clear to me what are you trying to achiecve. Do you want to create new view models and have them bound to the UI replacing the previous ones?

**Comment by vldalx** [comment]
Let's say, my app has a newsfeed. The user is able to refresh it as often as he/she wants.
If the user refreshes the newsfeed and any post hasn't been changed, the cell for that post will still contain the old post view-model object, but the data-source will contain the new one.

I know how to use `Equitable` and `IdentifiableType`. For example:
``` Swift
final class PostViewModel: IdentifiableType, Equatable {
    private(set) var identity: Int
    private let text: String

    init(id: Int, text: String) {
        identity = id
        self.text = text
    }

    static func == (lhs: PostViewModel, rhs: PostViewModel) -> Bool {
        return lhs.text == rhs.text
    }
}
```
Don't you want to say it's impossible two different objects of `PostViewModel` type have the same identity and they are equal? Why can't I use `ViewModel` from my example to reproduce the same situation?

> It is still not quite clear to me what are you trying to achiecve. Do you want to create new view models and have them bound to the UI replacing the previous ones?

I want if a new view-mode is equal to the old one, the datasource will still contain the old view-model.

**Comment by mkko** [comment]
In that case you should not create new view models if one already exists. Before creating, you should check whether one exists and use that one. To do this, for one, you can loop the previous values back with `scan`.  One example of this is in the [StackOverflow answer](https://stackoverflow.com/questions/51375543/map-a-list-of-one-type-to-another-in-rxswift-but-keep-existing-ones/51754503#51754503).

In any case the equality should not be implemented they way you have. Just to give some pointers, if you need to use `class`, then either inherit from `NSObject` and rely on its implementation of `Equitable` or implement the equality by comparing the references instead. You can also switch to `struct` and then you don't have to think about instances. However, in this case bindings don't work.

**Comment by vldalx** [comment]
Thanks, but I don't agree with you.
Your suggestion is a workaround. It hides the problem but doesn't solve the one.
The problem is the datasource replaces the old object with the new one in internal storage if they are equal. The datasource should ignore the new object in that case.

**Comment by mkko** [comment]
Well, the data source is doing exactly as you instruct it to do. It gets its values from the observable you're binding it to. If you want to have a data source that has this kind of behavior, feel free to implement your own.

The functionality you're asking is not consistent.

**Comment by freak4pc** [comment]
Hey @vidalx - Please not that this library provides no guarantees around proper diffing for Reference Types, so I don't believe we can offer anything beyond a workaround for your issue. 

The model representing your cell should optimally be a value type (such as a Struct or an Enum). Keeping a reference to the old model isn't in the goals for this library since it focuses on reloading and presenting proper data on screen, not necessarily any reference classes behind that data.
