### ISSUE TITLE
Differentiator doesn't detect changes in section model

### ISSUE THREAD

**Issue by dvir04** [RxSwiftCommunity/RxDataSources#252]
I've implemented an enum confirmed to the AnimatableSectionModelType protocol.
This enum has an associated value represent the section header title.
I've initialize a section models variable and bind it to tableView.rx.items.
Unfortunately, updating my section models variable does update the section items, but doesn't update the section title. Seems like the Differentiator miss this change.

I've attach a sample project for your convenience.

Thanks.
[RXDataSources_SectionAnimated.zip](https://github.com/RxSwiftCommunity/RxDataSources/files/2283365/RXDataSources_SectionAnimated.zip)

**Comment by mkko** [comment]
Awesome work providing a minified sample for this!

Curiously it also crashes when, for instance you first have two sections in your example and then set the sections only to contain the other. My debugger seems to be gone haywire though, could be my machine. I'll try to look if there's something.

**Comment by mkko** [comment]
Oh, my mistake. Both sections were using the same identity. It didn't crash until I tried to change the sections.

`titleForHeaderInSection` is not used as an input for the Diff and I don't think it would make sense in any case. I'm not sure if you have any better solution but to update the header manually. I believe that's the solution also when dealing with Apple's APIs directly.

current implementation is analogous with

**Comment by ofirreuv72** [comment]
Thank you for your comments. 

I work on the same team with Dvir, 
Why should the Diff care about the title only?

Wouldn't  it be better to use the operator ==? to decide if it needs to reload? 

Thank you

**Comment by mkko** [comment]
I think you have two options here. For one, you can change the identity of the section to trigger the reload of the section. The other option is to change the header by fiddling the view hierarchy and retrieving the header view from there.

What I'm saying is that the Diff doesn't depend on visual properties which the title is. If you happen to notice, protocol implementation `MySection: Equatable` is redundant, the sections are not compared this way. Just try removing the extension and nothing is changed.

I think comparing the sections (or their titles) would also cause a lot of confusion. The equality would need to consider also the contained items for each section and that is exactly what the Differentiator is handling.

Does this make sense to you?

**Comment by dvir04** [comment]
Hi,

Thanks again for your comments!

I think that comparing sections items without their cells items can make sense for differing data used for the sections header.
The implementation for cells differences can remain the same.

Anyway, if you don't think so, or maybe it breaks some other logics, is it possible to get also the new section models array in the decideViewTransition callback?
This way I can catch this case and force the tableView to reload the new data by returning the ViewTransition.reload value.

**Comment by freak4pc** [comment]
Nice seeing more Israelis joining the RxSwift community :) 

About your example

1. Please do not use `Variable`s - they've been soft-deprecated for a while now and will be hard-deprecated by RxSwift 5. 

2. I'm a bit confused with why you're using sub-sectioning of a section in a way. You define an `enum` that has a `.section` case, even though the entire item is already a section - so what you'd really want to have is a title of some sorts and its items. 

3. Your section must have an `identity` field - your `AnimatableSectionModelType` has the same identity for every section, so clearly no change is detected.

**Comment by mkko** [comment]
I'm curious, how do you tell someone's nationality without profile? And ditto, nice to see more Israelis here :-)

I think one source of confusion here is the identity and the distinction from equality. Maybe this is because the data can change in two ways: on the list level where items are rearranged and on the item level where the contents of an item should be reloaded / re-evaluated.

In this case item level changes such as the title change are not updated on the UI even though it might sound logical to do so. I believe this is in line with Apple's implementation of section handling.

Would be cool though to make this more developer friendly, if this makes sense.

**Comment by freak4pc** [comment]
> I'm curious, how do you tell someone's nationality without profile? And ditto, nice to see more Israelis here :-)

Nothing too fancy, they just have extremely Israeli names that leave no doubt haha ;-) 

> I think one source of confusion here is the identity and the distinction from equality. Maybe this is because the data can change in two ways: on the list level where items are rearranged and on the item level where the contents of an item should be reloaded / re-evaluated.

Yeah that's true - but think of it this way: 

1. Identity: Used to define _which_ things changed.
2. Equatable: Used to define _if_ these things changed. 

We recently added some clarifying text about this here; do you have any additional thoughts about this: 

https://github.com/RxSwiftCommunity/RxDataSources#animated-data-sources

**Comment by freak4pc** [comment]
IRT to ReactorKit, see here: https://github.com/ReactorKit/ReactorKit/pull/64

I don't think RxDataSources currently support reloading only the header component. If you want to push a PR around this addition along with tests, I'd love to review it.

Shai.

**Comment by dvir04** [comment]
> I don't think RxDataSources currently support reloading only the header component. If you want to push a PR around this addition along with tests, I'd love to review it.

I'll update if so.
Thanks again :)

**Comment by mkko** [comment]
> I don't think RxDataSources currently support reloading only the header component. If you want to push a PR around this addition along with tests, I'd love to review it.

Would be a really nice addition. However, just to make sure that we'd be on the same track, I would not involve `Equatable` for this the way it was used in the sample project. Would `reloadSections:withRowAnimation` or `beginUpdates`/èndUpdates` work in your case?

**Comment by dvir04** [comment]
> Would be a really nice addition. However, just to make sure that we'd be on the same track, I would not involve Equatable for this the way it was used in the sample project. Would reloadSections:withRowAnimation or beginUpdates/èndUpdates` work in your case?

As long as the the new section models have the updated data, it will work.

**Comment by mkko** [comment]
Please correct me if I'm wrong, but `beginUpdates`/`endUpdates` don't seem to update the section title. I modified your example with this and it still didn't work. `RxDataSources` is using these calls internally which might be the source of the issue.

Anyways, I'd be really happy as well to review your PR if you come up with a solution.

**Comment by dvir04** [comment]
Ok. I'll check it in the next few days, and let you know If I can suggest any solution for that.
Thanks.
