### ISSUE TITLE
How to Smooth Scroll in a table view while appending items to the data source

### ISSUE THREAD

**Issue by nmdias** [RxSwiftCommunity/RxDataSources#258]
Hi,

My tables views jump like crazy when paginated. First page is OK, however, when my data source changes, and new rows are added at the bottom, if the appending happens when I have scrolled past the last row, there is a "jump" in the table view trying to readjust.

Before Rx, I would calculate the indexPaths that I needed to update, and for an insert, I would just do this.:

```swift
tableView.beginUpdates()
tableView.insertRows(at: indexPaths, with: .top)
tableView.endUpdates()
```

I could scroll at the speed of light with that approach. But this ain't Kansas anymore... 😨 

Any sugestions on how I can tackle this?

Thank you!

**Comment by cozzin** [comment]
This code might help you.
https://github.com/RxSwiftCommunity/RxDataSources/issues/211#issuecomment-400886008

**Comment by nmdias** [comment]
Outstanding @cozzin, caching the `estimatedHeightForRowAt` is doing wonders for me. 

Thank you 🙏

**Comment by RachelPolachova** [comment]
Hey guys, I was struggling with this for a long time and I couldn't figure it out.

Caching didn't help me, then I found this on stackoverflow and it actually worked (together with caching): 
https://stackoverflow.com/questions/44928752/how-to-disable-automatic-scrolling-to-top 

hope it helps
