### ISSUE TITLE
Potential leak in `rx_itemsAnimatedWithDataSource`

### ISSUE THREAD

**Issue by wouterw** [RxSwiftCommunity/RxDataSources#27]
First of all, thanks for the great work on RxSwift! I'm really enjoying working with it. :D

That being said; I'm currently experiencing a potential leak when using `tableView.rx_itemsAnimatedWithDataSource`.

I have a `UIViewController` polling the server and binding the result to a `UITableView`:
https://github.com/wouterw/leak/blob/master/Leak/ViewController.swift

This VC is inside a `UITabBarController` and should stop polling when not visible. In order to achieve this behaviour I'm subscribing inside `viewWillAppear` and disposing inside the `viewWillDisappear` hook.

This approach seems to work for simpler `Observables` (e.g. `Driver<Int>.interval(1)`), but not when using in combination with `tableView.rx_itemsAnimatedWithDataSource`.

I've setup a minimal app demonstrating the problem here: https://github.com/wouterw/leak.

**Comment by kzaher** [comment]
Hi @wouterw ,

thnx for reporting this. 
I've found some time to take a look at this.
Awesome code example :+1:, found the problem, will push the fix soon.

**Comment by ycfreeman** [comment]
any ETA for the fix?

**Comment by kzaher** [comment]
@ycfreeman this weekend

**Comment by kzaher** [comment]
@wouterw @ycfreeman 

The fix is in `develop` branch of `RxSwift`

https://github.com/ReactiveX/RxSwift/tree/develop

Hoping to release a new version tomorrow or day after tomorrow. Still need to do some release chores.

**Comment by wouterw** [comment]
@kzaher Thanks! :+1:
