### ISSUE TITLE
Create Archive from RXDataSources

### ISSUE THREAD

**Issue by hajiko-mobile** [RxSwiftCommunity/RxDataSources#270]
Hi!
I am trying to "Archive" the RXDataSources within Xcode, but I always get a zero bytes file.

Steps:
1. Download RXDataSources and extract it
2. Download RXSwift and extract it to RXDataSources, so the Carthage folder is existing
3. Select generic iOS target
4. Select Product->Archive
5. Go to the derived folders of Xcode and observe that the archive is zero bytes.

My goal is to have a RXDataSources.framework file that can be archived.

Note: RXSwift itself can be archived but in combination with a manual created RXDataSources.framework it will be zero bytes.

Xcode: 9.4.1
RXSwift: https://github.com/ReactiveX/RxSwift/releases/download/4.2.0/RxSwift.framework.zip
RXDataSources: https://github.com/RxSwiftCommunity/RxDataSources/releases/tag/3.1.0

**Comment by hajiko-mobile** [comment]
Okay I found the reason, I had to set the "skip install = no" on the target "RXDataSources" and not on the Project itself.

**Comment by Tawfikk** [comment]
You're solved problem ?

**Comment by hajiko-mobile** [comment]
Yes Its solved. Thank you!
