### ISSUE TITLE
Can we use Class instead of Structs?

### ISSUE THREAD

**Issue by luucassoares** [RxSwiftCommunity/RxDataSources#280]
Hi people, good night. I'm sorry if this is a too newbie question or whatever but I didn't find anything on web so here it goes: Is it possible to use Class instead of Structs?

Here goes my code: 

`
struct Family {
    var id: Int
    var name: String
}
extension Family: IdentifiableType, Equatable {
    typealias Identity = Int
    var identity: Int { return id }
}
func == (lhs: Family, rhs: Family) -> Bool {
    return lhs.id == rhs.id && lhs.name == rhs.name
}
struct SectionFamily {
    var header: String
    var items: [Item]
}
extension SectionFamily: AnimatableSectionModelType {
    typealias Item = Family
    var identity: String { return header }
    init(original: SectionFamily, items: [Item]) {
        self = original
        self.items = items
    }
}
`

I don't know if it will be pasted correctly, Im sorry if it isn't. But anyways, I'm implemeting RxTableViewSectionedAnimatedDataSource<SectionFamily> and it is just an small struct but what if I use json data parsed into class objects to feed my tableview? I use the EVNetworkingObject framework to parse them

thank you in advance!

**Comment by luucassoares** [comment]
I'll close this issue since I found out how to do what I was looking for. I just needed a little bit more studying before asked that question. I'm sorry anyways and thanks

**Comment by hjqiaho** [comment]
import UIKit
import RxDataSources

class AssignHWSectionModel : YLModel,AnimatableSectionModelType{
    typealias Item = AssignHWModel
    
    required init(original: AssignHWSectionModel, items: [Item]) {
        self.header = original.header
        self.items = items
    }
    
    required init() {
        fatalError("init() has not been implemented")
    }
    
    
    var header: String = ""
    var items: [Item] = []
    
    var identity: String {
        return header
    }
}

import UIKit
import RxDataSources

class AssignHWModel: YLModel,IdentifiableType {
    typealias Identity = HWTypeCode
    var identity:Identity {return typeCode}
    
    var title: String = ""
    var desc: String = ""
    var img: String = ""
    var typeCode: HWTypeCode = HWTypeCode.C202
    
}
