### ISSUE TITLE
Binder like property to bind items.

### ISSUE THREAD

**Issue by AlexisQapa** [RxSwiftCommunity/RxDataSources#282]
Hi, 

I'd like to have a binder like property to bind the items on my custom view. This would allow keep the tableview and the datasource private.

instead of 
bind(to: view.tableView.items(dataSource: view.dataSource)
use 
bind(to: view.items)

Is it possible ?

**Comment by mkko** [comment]
Hi,

Yes it's definitely possible. How does the view look like you want to bind to?

Besides the `UITableView.rx.items(dataSource:)`, you can look an example from [MKMapView+Rx.swift:241](https://github.com/RxSwiftCommunity/RxMKMapView/blob/master/Sources/MKMapView%2BRx.swift#L241). Not saying it's the best one but just one I happen to know about. The bits and pieces you need to implement are there and I think the project is small enough to not get easily swamped.

**Comment by AlexisQapa** [comment]
I ended doing this: 
var items: (_ items: Observable<[Section]>) -> Disposable {
        return base.tableView.rx.items(dataSource: base.dataSource)
}
