### ISSUE TITLE
"there is already a delegate (or data source) set somewhere previously"

### ISSUE THREAD

**Issue by alouanemed** [RxSwiftCommunity/RxDataSources#283]
I upgraded some pods and cleaned the project and got this error for the first time on my project.

```
thread 1: Assertion failed: This is a feature to warn you that there is already a delegate (or data source) set somewhere previously. The action you are trying to perform will clear that delegate (data source) and that means that some of your features that depend on that delegate (data source) being set will likely stop working.
If you are ok with this, try to set delegate (data source) to `nil` in front of this operation.
 This is the source object value: <UICollectionView: 0x7f9abb8b1600; frame = (0 0; 375 667); c
```

I have a TableView with multiple different table cell views, 3 of them are CollectionViews. 

The error point to this part:

 ```
func bindViewModel() {
        viewModel.transform().asDriver(onErrorJustReturn: [])
            .drive(self.collectionView.rx.items(cellIdentifier: reuseIdentifier, cellType: ProductImageItemCell.self)) { collectionView, viewModel, cell in
                cell.bind(to: viewModel)
            }.disposed(by: rx.disposeBag)
 
    }
```
In #185 It suggested that to use this before binding the collection view : 

```
self.collectionView.delegate = nil
self.collectionView.dataSource = nil
```
I tried so but without any luck. How to solve this? and is there any explanation why this is happening?

**_Edit_**:
When choosing the Scheme (Beta) on which the Xib file created it runs without issues rolling back to a different scheme (Debug) fails.

**Comment by mgoldin** [comment]
Hello! Have you fixed this issue? How?

**Comment by ramrcram** [comment]
Any update on this issue? I am facing the same problem. Using Swift 4.2 RxCocoa (4.4.0) RxSwift (4.4.0). 

Sample Code: 
`
viewModel.list.asDriver()
            .do{
                self.collectionViewShops.delegate = nil
                self.collectionViewShops.dataSource = nil
            }
            .drive(collectionView.rx.items(cellIdentifier: cellIdentifier,cellType:Cell.self)) { index, model, cell in
                cell.bindDataFromModel(modelObj: model)
        }.disposed(by: bag)
`

**Comment by alouanemed** [comment]
For me it wasn't related to the library itself, but rather the selected scheme. The issues solved when I choose a different scheme. I really hope someone would clarify this.

**Comment by pschneider** [comment]
> For me it wasn't related to the library itself, but rather the selected scheme. The issues solved when I choose a different scheme. I really hope someone would clarify this.

@alouanemed 

I don't think you solved it. It's just that your other scheme is not building in debug and therefor "assert" doesn't do anything.

**Comment by aarashgoodarzi** [comment]
in may case this line was enough:

`tableView.dataSource = nil`

**Comment by valilinn** [comment]
I had the same problem, my mistake was that i called my function bindTableView() in viewWillAppear instead of ViewDidLoad.
