### ISSUE TITLE
AnimatableSectionModel unused

### ISSUE THREAD

**Issue by gregpardo** [RxSwiftCommunity/RxDataSources#29]
I'm not sure if this is an issue or an inquiry. 

AnimatableSectionModel seems to not be used anywhere and I'm not sure if it's something that I should use in my project. 

If my section model extends AnimatableSectionModelType do I need to still declare something like this? 

```swift2.2
let sectionModel = AnimatableSectionModel<Section, Item>()
```

**Comment by kzaher** [comment]
Hi @gregpardo ,

you don't need to use it, it's just a handy class so you can just display something identifiable on screen quickly.
