### ISSUE TITLE
Swift closure context memory leak when binding collection view items from BehaviorSubject

### ISSUE THREAD

**Issue by gobright12** [RxSwiftCommunity/RxDataSources#296]
When the view controller below is loaded, xcode memory graph shows that a swift closure context is leaking.

    import UIKit
    import RxSwift
    import RxCocoa

    class Test4ViewController: UIViewController {
        private let collectionViewLayout: UICollectionViewLayout = {
            let layout = UICollectionViewFlowLayout()
            layout.scrollDirection = .horizontal
            return layout
        }()

        private lazy var collectionView: UICollectionView = {
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: collectionViewLayout)
            collectionView.register(UICollectionViewCell.self, forCellWithReuseIdentifier: "test")
            return collectionView
        }()

        private let subject = BehaviorSubject<[Int]>(value: [1, 2, 3])

        private let disposeBag = DisposeBag()

        override func viewDidLoad() {
            super.viewDidLoad()
            view.addSubview(collectionView)

            subject.asObservable()
                .bind(to: collectionView.rx.items(cellIdentifier: "test", cellType: UICollectionViewCell.self)) { item, feedId, cell in
                    cell.backgroundColor = .black
                }
                .disposed(by: disposeBag)
        }
    }
<img width="840" alt="rxdatasource" src="https://user-images.githubusercontent.com/34306129/55182811-e01bab80-5164-11e9-92f7-56686d9fa4a0.png">

**Comment by kzaher** [comment]
It's not.

**Comment by alouanemed** [comment]
@kzaher care to elaborate on this? I have several similar leaks but not on binding.
