### ISSUE TITLE
When will RxDataSources support Swift 5? 

### ISSUE THREAD

**Issue by krystlemaelabio** [RxSwiftCommunity/RxDataSources#304]
RxSwift already released its version to support Swift 5. When will RxDataSources support Swift 5? We are encountering compatibility issues already related to Swift 5 migration. Thanks!

**Comment by kzaher** [comment]
We first need to release RxSwift 5.0.

**Comment by krystlemaelabio** [comment]
There is already a latest release for RxSwift to support XCode 10.2. Isn't it the official release? Please confirm. [https://github.com/ReactiveX/RxSwift/releases/tag/4.5.0](url)

<img width="1135" alt="Screen Shot 2019-04-24 at 18 02 49" src="https://user-images.githubusercontent.com/38375874/56651339-64f1da80-66bb-11e9-9bb6-687bbbe3a200.png">

**Comment by krystlemaelabio** [comment]
Follow up on this. RxSwift has already released version 5.0.0.  Thanks!
[https://github.com/ReactiveX/RxSwift/releases](url)

**Comment by kzaher** [comment]
The release is out.
