### ISSUE TITLE
Is it possible to have multiple models in RxTableViewSectionedReloadDataSource?

### ISSUE THREAD

**Issue by kishyr** [RxSwiftCommunity/RxDataSources#31]
Hi

Consider the following scenario: I have a table view that contains 2 sections. Section 1 contains multiple products (`Product` model) and Section 2 contains multiple payment methods (`PaymentMethod` model). How can I create an Rx-based DataSource that contains both models so that I can display their appropriate cells/data in the tableview?

Thanks for the great library. It's awesome!

—Kishyr

**Comment by kzaher** [comment]
Hi @kishyr ,

you can model your sections and items as enums :) That would solve your issues I believe.

**Comment by kishyr** [comment]
Hi @kzaher,

Thanks for replying! The problem comes in when trying to bind a ViewModel to a TableView using `rx_itemsWithDataSource`.

For example, given `RxTableViewSectionedReloadDataSource<SectionModel<String, Product>>` as a datasource, and a `PublishSubject<[SectionModal<String, Product>]>` as a ViewModel, I'm not sure how to use enums in this instance. How would I bind/send/set the products, and payment methods to the tableview?

**Comment by kzaher** [comment]
Hi @kishyr ,

I would suggest taking a look at example app inside this repo, or maybe providing a more detail explanation of problem you are experiencing.

**Comment by sergdort** [comment]
Hi, guys

Looks like this is pretty common problem, for users of the library :) I remember couple weeks ago some guys asked this question on the main repo.

Maybe we could implement this in the example app, what do you think @kzaher? I could spend some time this week to do this:)

**Comment by kishyr** [comment]
@sergdort that would be fantastic!

I tried to create an enum type which conformed to `SequenceType` and set that as array-type `item` in the SectionModel (`CheckoutReviewItem` below), but because it's expecting an array, and not something that conforms to `SequenceType`, it doesn't work.

```swift
var reviewDataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, CheckoutReviewItem>>()
var reviewTableViewModel = PublishSubject<[SectionModel<String, CheckoutReviewItem>]>()
...
let productsModel = SectionModel(model: "Products", items: CheckoutReviewItem.Product(products))
let pricesModel = SectionModel(model: "Payment Methods", items: CheckoutReviewItem.PaymentMethod(paymentMethods))                        
self?.reviewTableViewModel.onNext([productsModel, pricesModel])
```
(`products` and `paymentMethods` are arrays)

Basically, the second parameter of `SectionModel` is what I'm confused about. If I need to send each tableview section a different array of objects (in my case, arrays of `Product` and `PaymentMethod`), how could it be done?

**Comment by kishyr** [comment]
Thanks @sergdort! This is exactly what I was looking for :-)

**Comment by Stoff81** [comment]
Hey guys,

Struggling to do something similar to this, although I want to add cells of different types to one section. Is this possible? My `confiureCells` isnt being called.

Tom
