### ISSUE TITLE
Can you not rely on == to compare the models?

### ISSUE THREAD

**Issue by Sweeper777** [RxSwiftCommunity/RxDataSources#314]
I realised that currently, collection view cells are updated when the models change (when the new model is != to the old model), not when their _identities_ change (when the new model.identity != to the old model.identity). Why use the `==` operator when deciding which cells to update, instead of `identity`?

This is causing a problem for me as I am using RxRealm alongside RxDataSources. My model is a realm object. The realm object defined its own `==` operator, which I can't override. My cells get deselected (due it being updated) every time something about the realm object changes, which is undesirable. I only want the cells to be updated when one of the properties change, and that is the property I set `identity` as.

**Comment by freak4pc** [comment]
RxDataSources never had a goal of supporting Reference-types (such as Classes in Realm). Equality only means the current state of some object hasn't changed, but it doesn't mean it's the same object necessarily, so you need a way to identify it. 

If you saw SwiftUI's new List() API, you'll notice they have `Identifiable` as well, for the same reason.

**Comment by Sweeper777** [comment]
I see. So what should I do instead if I want to use a Realm object as the data source for a collection view? Create a struct wrapper for it?

**Comment by freak4pc** [comment]
The easiest way would not be just a wrapper - but a struct that you copy all the fields you need into. So the Realm object shouldn’t be part of the consideration IMO. You can keep the threadSafeReference in that struct if you need a way to fetch the specific option perhaps.

**Comment by Sweeper777** [comment]
Okay. I'll try that.
