### ISSUE TITLE
Swiftlint proposal

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxDataSources#316]
Swiftlint became the golden standard for providing unified code style for projects.
What do you think about adding swiftlint to project (with build phase)?
Config from the main repo could be used - https://github.com/ReactiveX/RxSwift/blob/master/.swiftlint.yml
It will be a pleasure for me to open PR :)

**Comment by kzaher** [comment]
Sure, go for it.

**Comment by MortyMerr** [comment]
https://github.com/RxSwiftCommunity/RxDataSources/pull/319
