### ISSUE TITLE
Animation of changes doing wrong

### ISSUE THREAD

**Issue by forsoff** [RxSwiftCommunity/RxDataSources#325]
First of all, thank you so much for your work.

I am using RxCollectionViewSectionedAnimatedDataSource for my collection view and encountering an issue with animation of changes in datasource. When items added to the datasource, it animates. But when it comes to removing items from the datasource, it does it without animation. I have watched into sources and put breakpoints. Breakpoints worked only on insertion. What I am doing wrong? I am enclosing a gif with the animation.

![Screen Recording 2019-06-24 at 10 22 12](https://user-images.githubusercontent.com/11006935/59991680-27cda880-966a-11e9-9118-e62f0ee40571.gif)

**Comment by teodorpenkov** [comment]
Your cell identifier should be unique in order Differentiator (the engine behind rxdarasources) to do its magic.
Post your section model so I can be more helpful.

**Comment by alisherski** [comment]
@teodorpenkov I get invalidInitializerImplementation error in Differentiator. However, I can't understand why I'm getting this error. Ids are unique and forward transition is doing good.

**Comment by forsoff** [comment]
@teodorpenkov Differentiator gets invalidInitializerImplementation error. I can't understand because forward transition is doing ok and ids are unique.

**Comment by forsoff** [comment]
@teodorpenkov Here's the extended output of error:

▿ **Wrong initializer implementation for:** card(id: 2, headerTitle: "Items", items: [
SectionItem.movie(item: CellModel(id: "148277889", image: <UIImage: 0x60c0002a3420> size {45, 45} orientation 0 scale 2.000000, isHidden: false)),

SectionItem.movie(item: CellModel(id: "151184716", image: <UIImage: 0x60c0002a4860> size {45, 45} orientation 0 scale 2.000000, isHidden: false)), 

SectionItem.movie(item: CellModel(id: "151500434", image: <UIImage: 0x60c0002a5e20> size {45, 45} orientation 0 scale 2.000000, isHidden: false)), 

SectionItem.movie(item: CellModel(id: "153050759", image: <UIImage: 0x60c0002a6480> size {45, 45} orientation 0 scale 2.000000, isHidden: true)), 

SectionItem.movie(item: CellModel(id: "153485155", image: <UIImage: 0x60c0002a6cc0> size {45, 45} orientation 0 scale 2.000000, isHidden: true))])

**Expected it should return items:** 
[SectionItem.movie(item: CellModel(id: "148277889", image: <UIImage: 0x6000004b83c0> size {45, 45} orientation 0 scale 2.000000, isHidden: false)), 

SectionItem.movie(item: CellModel(id: "151184716", image: <UIImage: 0x6000004b8b40> size {45, 45} orientation 0 scale 2.000000, isHidden: false)), 

SectionItem.movie(item: CellModel(id: "151500434" , image: <UIImage: 0x6000004b9140> size {45, 45} orientation 0 scale 2.000000, isHidden: false))]

**Expected it should have id: 2**

**Comment by forsoff** [comment]
Problem solved. Error was in initializer.
 I used items from my enum type .movie(let id, let title, let items):
**But I should use items from init** 
init(original: AccountSection, items: [Item])
