### ISSUE TITLE
Crash with RxCollectionViewSectionedReloadDataSource when long press on cell

### ISSUE THREAD

**Issue by damienrambout** [RxSwiftCommunity/RxDataSources#33]
A crash occurs when a long press is performed on a cell, when using a `RxCollectionViewSectionedReloadDataSource`. 
Apparently, the data source proxy does not implement the `collectionView(_:,canMoveItemAtIndexPath:)` data source function introduced in iOS 9 to allow cell reordering.

**Comment by kzaher** [comment]
Fix for this has just been released :) Hope it works for you :)

**Comment by kzaher** [comment]
If latest release hasn't solved this, please let me know, and we'll reopen the issue.
