### ISSUE TITLE
TableViewCell blinks when an item change

### ISSUE THREAD

**Issue by bigearsenal** [RxSwiftCommunity/RxDataSources#346]
I'm using RxTableViewSectionedAnimatedDataSource for binding my items to tableview.
Everything works well, except the moment when I changed item which is associated with cell, the Cell blinks a little bit.
Here is the binding code
```
dataSource = MyRxTableViewSectionedAnimatedDataSource<ListSection>(
            configureCell: { dataSource, tableView, indexPath, item in
                let cell = self.configureCell(with: item, indexPath: indexPath)
                return cell
            }
        )

viewModel.items
            .map {[ListSection(model: "", items: $0)]}
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
```
The code to update item
```
func updateItem(_ updatedItem: T) {
        var newItems = items.value
        guard let index = newItems.firstIndex(where: {$0.identity == updatedItem.identity}) else {return}
        newItems[index] = updatedItem
        UIView.performWithoutAnimation {
            self.items.accept(newItems)
        }
    }
```
The resullt: (Unwanted result is the blinking of the cell (not just imageView or avatar)
![123123](https://user-images.githubusercontent.com/6975538/70135416-9ce2e680-16bc-11ea-9a14-3af71a3c5641.gif)
Any suggestion? Thank a lot )

**Comment by shengyang998** [comment]
Did you reload rows at index path with animation? you should disable the animation

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bigearsenal** [comment]
I figured it out, just set the reload animation in AnimationConfiguration to .none.
Thanks any way :)
