### ISSUE TITLE
configureSupplementaryView not called with Custom UICollectionViewLayout

### ISSUE THREAD

**Issue by robelsh** [RxSwiftCommunity/RxDataSources#354]
Hello, I try to define a `RxCollectionViewSectionedReloadDataSource` with a Footer. But if I use a Custom `UICollectionViewLayout`, `configureSupplementaryView` is not called. 

I try to override delegate from `UICollectionViewDelegateFLowLayout` but it doesn't works. 

I set `footerReferenceSize` but it doesn't work too.

**Comment by pablogeek** [comment]
This is also happening to me, any solution?

**Comment by trongnhan68** [comment]
throw your code here, may be some one can support you.

**Comment by tsomaev** [comment]
@robelsh you will need simple set the headerReferenceSize for your custom layout
