### ISSUE TITLE
Leading & Trailing Swipe Delegate not Working

### ISSUE THREAD

**Issue by simonzwicker** [RxSwiftCommunity/RxDataSources#359]
Hey guys have the problem that the leadingSwipe and trailingSwipe Delegate not working on my case maybe I am missing something. Hope someone can help me :) 

`override open func bindData() {

		super.bindData()

		subView.dataSource.canEditRowAtIndexPath = { _, _  in
			return true
		}

		configViewModel?.dataSource
			.bind(to: subView.tableView.rx.items(dataSource: subView.dataSource))
			.disposed(by: bag)

		depotViewModel.showLogin
			.asObservable()
			.subscribe(onNext: { [weak self] (state) in

				guard let self = self else { return }
				self.subView.tableView.tableFooterView = state ? self.loginView: UIView()
				self.subView.tableView.sizeFooterToFit()
				self.navigationItem.rightBarButtonItem = !state ? self.rightBarButtonItem: nil
			})
			.disposed(by: bag)
	}

	open override func viewWillDisappear(_ animated: Bool) {

		if let tabBar = tabBarController as? UITabBarControllerMain {

			tabBar.closeHint()
		}
	}

	public func tableView(_ tableView: UITableView, leadingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
		let closeAction = UIContextualAction(style: .normal, title:  "Close", handler: { (ac:UIContextualAction, view:UIView, success:(Bool) -> Void) in
			print("OK, marked as Closed")
			success(true)
		})
		closeAction.backgroundColor = .purple

		return UISwipeActionsConfiguration(actions: [closeAction])
	}

	public func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
		let modifyAction = UIContextualAction(style: .normal, title:  "Update", handler: { (ac:UIContextualAction, view:UIView, success:(Bool) -> Void) in
			print("Update action ...")
			success(true)
		})
		modifyAction.backgroundColor = .blue
		return UISwipeActionsConfiguration(actions: [modifyAction])
	}`

**Comment by haydarKarkin** [comment]
You should set delegate:

`tableView.rx.setDelegate(self)
            .disposed(by: rx.disposeBag)`

Also, don't forget extend `UITableViewDelegate` for your UIViewController

**Comment by PatrickKaalund** [comment]
Seems like I got the same issue as @simonzwicker , and @haydarKarkin I already tried setting the delegate as you describe:

https://stackoverflow.com/questions/63776621/rxswift-tableview-with-swipe-actions

Did someone manage to fix this issue?

**Comment by haydarKarkin** [comment]
Hi @PatrickKaalund,
Could you please share your all code in your ViewController at here or StackOverflow?

**Comment by PatrickKaalund** [comment]
@haydarKarkin

I found the issue. 

Adding this method, fixed the swipe actions: 

dataSource.canEditRowAtIndexPath = { datasource, index -> Bool in 
     return true 
}

**Comment by forceunwrap** [comment]
@PatrickKaalund 
Thanks for pointing that out. I think that's not the responsibility of the one implementing swipe actions though, as this is different from iOS default behavior. Created an issue to fix that.

**Comment by simonzwicker** [comment]
Danke Gordy :D Gruß an de reschd :D
