### ISSUE TITLE
Use MultipleSectionModel example with RxCollectionViewSectionedAnimatedDataSource

### ISSUE THREAD

**Issue by serluca** [RxSwiftCommunity/RxDataSources#37]
Hi guys

I'm trying to model my sections and items as enums as implemented in `MultipleSectionModelViewController.swift` in the Example to be able to use the `MultipleSectionModel` with `RxCollectionViewSectionedAnimatedDataSource<MultipleSectionModel>`.

I know that I have to make the `MultipleSectionModel` conforms to `AnimatableSectionModelType` but I'm not having good time with the `associatedtype` defined in `AnimatableSectionModelType`.

In the Example app the `typealias` is defined like this
```
extension MultipleSectionModel: SectionModelType {
    typealias Item = Any
    .....
}
```

My question is how I can implement the same but doing something like:
```
extension MultipleSectionModel: AnimatableSectionModelType {
    typealias Item = Any // Here Any doesn't work because Any is not conform to SectionModelType, IdentifiableType
}
```

Note: I want still be able to use multiple type as the example uses `ImageSectionItem, ToggleableSectionItem, StepperSectionItem`

**Comment by kzaher** [comment]
Hi,

I've just improved our example. Please take a look at MultipleSectionModelViewController.swift. It should be more clear now.

**Comment by serluca** [comment]
Hi @kzaher,

Thanks for getting back to me, that was a smart change, I didn't think about introducing another enums. 

Thank you

**Comment by nmdias** [comment]
I also struggled with this. For future reference, here's an Xcode Template:

```swift
//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//___COPYRIGHT___
//

import Foundation
import RxDataSources

struct ___FILEBASENAMEASIDENTIFIER___ {
    var header: String
    var items: [Item]
}

extension ___FILEBASENAMEASIDENTIFIER___: AnimatableSectionModelType {
    
    typealias Item = <#Model#>
    
    var identity: String {
        return header
    }
    
    init(original: ___FILEBASENAMEASIDENTIFIER___, items: [Item]) {
        self = original
        self.items = items
    }
}

extension <#Model#>: IdentifiableType {
    
    typealias identity = <#Type#>
    
    public var identity: <#Type#> {
        return <#Value#>
    }
    
}
```

### How to:

Close Xcode.

Copy the **Swift File.xctemplate** folder from:
```
/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File Templates/Source
```

To:
```
/Users/user/Library/Developer/Xcode/Custom
```

You'll need to create the **Custom** folder.

Rename `Swift File.xctemplate` to `RxSectionModel.xctemplate`

Open Xcode and go to:
```
 File -> New -> File... -> Custom -> RxSectionModel
```
