### ISSUE TITLE
RxSwift 6.0 Support

### ISSUE THREAD

**Issue by huoda1237** [RxSwiftCommunity/RxDataSources#385]
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In snapshot (Podfile.lock):
    RxSwift (= 6.0.0-rc.2)

  In Podfile:
    RxCocoa (= 6.0.0-rc.2) was resolved to 6.0.0-rc.2, which depends on
      RxSwift (= 6.0.0-rc.2)

    RxDataSources (~> 4.0) was resolved to 4.0.1, which depends on
      RxSwift (~> 5.0)

**Comment by freak4pc** [comment]
I'm hoping to make a new release of RxDataSources once we release RxSwift 6 (soon).

**Comment by freak4pc** [comment]
Part of RxDataSources 5.0.0.
