### ISSUE TITLE
SectionedViewDataSourceType not found

### ISSUE THREAD

**Issue by esttorhe** [RxSwiftCommunity/RxDataSources#4]
So this is how my `Podfile` looks (the part that matters for this):
```ruby
  pod 'RxSwift', '~> 2.0.0'
  pod 'RxCocoa', '~> 2.0.0'
  pod 'RxDataSources', '~> 0.1'
```

And this is my `Podfile.lock`
```lock
  - RxCocoa (2.0.0):
    - RxSwift (~> 2.0)
  - RxDataSources (0.3):
    - RxCocoa (~> 2.0)
    - RxSwift (~> 2.0)
  - RxSwift (2.0.0)
  - RxViewModel (3.0.0):
    - RxCocoa (~> 2.0.0)
    - RxSwift (~> 2.0.0)
```

As you can see i'm using `2.0.0` for  `RxSwift` and `RxCocoa` and `0.3` for `RxDataSources` but I can't compile my project.

I'm targeting `iOS 8.1` and can't compile because `public class CollectionViewSectionedDataSource<S: SectionModelType>` and `public class RxTableViewSectionedDataSource<S: SectionModelType>` can't find `SectionedViewDataSourceType`

<img width="725" alt="screen shot 2016-01-27 at 10 52 29 p m" src="https://cloud.githubusercontent.com/assets/2642850/12635445/e68ba1ec-c548-11e5-9166-d3824109b8f2.png">

===

After checking `RxCocoa` `podspec` and [`RxDataSources`](../blob/master/RxDataSources.podspec) `RxCocoa` `2.1.0` is the one that includes `SectionedViewDataSourceType` and `RxDataSources` `podspec` depends on `2.0.0` making the project impossible to compile at the moment

**Comment by kzaher** [comment]
Shouldn't it be
Podfile
```
pod 'RxSwift', '~> 2.0'
pod 'RxCocoa', '~> 2.0'
```

I've pushed the new version 0.4 :) Thnx for PR

**Comment by sger** [comment]
@kzaher small update to README.md

**Comment by kzaher** [comment]
:+1:

**Comment by esttorhe** [comment]
@kzaher yeah; i was playing around with the `Podfile` and left it with `2.0.0`

Thanks :bow:
