### ISSUE TITLE
[Carthage] IPHONEOS_DEPLOYMENT_TARGET on Xcode project does not match the SPM target.

### ISSUE THREAD

**Issue by ajamaica** [RxSwiftCommunity/RxDataSources#402]
There is a discrepancy on the current IPHONEOS_DEPLOYMENT_TARGET and the supported versions on SPM.

The IPHONEOS_DEPLOYMENT_TARGET is set to 12 which limits the compatibility versus the current RxSwift library. This only happens when using the Xcode Project (like on Carthage and Cocoapods). It might be a simple mistake but if we can match and set the compatibility with RxSwift we can gain a bit by not doing much. 

It can be easily fix by just lowering down the IPHONEOS_DEPLOYMENT_TARGET on the xcode project file (Someone actually attempt fix this #399).

**Comment by ElonPark** [comment]
#399 is merged in main branch!
