### ISSUE TITLE
"Editing Example" tries to add a duplicate item and crashes

### ISSUE THREAD

**Issue by solidcell** [RxSwiftCommunity/RxDataSources#45]
I'm not sure what the preferred solution would be.  Here are a couple ideas that come to mind:

1. Don't try to add a duplicate (keep check of used numbers somehow and go beyond 100 if necessary).
2. Pop up an alert showing the error, instead of fatal erroring.
3. Allow duplicates.
4. Leave it as is. Maybe this is intentional for educational purposes to show what happens with duplicates. I'm not sure, but I didn't see any comments or documentation leading me to believe so.

<img width="680" alt="screen shot 2016-06-15 at 11 23 36 pm" src="https://cloud.githubusercontent.com/assets/309224/16097829/4bafa26a-3350-11e6-8e2e-fe45650e9eea.png">

**Comment by kzaher** [comment]
Hi @solidcell ,

we can turn this from `rxDebugFatalError` to `print` if it concerns you.
