### ISSUE TITLE
 collectionView(_:layout:referenceSizeForHeaderInSection:)

### ISSUE THREAD

**Issue by serluca** [RxSwiftCommunity/RxDataSources#46]
## Description

Would be nice to define `collectionView(_:layout:referenceSizeForHeaderInSection:)` in the same way we define `supplementaryViewFactory` 
## Why

By default `collectionView(_:layout:referenceSizeForHeaderInSection:)` returns (0,0) as described [here](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionViewDelegateFlowLayout_protocol/#//apple_ref/occ/intfm/UICollectionViewDelegateFlowLayout/collectionView:layout:referenceSizeForHeaderInSection:) unless the user either implements the delegate or defines `headerReferenceSize` property of the UICollectionViewFlowLayout [link](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionViewFlowLayout_class/index.html#//apple_ref/occ/instp/UICollectionViewFlowLayout/headerReferenceSize). When the size in the appropriate scrolling dimension is 0, no header is added.
# Issue

I was trying to use a custom header registered using the method `registerNib(_:forSupplementaryViewOfKind:withReuseIdentifier:)` and I couldn't figured out why it was not working. Then, I realised it was the size but to define I had to implement the delegate which is annoying because I use `RxDataSources` for the view and the `UICollectionViewDelegateFlowLayout` for the size of the same view.
In the project `Example2` everything work because the header is defined in the Storyboard inside the collection view, in that case the `UICollectionViewDelegateFlowLayout` inherits the `headerReferenceSize` property, but defining custom header is a common use case

**Comment by kzaher** [comment]
Hi @serluca ,

I'm not sure what is the suggestion here. 

`collectionView(_:layout:referenceSizeForHeaderInSection:)` is part of delegate and not data source, so we can't implement this on data source.

I think that RxDelegate should report `collectionView(_:layout:referenceSizeForHeaderInSection:)` wasn't implemented in case delegate isn't implementing it because it has `void` return type, so little confused it returns (0, 0). Why do you think it does?

What we could theoretically do is for data source to also implement delegate methods, and then create an extension `rx_itemsWithDataSourceAndDelegate`.

**Comment by kzaher** [comment]
Hi @serluca ,

would 

> What we could theoretically do is for data source to also implement delegate methods, and then create an extension rx_itemsWithDataSourceAndDelegate.

even help in this case. According to this, it sounds like not.

**Comment by serluca** [comment]
Hi @kzaher 

What I'm suggesting here is to have a method  that looks like
```
dataSource.supplementaryViewFactory = { (dataSource, collectionView, kind, indexPath) in
}
```

But for the delegate method `collectionView(_:layout:referenceSizeForHeaderInSection:)` something like
```
dataSourceAndDelegate.referenceSizeForHeaderFactory = { { (dataSource, collectionView, section)
}
```

Having this method, we can customize the header size and keep the same syntax that we use for the dataSource.

Right now my code looks like this (and I think is ugly):

```
class MyClass {
	func skinCollectionView() {
		dataSource.supplementaryViewFactory = { (dataSource, collectionView, kind, indexPath) in
			...
		}
	}	
}

extension MyClass : UICollectionViewDelegateFlowLayout {

    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
        ....
        return Size
    }
}
```

**Comment by kzaher** [comment]
Can you make a PR?

**Comment by serluca** [comment]
I'll try :)
