### ISSUE TITLE
Error while reloading sections in RxTableViewSectionedAnimatedDataSource.

### ISSUE THREAD

**Issue by sunshinejr** [RxSwiftCommunity/RxDataSources#47]
## Description
While setting new items to animatable data source, the app will crash due to:

> 2016-06-28 15:39:19.024 myproapp[28226:12219321] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

## Steps to reproduce:
I have animatable data source with 2 sections: 1 section having one item, another section having more than 1 item (about 10).

Change the source to 2 sections: 1 without any items (from 1), and second with the same items as before.

App will crash (well, depends if the steps above all enough for it).

## Temp fix
So I was able to check the code out for a few minutes, and I found a quick fix (dunno if it's anyhow good, just pasting it here, maybe it will help with normal fix).

Basically in [RxTableViewSectionedAnimatedDataSource.swift](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/DataSources%2BRx/RxTableViewSectionedAnimatedDataSource.swift#L40-L50) I changed the lines:
```swift
do {
    let differences = try differencesForSectionedView(oldSections, finalSections: newSections)

    for difference in differences {
        dataSource.setSections(difference.finalSections)

        tableView.performBatchUpdates(difference, animationConfiguration: self.animationConfiguration)
    }
}
```

to:
```swift
do {
    let differences = try differencesForSectionedView(oldSections, finalSections: newSections)

    dataSource.setSections(newSections)
    for difference in differences {
        tableView.performBatchUpdates(difference, animationConfiguration: self.animationConfiguration)
    }
}
```

It seems like it returns wrong `finalSections` from `differences` in my use-case. But I figured that the variable `newSections` should have the proper final sections anyways. I didn't have time to dig more into the code so I filled an issue here.

Cheers! 🐼

**Comment by kzaher** [comment]
Hi @sunshinejr ,

could you maybe try to modify the example app so it reproduces this issue. I can perform further investigations if I have a repo step. As far as I can tell example in RxExample app works ok. 

Was this table view or collection view?

You can maybe use `Example2_RandomizedSectionsAnimation` view controller class.

and something like

```swift
let firstState: [NumberSection] = [
    NumberSection(header: "section 1", numbers: $([1, 2, 3]), updated: NSDate()),
    NumberSection(header: "section 2", numbers: $([4, 5, 6]), updated: NSDate()),
    NumberSection(header: "section 3", numbers: $([7, 8, 9]), updated: NSDate()),
    NumberSection(header: "section 4", numbers: $([10, 11, 12]), updated: NSDate()),
    NumberSection(header: "section 5", numbers: $([13, 14, 15]), updated: NSDate()),
    NumberSection(header: "section 6", numbers: $([16, 17, 18]), updated: NSDate()),
    NumberSection(header: "section 7", numbers: $([19, 20, 21]), updated: NSDate()),
    NumberSection(header: "section 8", numbers: $([22, 23, 24]), updated: NSDate()),
    NumberSection(header: "section 9", numbers: $([25, 26, 27]), updated: NSDate()),
    NumberSection(header: "section 10", numbers: $([28, 29, 30]), updated: NSDate())
]

let secondState: [NumberSection] = [
    NumberSection(header: "section 1", numbers: $([1, 2, 3]), updated: NSDate()),
    NumberSection(header: "section 2", numbers: $([4, 5, 6]), updated: NSDate()),
    NumberSection(header: "section 3", numbers: $([7, 8, 9]), updated: NSDate()),
    NumberSection(header: "section 4", numbers: $([10, 11, 12]), updated: NSDate()),
    NumberSection(header: "section 5", numbers: $([13, 14, 15]), updated: NSDate()),
    NumberSection(header: "section 6", numbers: $([16, 17, 18]), updated: NSDate()),
    NumberSection(header: "section 7", numbers: $([19, 20, 21]), updated: NSDate()),
    NumberSection(header: "section 8", numbers: $([22, 23, 24]), updated: NSDate()),
    NumberSection(header: "section 9", numbers: $([25, 26, 27]), updated: NSDate()),
    NumberSection(header: "section 10", numbers: $([28, 29, 30]), updated: NSDate())
]

let randomSections = Observable.of(firstState, secondState)
```

to specify the transition.

**Comment by sunshinejr** [comment]
Hey @kzaher, thanks so much for quick response! 

Okay, so here more info about the bug:
1. It was using `UITableView`.
2. It was using MultipleSectionModel-ish style (like in example 4).
3. I was able to reproduce the bug in the example, [here](https://github.com/sunshinejr/RxDataSources/blob/master/Example/Example4_DifferentSectionAndItemTypes.swift).

I hope it helps!

**Comment by kzaher** [comment]
Hey,

I've figured it out. It's not a problem in RxDataSources. Initializer was implemented wrong.

```
 init(original: MultipleSectionModel, items: [Item]) {
        self = original
    }
```

items were ignored.

I've added additional safeguards to check has somebody implemented initializer wrong ;)

https://github.com/RxSwiftCommunity/RxDataSources/commit/7d292f9882f105e568cebd92de3e3f5c8d0671e1

If you now try to run your example, the error should be clearer.

**Comment by sunshinejr** [comment]
Thank you so much for the help, I really appreciate that @kzaher 🙌 One thing to notice is that I mindlessly (and it's my bad) copied the init code from the [example](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example4_DifferentSectionAndItemTypes.swift#L98-L100), so might be worth fixing that too in the example app.

Thanks again! 🐼

**Comment by kzaher** [comment]
Fixed, thnx 👍

**Comment by CoderAndCat** [comment]
the same problem in Object-C ,how to solve
