### ISSUE TITLE
Duplicate binding messages when using rx_itemsWithDataSource + configureCell

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxDataSources#50]
I have the following code:

viewModel.tableViewSections.bindTo(tableView.rx_itemsWithDataSource

....

viewModel.tableViewDataSource.configureCell = { 

...

This is working in previous release but now throwing assert, what is the proper way of doing this?

**Comment by kzaher** [comment]
Hi @grangej ,

just reverse those two lines.

**Comment by jingfei05** [comment]
Is there anyway to bind multiple data sources? 
Or is there anyway avoid return cell in certain conditions?

**Comment by kzaher** [comment]
Hi @jingfei05 ,

maybe this was what you were looking for.

https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Example/Example4_DifferentSectionAndItemTypes.swift
