### ISSUE TITLE
Provide simpler examples

### ISSUE THREAD

**Issue by mwawrusch** [RxSwiftCommunity/RxDataSources#51]
Hi guys, thanks for the great work. To make this easier to understand and to widen the audience simpler examples would be awesome. 

Even for someone who is used to RX extensions from the Microsoft world and Angular2 it's still very hard to get this implemented, in particular when under time pressure. I am sure that a lot of less experienced developers just give up which is a pity.

Perhaps start with the most basic UITableViewController and UICollectionViewController implementation and work your way upwards.

**Comment by kzaher** [comment]
Hi @mwawrusch ,

thnx for kind words. I agree with your claims. I guess we've tried to add simple examples in example app in this repository, example app in RxSwift repository and inline documentation of data source methods.

We are open to PRs, so if you have any ideas how to present this in a simper, more approachable or more elegant way feel free to open one.

**Comment by mwawrusch** [comment]
Unfortunately I can't donate any time for this. Speaking of RxSwift in general I feel like the biggest problem is that it is all over the place - there are some good blog posts etc. I feel like there should be a site like angular.io, which obviously is a huge and sponsored undertaking.

**Comment by kzaher** [comment]
¯\\\_(ツ)\_/¯ 

Hope we'll get there some day.
