### ISSUE TITLE
CocoaPods specific build steps

### ISSUE THREAD

**Issue by mark-urbanthings** [RxSwiftCommunity/RxDataSources#58]
0.9 appears to introduce two CocoaPods specific custom build steps. This causes the build to fail if you didn't use CocoaPods to obtain it. Not everyone uses CocoaPods so what is the purpose and can it be made conditional so not to affect those not installing in their project via CocoaPods?

**Comment by kzaher** [comment]
Hi @mark-urbanthings ,

I'm not sure what are you exactly suggesting the problem is.

Adding RxDataSources as a dependency using Carthage is supported, at least I would conclude that from my tests. Are you saying that adding this repo as a Carthage dependency doesn't work?

There is only one Example app, and yes, that it uses CocoaPods. Are you complaining about that?

**Comment by mark-urbanthings** [comment]
Hi

I hit a problem that building a complex project that included RxDataSources (amongst many others) was giving errors as due to it trying to run the scripts. I did the following:

Created a new clone of project which pulled out head of RxDataSources
This caused build failures (I’m still running with release Xcode so no Swift 3 support)
Reverted to 0.9
Now got the CocoaPod scripts errors
Reverted to 0.8.1
My project built :-)
I posted the issue…

Subsequently I started getting same problems with another clone of the project which has been on 0.8.1 (it was started a few months ago and not pulled 3rd party to update)
After much hair pulling, clearing Xcode project build areas, and restarting Xcode my old project also built
I was then able to move to 0.9 and still build
So although I have no idea why seems Xcode got itself into a mess with dependencies and was (I think) getting the errors from the demo even though I don’t have a dependency on that…

Anyway I think its a non-issue from your side, not got around to updating the issue on github and am happy for this to be closed.

Regards
Mark

**Comment by kzaher** [comment]
:)
