### ISSUE TITLE
README is out of date and inconsistant w.r.t. rx_items()

### ISSUE THREAD

**Issue by augustjd** [RxSwiftCommunity/RxDataSources#59]
The README still has lots of passages that refer to functions like`rx_items(dataSource:protocol<RxTableViewDataSourceType, UITableViewDataSource>)`, which is now `rx_itemsWithDataSource(dataSource:protocol<RxTableViewDataSourceType, UITableViewDataSource>)`. Several of the code snippets also reference `.rx.items()`, which is also no longer correct.

The README needs to be updated - each code snippet should be copy-pastable and should work without further modifications.

**Comment by kzaher** [comment]
Hi @augustjd ,

I think it should be fine now, please let me know if you find some additional errors.
