### ISSUE TITLE
Is the minimum deploy target version way too high?

### ISSUE THREAD

**Issue by JoeHetfield** [RxSwiftCommunity/RxDataSources#6]
Hi, I'm doing a app targets iOS 8.3, after I add RxDataSource with carthage and import it, it's said the minimum deploy target version is 9.0.

I don't know the reason RxDataSource was set like this. but in this way, you may lost huge mount of uses. 

Is that possible to make the minimum deploy target version lower like 8.0 or 7.0?

and, I really want to use RxDataSource by carthage, any work around of this problem?

thanks.

**Comment by orta** [comment]
Sure, submit a PR fixing it, I think 8.0 should be fine :+1:

**Comment by esttorhe** [comment]
The deploy target for `iOS` is `8.0` => https://github.com/RxSwiftCommunity/RxDataSources/blob/master/RxDataSources.podspec#L38

I'm going to close this issue based on that and in case there's a need to lower it to `7.0` just submit another `PR` and we can merge it :tada:
