### ISSUE TITLE
 Proposal for: Index out of range exception

### ISSUE THREAD

**Issue by serluca** [RxSwiftCommunity/RxDataSources#65]
## Description
Using the method `func model(_ indexPath: IndexPath) throws -> Any` of `CollectionViewSectionedDataSource` I received few crash reports because of `Index out of range`. 
The description of the method says:
>Returns model at index path. In case data source doesn’t contain any sections when this method is being called, RxCocoaError.ItemsNotYetBound(object: self) is thrown.

I was wondering if the library can help also with the out of range error.

**Comment by kzaher** [comment]
Hi @serluca ,

I think it's consistent with Swift to have index out of range errors be fatal. You can always create your own convenience wrapper if you like.

**Comment by serluca** [comment]
HI @kzaher 

Thanks for getting back to me, you are right, it's better to keep the library consistent with Swift
