### ISSUE TITLE
viewForHeaderInSection not working properly

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxDataSources#66]
import RxSwift
    import RxCocoa
    import RxDataSources

    class ViewController: UIViewController, UITableViewDelegate {

        @IBOutlet weak var tableView: UITableView!
  
        let dataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, Double>>()
        let disposeBag = DisposeBag()
  
        override func viewDidLoad() {
          super.viewDidLoad()
    
          dataSource.configureCell = { (ds, tv, indexPath, element) in
            let cell = tv.dequeueReusableCell(withIdentifier: "Cell")!
            cell.textLabel?.text = "\(element) @ row \(indexPath.row)"
            return cell
          }
    
          let items = Observable.just([
            SectionModel(model: "First section", items: [ 1.0, 2.0, 3.0 ]),
            SectionModel(model: "Second section", items: [ 1.0, 2.0, 3.0 ]),
            SectionModel(model: "Third section", items: [ 1.0, 2.0, 3.0 ])
          ])
    
          items
            .bindTo(tableView.rx.items(dataSource: dataSource))
            .addDisposableTo(disposeBag)
  
          tableView.rx
            .setDelegate(self)
            .addDisposableTo(disposeBag)
        }
  
        func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
          print("\(tableView.numberOfSections) - \(section)")
    
          let label = UILabel(frame: CGRect.zero)
          label.text = dataSource.sectionAtIndex(section).model
          return label
        }
      }

The outputs I get:
3 - 1
3 - 2

It looks as if the first section is being ignored. This is also reflected in the tableView as the first header is empty

**Comment by kzaher** [comment]
Hi @plm75 ,

I think you need to reverse these lines
```
tableView.rx
        .setDelegate(self)
        .addDisposableTo(disposeBag)

items
        .bindTo(tableView.rx.items(dataSource: dataSource))
        .addDisposableTo(disposeBag)
```

**Comment by plm75** [comment]
@kzaher 
Unfortunately, that doesn't fix it: same output in the console and first header is still empty.

ps: the code is lifted directly from the example "simple tableView sectioned" where items are also bound to the tableView before the delegate is set

**Comment by kzaher** [comment]
Sorry, can't repro

https://github.com/RxSwiftCommunity/RxDataSources/commit/cfcf6a96550b1f634b9278f9e4165b209f58c1c7

**Comment by DansWorld** [comment]
I had to include tableView:heightForHeaderInSection: method

**Comment by Sadmansamee** [comment]
but for tableView:heightForHeaderInSection isn't getting called!
