### ISSUE TITLE
dyld: Library not loaded: @rpath/RxDataSources.framework/RxDataSources when run the app

### ISSUE THREAD

**Issue by Linfz** [RxSwiftCommunity/RxDataSources#71]
I install RxDataSource with cocoapod, after pod install successfully, my app crash and show the error message when I run it like follows:
```
dyld: Library not loaded: @rpath/RxDataSources.framework/RxDataSources
  Referenced from: /Users/feilang001/Library/Developer/CoreSimulator/Devices/F6C9FC56-F6A5-4F24-8180-E724D7F76EF1/data/Containers/Bundle/Application/ECEA79C2-336D-4560-B3E3-1304E4CA5358/ProcessControl.app/ProcessControl
  Reason: image not found
```
I found solution on stackoverflow that add the dynamic framework to the Embedded binaries section in the General tab of the project. But anyone else who works in my team must do this again at first,is there some other better ways to solve this?

**Comment by kzaher** [comment]
Hi @Linfz ,

only one team member needs to add this to Embedded binaries. This is more of a Carthage question.

**Comment by Linfz** [comment]
@kzaher 
Thanks for your response. I'll try it, the problem may be my own cause.
