### ISSUE TITLE
I want an idea to use with AsyncDisplayKit

### ISSUE THREAD

**Issue by muukii** [RxSwiftCommunity/RxDataSources#74]
RxDataSources is a very nice library.
Thank you.
I'd like to implement this function also in ASCollectionNode of AsyncDisplayKit.
However, since RxDataSources depends on the DelegateProxy of RxCocoa,
Since some methods are Internal, it is difficult to implement "ASCollectionNode + Rx".
Is there any good idea?

[AsyncDisplayKit](https://github.com/facebook/AsyncDisplayKit)
[ASCollectionNode](https://github.com/facebook/AsyncDisplayKit/blob/a6e2f8e5ab06804ae3bb69e3455e1ee03e8304cc/AsyncDisplayKit/ASCollectionNode.h)

If I can realize it will be published in the following repository
https://github.com/muukii/RxAsyncDataSources

**Comment by kzaher** [comment]
Hi @muukii ,

I haven't worked with ASCollectionNode but I think that all you need is diffing algoritm.

Everything in https://github.com/RxSwiftCommunity/RxDataSources/tree/master/Sources/DataSources folder is Rx agnostic.

Only a small part in
https://github.com/RxSwiftCommunity/RxDataSources/tree/master/Sources/DataSources+Rx depends on RxCocoa.

I think it shouldn't be too hard to just take the algorithm and apply it.

On the other hand, I didn't ever work with ASCollectionNode so might be wrong. Maybe it handles batch updates differently.

¯\\\_(ツ)\_/¯

**Comment by muukii** [comment]
@kzaher 

Thank you for the idea.
I will consider ways to use the diffing algorithm.
