### ISSUE TITLE
Handle updates to items? 

### ISSUE THREAD

**Issue by Nemesisprime** [RxSwiftCommunity/RxDataSources#77]
I have a list of items and a view controller to edit their titles. When I modify the information, the event is passed to RxTableViewSectionedAnimatedDataSource but the differencesForSectionedView doesn't return any differences, so no cells get updated. 

As I look a little deeper, I can't find any functionality related to checking item properties for differences. Is this correct?

**Comment by kzaher** [comment]
Hi @Nemesisprime ,

what do you mean? Your items need to implement `Equatable` and `IdentifiableType` for animations to work.

If you would like for updates to work, then you need to check how item equality is implemented.

**Comment by Nemesisprime** [comment]
How embarrassing. I had implemented `Equatable` partially and when I attempted to fix it, I updated the wrong object. My bad! 
Thanks, my friend!
