### ISSUE TITLE
RxAnimatedDataSource crash on performBatchUpdates (line 0)

### ISSUE THREAD

**Issue by alexbredy** [RxSwiftCommunity/RxDataSources#80]
Hello,

I've got a small amount of crashes on Fabric that seem to be triggered sometimes when calling the performBatchUpdates method.

The error displayed is the following:
`UITableView internal bug: unable to generate a new section map with old section count: 2 and new section count: 0`

I am initialising the View Controller with 2 sections (0 cells until the data is loaded from the server) and never remove them. I only replace them by an updated version in my handler method, which returns a new set of 2 sections.

Any ideas are much appreciated! Thanks.

**Comment by alexbredy** [comment]
The issue was related to the table view's data source not being set (RxCocoa.swift data source not set fatal error). Once I fixed that this crash disappeared.

**Comment by YanisSOTO** [comment]
Hello, i've the same problem and i can't fix it... This crash appears randomly when i load for the first time a collectionView. Any idea ? I think it's a problem of section.
