### ISSUE TITLE
make dataSet variable in RxCollectionViewSectionedAnimatedDataSource Public?

### ISSUE THREAD

**Issue by lingzlu** [RxSwiftCommunity/RxDataSources#82]
I need to reset dataSet variable in RxCollectionViewSectionedAnimatedDataSource to false so my collection view will perform a reload instead of partial update. Currently, it's default to internal. Alternatively, is there a work around to reload the collection view using AnimatableSectionModelType?

**Comment by kzaher** [comment]
Hi @lingzlu ,

I think we can think about how to incorporate this feature best in 2.0 version.

So far you can either, create your own data source or remove the binding and rebind the data source (this will cause reload).

**Comment by lingzlu** [comment]
Hi kzaher, thanks for your response. I did solve the issue by subclass RxCollectionViewSectionedAnimatedDataSource and added a variable called forceReload, which change dataSet to false when true, then immediately default back to false. 

I'm thinking that we can simply rename the variable 'dataSet' to 'shouldReload' with public accessor, default to true, after initial load, change to false as designed. This grant the user control of reload the list when needed and doesn't change the original behavior of AnimatedDataSource. 

For the example of use case, I have a 'filter' option, when applied, it would slightly change the view of cells, the problem is that when some of previous list items are also part of new filtered list, partial update only re-render the differences.

**Comment by lingzlu** [comment]
Closing it as this is probably not applicable to most users. Reset the disposeBag will reload the data source
