### ISSUE TITLE
When Using Animated data sources, configure cell is not called on a cell move

### ISSUE THREAD

**Issue by kingmatusevich** [RxSwiftCommunity/RxDataSources#86]
Example: I have a simple todo app. When I tap a task cell, the cell get's marked as completed in the model, and that percolates all the way up to the section, and then datasource. The cell moves appropiately. However, configure cell is not recalled, meaning the cell doesn't display the UI traits for complete tasks. If you scroll away and rescroll, such that the tableview needs to re trigger those methods, it shows the correct UI traits.

**Comment by kzaher** [comment]
Hi @kingmatusevich ,

I've added this unit test

```
func testItemUpdatedAndMoved() {
        let initial: [s] = [
            s(1, [
                i(0, ""),
                i(1, ""),
                i(2, ""),
                ])
        ]

        let final: [s] = [
            s(1, [
                i(1, "u"),
                i(0, ""),
                i(2, ""),
                ])
        ]

        let differences = try! differencesForSectionedView(initialSections: initial, finalSections: final)

        XCTAssertTrue(differences.count == 2)

        // updates ok
        XCTAssertTrue(differences[0].onlyContains(updatedItems: 1))
        XCTAssertTrue(differences[0].updatedItems[0] == ItemPath(sectionIndex: 0, itemIndex: 1))

        // moves ok
        XCTAssertTrue(differences[1].onlyContains(movedItems: 1))

        XCTAssertEqual(initial.apply(differences), final)
    }
```

and it passes.

Are you sure you've implemented equality correctly? It seems to me this should be working.

**Comment by Alveng** [comment]
> Example: I have a simple todo app. When I tap a task cell, the cell get's marked as completed in the model, and that percolates all the way up to the section, and then datasource. The cell moves appropiately. However, configure cell is not recalled, meaning the cell doesn't display the UI traits for complete tasks. If you scroll away and rescroll, such that the tableview needs to re trigger those methods, it shows the correct UI traits.

Did you found mistakes? I have same problem

**Comment by mkko** [comment]
@Alveng, just curious, how does your item look like?

**Comment by Alveng** [comment]
`struct TaskModel {
    
    var id: String = ""
    var taskName: TaskName? = nil
    var taskState: TaskState? = nil
    
    var isClosed: Bool {
        return taskState?.type == .closed
    }
    
    // other fields
}

extension TaskModel: IdentifiableType {
    
    var identity: String { return id }
}

extension TaskModel: Equatable {
    
    static func == (lhs: TaskModel, rhs: TaskModel) -> Bool {
        return lhs.id == rhs.id && lhs.isClosed == rhs.isClosed
    }
}

struct Section<T> where T: IdentifiableType, T: Equatable {
    
    var header: String
    var items: [Item]
    
    init(title: String, items: [Item]) {
        self.header = title
        self.items = items
    }
}

extension Section: AnimatableSectionModelType {
    typealias Item = T
    
    var identity : String { return header }
    
    init(original: Section, items: [Item]) {
        self = original
        self.items = items
    }
}

final class TasksVC: UIViewController {
    
    private lazy var dataSource: RxTableViewSectionedAnimatedDataSource<TaskSection> = {
        return RxTableViewSectionedAnimatedDataSource<TaskSection>(
            animationConfiguration: AnimationConfiguration.fadeInset,
            configureCell: { _, tv, ip, item in
                let cell: TaskTableViewCell = tv.dequeue(for: ip)
                cell.set(item)
                return cell
        }, canEditRowAtIndexPath: { _,_ in true })
    }()
    
    func bind(reactor: TasksReactor) {
        reactor.state
            .map { $0.sections }
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
        
        tableView.rx.itemSelected
            .subscribe({ [weak self] indexPath in
                self?.fireAction(.selectItem(indexPath.element!))
            }).disposed(by: disposeBag)
    }
}

extension TasksVC: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, leadingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
        guard indexPath.section == 0
            && vm.currentState.hasCurrentTasks else { return UISwipeActionsConfiguration(actions: []) }
        
        let close = UIContextualAction(style: .normal, title: nil) { [weak self] (_, _, completionHandler) in
            self?.fireAction(.doneItem(indexPath))
            completionHandler(false)
        }
        close.backgroundColor = .indigo
        close.image = #imageLiteral(resourceName: "Tick.pdf")
        
        let swipeActionConfig = UISwipeActionsConfiguration(actions: [close])
        return swipeActionConfig
    }
    
    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
        guard indexPath.section == 1
            || !vm.currentState.hasCurrentTasks && indexPath.section == 0 else { return UISwipeActionsConfiguration(actions: []) }
        
        let undone = UIContextualAction(style: .normal, title: nil) { [weak self] (_, _, completionHandler) in
            self?.fireAction(.undoneItem(indexPath))
            completionHandler(false)
        }
        undone.backgroundColor = .frenchGray
        undone.image = #imageLiteral(resourceName: "undone.pdf")
        
        let swipeActionConfig = UISwipeActionsConfiguration(actions: [undone])
        return swipeActionConfig
    }
}`
My table contains 2 section: done and undone items. Cells can be swiped and moved to another section. CellDidSelect works before moving. But after several swipes, I can't select any cell. Only after moving all cell to one section called 'configureCell' in dataSource.

**Comment by Alveng** [comment]
> @Alveng, just curious, how does your item look like?

Can you help me?

**Comment by mkko** [comment]
@Alveng Sorry for the delay. I don't see any explicit issues in your code. If the issue still remains, I could look at the project if you're willing to provide some full working example.
