### ISSUE TITLE
How to observe changes in data source to scroll to position

### ISSUE THREAD

**Issue by jochenschoellig** [RxSwiftCommunity/RxDataSources#89]
Hi,

my name is Jochen and I'm new to Rx and RxDataSources in general. My goal is to have UICollectionView as a Chat with messages like in the standard iOS Messages App.

I have a working binding between my model and the collection view using `RxCollectionViewSectionedAnimatedDataSource`.

**The issue I have:**
I would like to scroll to the last message if there is new one. As it is code of the view I would like to observe an insertion event to call `scrollToItemAtIndexPath`. Maybe I'm blind or don't know what to observe but till now I didn't find a solution in RxDataSources or in the rx-ified Collection view.

Thanks for your help!

Kind regards,
Jochen

**Comment by kzaher** [comment]
Hi @jochenschoellig ,

the usual way how that's being handled is to set transformation on your table view to `scale(1, -1)` to invert it vertically and also to set transformation `scale(1, -1)` on each cell.

Doing that + reversing ordering of your data source should give you what you want (vertically inverted table view appropriate for chat).

**Comment by jochenschoellig** [comment]
Hi @kzaher,

thank you for your comment. I have done this already but there is still the problem when the view is not scrolled to the last message. For example if the user is reading some old messages and there is a new one incoming then I would like to scroll to the new message.

Maybe there is no visible way to do it?

The only way in my mind is to observe `onNext` before the binding with RxDataSource and scroll if there is a new message!?

Would be great to hear your opinion!

Kind regards,
Jochen

**Comment by kzaher** [comment]
I wouldn't suggest interrupting user intention to browse history from purely UX standpoint.

It would be better to just add some kind of banner (you have new message) or do something similar.

If you want to do that, you can use the same observable sequence, debounce for animation duration and then scroll to bottom.

**Comment by jochenschoellig** [comment]
Hello @kzaher,

I know what you mean, but i wanted to implement some kind of "Lazy Loading" WhatsApp have. Therefore I wrote now my own collection view layout which is completely working with RxDataSources.

You can find it here:
https://gist.github.com/jochenschoellig/04ffb26d38ae305fa81aeb711d043068

I hope it helps others, too!

Kind regards,
Jochen

**Comment by kzaher** [comment]
Hi @jochenschoellig ,

I'm glad you've managed to work it out :)
