### ISSUE TITLE
Unable to provide a custom UITableView header view when using RxDataSources

### ISSUE THREAD

**Issue by anhar** [RxSwiftCommunity/RxDataSources#91]
I have an issue with providing a custom header view when using RxDataSources.
Please bare with me as I am just getting started using RxSwift/RxCocoa and RxDataSources.

I have a gist with example code over here: https://gist.github.com/anhar/f8faeaf9b53c5cb52e2f251c9c7fa73b

The standard way of providing a title for your section works just fine:
```
dataSource.titleForHeaderInSection = { ds, index in
    return ds.sectionModels[index].header
}
```

However when combining this with a custom UILabel makes the method above not working:
```
func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
       let label = UILabel(frame: CGRect.zero)
       label.textColor = UIColor.white
       label.backgroundColor = UIColor.purple
       return label
   }
```

I have scanned through the documentation, and I have not found a `RxTableViewSectionedReloadDataSource` method that does something similar to `configureCell = { ds, tv, ip, item in }` for UITableView header views

**Comment by anhar** [comment]
I solved this issue by using this delegate method instead:
```
func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
    view.tintColor = UIColor.purple
    let header:UITableViewHeaderFooterView = view as! UITableViewHeaderFooterView
    header.textLabel?.textColor = UIColor.white	
}
```

Sorry for the inconvenience.

**Comment by benrudhart** [comment]
Hi there,
this solution is working if one simply wants to style the label. however it's not when one needs more customisation and really needs a `UITableViewHeaderFooterView` subclass.
Any ideas how to achieve this?

**Comment by eviathan** [comment]
This shouldnt really have been closed

**Comment by Sadmansamee** [comment]
@anhar but `willDisplayHeaderView` in here it doesn't get called at all!

**Comment by knight2010** [comment]
> @anhar but `willDisplayHeaderView` in here it doesn't get called at all!

you may try to `table.rx.setDelegate(self).disposed(by:disposedBag)`
