### ISSUE TITLE
TableView is not updated when window == nil

### ISSUE THREAD

**Issue by fjcaetano** [RxSwiftCommunity/RxDataSources#94]
The commit 2100c83e9b4fe6675a7ca3c50a5e6bf5f1923b7b introduced a bug in our app. 

We have a view controller with a table view and, on top of it, we present a search controller that inserts elements that are captured by the view controller beneath it.

The issue happens because when the table view's window is nil `reloadData` is called without updating the models storage.

I was able to make it work properly using this code inside the `do-catch` block, however it's not tested:
```
let differences = try differencesForSectionedView(initialSections: oldSections, finalSections: newSections)

for difference in differences {
    dataSource.setSections(difference.finalSections)
    
    // if view is not in view hierarchy, performing batch updates will crash the app
    if tableView.window != nil {
        tableView.performBatchUpdates(difference, animationConfiguration: self.animationConfiguration)
    }
}

if tableView.window == nil {
    tableView.reloadData()
}
```

If this could be confirmed as an issue, I can work on a pull request to fix this. I believe the issue can be easily reproduced, and consequently tested, by using a table view that's not added to any views, but don't take my word on this.

**Comment by pschneider** [comment]
Hi @fjcaetano 

Seems like you issue should've been solved with #84 too. As I mentioned in the comment we don't get the change even with cocoapods installing 1.0.2.

I added the changes manually to the file and it works for us. It's unclear for me why cocoapods installs 1.0.2 without containing the changes.

**Comment by fjcaetano** [comment]
Yes, my bad, this is a duplicate of that issue and it seems to have been fixed on the latest commits. What you said won't work, because Cocoapods will fetch the tag 1.0.2 and the commit was done later so, you can either tell in your Podfile, for Cocoapods to look at the fix commit specifically or wait for an update to be released.

```
pod 'RxDataSources', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :commit => '17fdc86fded785891f1d47be0261ec099e4e73ab' # Remove this when a version higher than 1.0.2 is released
```

This actually is in our Podfile

**Comment by pschneider** [comment]
Ah, makes sense. Didn't notice that the commit was after the version and it didn't came to my mind as the 1.0.2 release notes points to have fixed exactly this issue. Thanks for the clarification.
