### ISSUE TITLE
RxCollectionViewSectionedReloadDataSource() crashes on element count changes

### ISSUE THREAD

**Issue by urosk** [RxSwiftCommunity/RxDataSources#95]
When the datasource emits a changed model, a layout related crash happens.

This is an iOS 10 "feature", described here http://stackoverflow.com/questions/39867325/ios-10-bug-uicollectionview-received-layout-attributes-for-a-cell-with-an-index

It seems to work without issue after calling invalidateLayout in RxCollectionViewSectionedReloadDataSource.swift:
```
...
collectionView.reloadData()
collectionView.collectionViewLayout.invalidateLayout()
```

**Comment by kzaher** [comment]
Hi @urosk, 

Want do to a pr for this? 

What happens on animated updates and using animated data source?

It should work?

**Comment by urosk** [comment]
Hey @kzaher,

I made a pr.

The animated data source works fine 👍
