### ISSUE TITLE
Memory leak when bind through MVVM

### ISSUE THREAD

**Issue by pluckq** [RxSwiftCommunity/RxDataSources#97]
Hello, can you please tell me, is this my fault, or lib, i've got strange memory leak when binding PublishSubject array from my viewModel to table view through dataSources:

```swift
let teamsDataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, Team>>()
        teamsDataSource.configureCell = { ds, tv, ip, item in
            let cell = tv.dequeueReusableCell(withIdentifier: "TeamCell", for: ip) as? TeamCell
            cell?.configure(team: item)
            return cell!
        }
        viewModel?.playerteams.asObservable().bindTo(tvTeams.rx.items(dataSource: teamsDataSource)).addDisposableTo(rx_disposeBag)
```

In my viewmodel: 
```swift
let playerTeams: PublishSubject<[SectionModel<String, Team>]> = PublishSubject()
```

```swift
var profile: MyProfile? {
        didSet {
            playerTeams.onNext([SectionModel(model: "", items: profile?.player?.teams ?? [])])
}
```
<img width="1600" alt="2017-02-16 22 12 03" src="https://cloud.githubusercontent.com/assets/5019512/23032270/a97fe0ec-f495-11e6-960c-e45733ca0e2e.png">

**Comment by kzaher** [comment]
Hi @pluckq ,

I think it's probably on your end.

I see at least one memory leak in your screenshot.
```
btnAddAmplus.rx.tap.bindNext {
     self.viewModel ...
```

**Comment by zishanj** [comment]
I am also facing memory leak issue and it never happens with simple data binding like `.bind(to: tableView.rx.items(cellIdentifier: EventCell.Identifier, cellType: EventCell.self))`. But when I try to use it with  sectioned data with datasource using `RxTableViewSectionedReloadDataSource`, it never free up occupied resources.

**Comment by nickwph** [comment]
any updates on this?

**Comment by reshadf** [comment]
I am experiencing this too

**Comment by imanhn** [comment]
I am having memory leak with RXTableViewSectionedReloadDataSource too!
It does not free up the memory.

Any updates?

I am going to try disposing it manuallly.

**Comment by MattyAyOh** [comment]
using the Profiler, I have confirmed that there is an extra retain happening in this code:

    private func bindTableViewDataSource() {
        let dataSource = RxTableViewSectionedAnimatedDataSource<PublicMessagesSection>(configureCell: { _, tableView, indexPath, item in
            let cell = tableView.dequeueReusableCell(withIdentifier: PublicChatMessageCell.identifier, for: indexPath)
            (cell as? PublicChatMessageCell)?.delegate = self
            (cell as? PublicChatMessageCell)?.setPublicMessage(item)
            return cell
        })
        
        dataSource.animationConfiguration = AnimationConfiguration(insertAnimation: .none, reloadAnimation: .none, deleteAnimation: .none)
        dataSource.decideViewTransition = { (_, _, _)  in return ViewTransition.animated }

        viewModel.messagesStream
        .do(onNext: { [unowned self] _ in
            self.newMessagesCount += 1
            self.updateChatPillIfNecessary()

            let previousOffset = self.tableView.contentOffset.y
            if previousOffset > 0 {
                let heightOfRow = self.tableView.rectForRow(at: IndexPath(row: 0, section: 0)).height
                let newOffset = CGPoint(x: 0, y: previousOffset + heightOfRow)
                DispatchQueue.main.async {
                    self.tableView.setContentOffset(newOffset, animated: false)
                }
            }
        })
        .bind(to: tableView.rx.items(dataSource: dataSource))
        .disposed(by: disposeBag)
        
    }

Profiler results:

```
229 | Retain | 1 | 10 | 00:04.802.543 | HelloWorld | PublicChatMessagesController.bindTableViewDataSource()
230 | Retain | 1 | 11 | 00:04.804.364 | HelloWorld | PublicChatMessagesController.bindTableViewDataSource()
231 | Release | -1 | 10 | 00:04.804.373 | HelloWorld | PublicChatMessagesController.bindTableViewDataSource()
```

If I comment out this method, my controller is properly freed.  It is unclear why there are 2 retains, I'm currently investigating so hopefully I can report an update, but it's not looking like it's in my code

**Comment by MattyAyOh** [comment]
Update:
I have tried making everything a weak ref (datasource, tableview, messagesStream): https://medium.com/@chuck.krutsinger/avoiding-rxswift-memory-leaks-87885bd0023d

I also moved `messagesStream` into `self` in this context,
and still saw the leak

I discovered when I swapped out `bind` with `subscribe`, everything worked out great.

What I ended up doing is assigning the `bind` disposable to a variable, which then the owner of this controller disposes on it's own `deinit`. 

This seemed to work, everything was properly released 

Hope this helps somebody who stumbles across this in the future

**Comment by zishanj** [comment]
@MattyAyOh from your pointed code
```
let dataSource = RxTableViewSectionedAnimatedDataSource<PublicMessagesSection>(configureCell: { _, tableView, indexPath, item in
        let cell = tableView.dequeueReusableCell(withIdentifier: PublicChatMessageCell.identifier, for: indexPath)
        (cell as? PublicChatMessageCell)?.delegate = self
        (cell as? PublicChatMessageCell)?.setPublicMessage(item)
        return cell
    })
```
Just try making `self` unowned in this context.

**Comment by MattyAyOh** [comment]
hey @zishanj , thanks for that! you're right, it worked :) My thought at the time was that because `delegate` was declared as a `weak var`, that it wouldn't hold a strong reference to `self`

What I failed to remember is that the `configureCell` closure was capturing `self`

No bugs here :D

**Comment by zishanj** [comment]
@MattyAyOh Glad it helped. :)

**Comment by zishanj** [comment]
@kzaher apply this small patch plz.
