### ISSUE TITLE
No real `reload` of cells

### ISSUE THREAD

**Issue by jochenschoellig** [RxSwiftCommunity/RxDataSources#99]
Hello,

I have a question and at the same time an issue if I understand everything well. I tested it now on my own app and in the example and on both apps I see the same effect.

If I use an "SectionedAnimatedDataSource" and I replace an item then I expect a `reload` of that cell. What is happening instead is first a `delete` and then an `insert` of that cell. This causes some big troubles in my collection view where I handle some animations based on insertion and deletion.

Why is there no `reload`?

Kind regards
Jochen

**Comment by kzaher** [comment]
Hi @jochenschoellig ,

If you remove entity with some id and then insert another one, you will get two animations.
Reload animation happens when the same entity changes properties.

**Comment by jochenschoellig** [comment]
Hi @kzaher,

can you help me with an example?

I have the following **ViewModel**:
```
    /// Stores one section with many message elements as items
    private var sectionViewModels = [SBSectionViewModel(header: "", items: [SBMessageElement]())]
    
    /// Public getter for sections
    ///
    /// - Returns: An observable of sections.
    func getSections() -> Observable<[SBSectionViewModel]> {
        return SBModel.sharedInstance.getMessageElements()
                    .map { elements in

                        // Fill the only section with message elements
                        self.sectionViewModels[0].items = elements
                        
                        return self.sectionViewModels
                    }
    }
```

Appending an object like this works great:
`elements.value.append(element)`

If I replace an object like this I get first **delete** and then **insert**:
`elements.value[i] = element`

How do you mean you answer?

Thank you!
Jochen

**Comment by lingzlu** [comment]
@jochenschoellig I'm having a similar issue. Looking at Differentiator.swift, it seems like SectionedAnimatedDataSource will only work well for insert/delete. The implementation of Item equatable dictates same entity or not. If equatable return false,  Differentiator will treat it as an item removed from initialSections and a new item is inserted into finalSections. The update event(reload) is relate to EditEvent moved or movedAutomatics (line 555 in Differentiator.swift). But I don't quite understand the logic there. @kzaher, it would be nice if you can help clarify how update/reload works with SectionedAnimatedDataSource.

**Comment by jochenschoellig** [comment]
Thank you, @lingzlu! I saw the same issue at **Differentiator.swift**. The Changeset in line 667 is never filled with `updatedItems`.

@lingzlu, do you have any workaround? If we can't solve that then I have to go back to a "normal" implementation of my collection view.

**Comment by lingzlu** [comment]
@jochenschoellig one possible workaround is define your item properties as observable type, and bind them to the UI components. However, this solution does not work well for me as the height of of cells doesn't get adjust with updated contents. You can also try make an array of observable properties and reload the cell if any of them changes, it can be little tricky as you might create a cycle that reload the cell all the times.

**Comment by jochenschoellig** [comment]
Hi @lingzlu,

can you explain me the problem with the cells heights?
Have you ever tried this one: https://github.com/safx/ObservableArray-RxSwift

Kind regards
Jochen

**Comment by lingzlu** [comment]
@jochenschoellig For my scenario, the cell contains information that would be hidden/show base on the item properties (I used UIStackView for this), there's also labels with dynamic height. So when an update happens, let say an imageView was original hidden and now visible, and a label text changed from 1 line to 4 lines of text. The cell will not draw correctly unless I reload the cell. 

I haven't tried ObservableArray-RxSwift. But it looks like a good option for what we need. The nice thing with RxDataSource is its Differentiator algorithm, which is generic and handle all data types. With ObservableArray, you do get more control over how you want to animate the changes. One thing to note is you would want a batch update if the data source changes completely, could be from a fetch update from server or diff sync feature.

**Comment by kzaher** [comment]
@lingzlu It's how it should work naturally IMHO. If you delete and add new entity, then you have two animations. If you update entity, then you have one update animation.

How one chooses it's ids and equality is up to them.

Usually table and collection views are being used to represent some data that has identity (users, posts, comments, etc.).

I guess we could explore some other algorithms also.

**Comment by scottrhoyt** [comment]
Perhaps there can be a new protocol created to describe entity-sameness with respect to the data source. `Equatable` can be extended to provide a default conformance for this new protocol, but there would still be an ability for a user to offer an override. Could that work?

**Comment by lingzlu** [comment]
@kzaher I agree with your points, I do think the algorithm is doing the right thing currently. It just lacks the support for actual update scenario. Let says we have a table with list of comments (with two properties: id and comment), if a comment has update on the server and the app fetched new data. When define Comment equality as lhs.id == rhs.id, the update would be ignore; if equality is id and comments, the algorithm would perform a 'update' using delete/insert. A more desired update would reload the cell only. 

@scottrhoyt I was thinking create a new protocol that indicate an entity is 'dirty', is that what you mean? So Equatable would define entity sameness with respect to the unique identifier only. And the new protocol dictates if the same entity has updated properties or not.

**Comment by scottrhoyt** [comment]
@lingzlu I think we are going down the same path, with some slight differences. I would think `Equatable` should retain the semantics of two entities being exactly equal (whatever that means in context). Obviously if the data source only uses an equality check to determine whether it is a new entity or not, then many common use cases will always look like a new entity. What is missing, I think, is a way to describe not that two entities are equal, but that they refer to the same thing. Let's call protocol `ReferenceEquatable`. It could look like this:

```swift
protocol ReferenceEquatable {
  func referencesSame(as entity: Self) -> Bool
}
```

We could extend `Equatable` to provide default conformance for this:

```swift
extension Equatable: ReferenceEquatable {
  func referencesSame(as entity: Self) -> Bool {
    return self == entity
  }
}
```

Now if we use `ReferenceEquatable` in the entity same-ness check inside the data source, the behavior remains the same as now. However, a user can offer an override to that behavior by explicitly defining `ReferenceEquatable` for their entity.

```swift
struct Comment {
  let id: String
  let text: String
}

extension Comment: Equatable {
  static func == (lhs: Comment, rhs: Comment) -> Bool {
    return lhs.id == rhs.id && lhs.text == rhs.text
  }
}

extension Comment: ReferenceEquatable {
  func referencesSame(as entity: Comment) -> Bool {
    return id == entity.id
  }
}

/* ... or potentially ... */

class Comment {
  let id: String
  let text: String
}

extension Comment: Equatable {
  static func == (lhs: Comment, rhs: Comment) -> Bool {
    return lhs.id == rhs.id && lhs.text == rhs.text
  }
}

extension Comment: ReferenceEquatable {
  func referencesSame(as entity: Comment) -> Bool {
    return self === entity
  }
}
```

This way the user has control over what the data source considers a new entity needing deletion/insert and an update to the same entity. There are a couple of variations on this but the concept is the same. I would prefer a method like this where you positively declare entity equality and entity reference equality (and thus infer 'dirty'ness) to one where you declare a 'dirty'ness protocol.

**Comment by lingzlu** [comment]
@scottrhoyt that looks great!  I was thinking reversely, but It makes sense to leave `Equatable ` as what user define to be.   @kzaher What are your thoughts on this?

**Comment by rslim087g** [comment]
Did anyone figure this out yet? I spent days on this..

**Comment by crazytonyli** [comment]
I recently run into this issue, and I manage to fix it by correct my implementations of `AnimatableSectionModelType.Item`'s `IdentifiableType` and `Equatable`:
* For `IdentifiableType` protocol, items should have same `identity` if they represent same row. `identity` _shouldn't_ take UI appearance into account.
* For `Equatable` protocol, items are equal if they display same content, this is where we think about UI appearance.

I think [this code](https://github.com/RxSwiftCommunity/RxDataSources/blob/1.0.3/Sources/DataSources/Differentiator.swift#L651-L653) does the reloading trick.

**Comment by rslim087g** [comment]
My man! Spot on @crazytonyli .. looks like it worked for now!

**Comment by demchenkoalex** [comment]
@crazytonyli is right, I answered with an example here #118
